### ISSUE TITLE
First SF NodeSchool - Sat Feb 7th, 1-5p

### ISSUE THREAD

**Issue by cantremember** [nodeschool/sanfrancisco#1]
> continued from https://github.com/nodeschool/organizers/issues/92

it looks like we've all expressed interest in having a first NodeSchool event on Sat Feb 7th from 12-5pm at New Relic's class space.  let's continue the discussion here

**Comment by cantremember** [comment]
### the initial list of interested people

@duquet

> I think the following people have expressed interest. Please let me know if I missed anyone...
>
> Host: @groundwater (new relic) @llkats (craigslist)
> 8+ Mentors: @maxogden @jedireza @maxogden @tlhunter @cantremember @johnmarkos @bengl @linclark
> Organizers: @agminusthev
> Helpers: @terinjokes
> Unknown: @imurchie @dshaw @RichardLitt
> Advice: @mikeal

confirmed as available via comment:  @duquet @groundwater @agminusthev @llkats @jedireza @RichardLitt @cantremember

### excerpts from the prior thread

@agminusthev

> It was recommended we have a 5:1 ratio of attendees:mentors. We should consider capping the student headcount for the first event. Maybe 30 students and at least 6 mentors (8+ volunteers already!)
>
> it looks like New Relic's class space has 32 chairs and can comfortably hold some extra bodies.

@llkats

> Yes, tutor to student ratio would be great to know. How do we solicit and track volunteers?

@groundwater

> I've gotten a 90% yes on using the space (an exact date will help).
>
> Feb 7 looks good, but I have an obligation in Sacramento around 7pm. I'm assuming we will do this in the daytime?

@linclark

> If we start it at 1pm, then I think we can get away with having lighter snacks.
>
> For the one at Double Union, we did $5 tickets through Tito to ensure that people showed up.

**Comment by RichardLitt** [comment]
I'd be happy to be a mentor or a helper.

Also, @maxogden is in the Mentors' list twice.

**Comment by terinjokes** [comment]
I will be in Brussels on February 7th, so I'll be unable to help on the day of.

**Comment by dshaw** [comment]
@cantremember I'm afraid I'm probably in the Advice category too. My availability is extremely limited. I can also help recruit (too soon? :stuck_out_tongue_winking_eye:) and promote.

**Comment by agminusthev** [comment]
I just submitted an event request form to New Relic on 2/7 from 1-5pm. The odds are looking really good that they'll host us. Fingers crossed :)

**Comment by cantremember** [comment]
thank you @agminusthev .

in addition, the following questions came to mind

- @groundwater you'd hinted you might like to make this more of an 'advanced' NodeSchool.  you mentioned [Runtime.js](http://runtimejs.org/).  does anyone else have an idea for a Topic, advanced or otherwise? &dagger;

- how does a workshop like this get promoted?

- who wants to go in on the "lighter snack" fund?

&dagger; i'm gonna look at 2 of the core workshoppers, [Bug Clinic](https://github.com/othiym23/bug-clinic) and [Promise It Won't Hurt](https://github.com/stevekane/promise-it-wont-hurt), and see if they're fun. i don't have enough hands-on experience with [async-listener](https://github.com/othiym23/async-listener) and [continuation-local-storage](https://github.com/othiym23/node-continuation-local-storage) to build a workshopper of my own, but i find ThreadLocals-in-JavaScript to be kinda awesme

![](http://cdn.makeagif.com/media/1-10-2015/bgJDM8.gif)

**Comment by jedireza** [comment]
I'd like all skill levels to feel welcome. I can throw in on the snack fund.

**Comment by groundwater** [comment]
I am working on a *RuntimeJS Workshop* right now. If there is enough interest, we can hold a "kernel hacking in javascript" workshop.

**Comment by agminusthev** [comment]
New Relic confirmed for Feb. 7 1-5pm. 

Do we have a site to promote this event? Per the wisdom of previous NodeSchool organizers we'll probably want to consider charging a nominal fee of $5 for the event. Thoughts?

**Comment by RichardLitt** [comment]
@llkats is working on a site now. I think syncing with a Meetup group would probably be a smart idea, too.

**Comment by agminusthev** [comment]
I'm an organizer for SFNode so we can use that network if we'd like.

**Comment by agminusthev** [comment]
Another question, is this first come first served or are they submitting 'applications.'

The only other event I participated in similar to NodeSchool was Rails Girls. The big benefit of reviewing applications is making sure there's a good blend of people. The downside is that we would have to review applications and debate over who would get to attend.

**Comment by jedireza** [comment]
@agminusthev woo hoo! I'm glad the venue is confirmed. I agree the $5 cover is a good plan. When I attended an Oakland NodeSchool, attendees were paired with others at similar skill levels.

At first thought I'm not a fan of applications for the same reasons @agminusthev mentioned.

**Comment by jedireza** [comment]
@groundwater I read through the RuntimeJS docs. Very cool project btw. I'm interested in that workshop.

**Comment by llkats** [comment]
Wooo confirmed venue! I just pushed an initial site live to the gh-pages branch in this repo; will be sure to make an issue to update copy with the event details.

**Comment by llkats** [comment]
I opened some issues of tasks that need doing. Leave a comment to pick up a task, and please feel free to discuss and add more issues.

**Comment by sedouard** [comment]
Not available on the 7th but I'd love to get involved in future event as a helper or mentor! :-)

**Comment by jedireza** [comment]
We have a website:
http://nodeschool.io/sanfrancisco/

And started tweeting today:
https://twitter.com/nodeschoolsf

We've had 18 registrations so far.

**Comment by cantremember** [comment]
excellent work, @jedireza . especially the Complete Forking History in the footer!

**Comment by jedireza** [comment]
:fireworks: Thanks. I'm pretty sure @llkats did the footer.

**Comment by RichardLitt** [comment]
Woop.

**Comment by johnmarkos** [comment]
My child care has fallen through: I'm wondering whether it would be all right if I brought my children (7 and 9) to the event. I'd ensure they were quiet with books and perhaps screens, if necessary. I don't think they're quite ready to learn Node just yet, so they wouldn't really fall into the "student" category.

**Comment by johnmarkos** [comment]
This morning I tried installing Node on my son's Windows machine, and I noticed two issues. First of all, the directory where node resides was not in the PATH on install, so I had to go into Advanced Settings -> Environment to add it to the PATH. Secondly, npm expects a directory `C:\Users\<user>\AppData\Roaming\npm` to exist out of the box, but it didn't, so I had to go create that.

**Comment by Trott** [comment]
@johnmarkos I'm glad somebody is doing the legwork on Windows. It had crossed my mind that if someone has trouble installing Node on a Windows machine, I for one would be largely lost trying to help them.

**Comment by agminusthev** [comment]
Hey @johnmarkos it's a friendly space and I don't foresee any problems with your kids hanging out.

**Comment by agminusthev** [comment]
I'll need the attendee list and will also pull together the list of mentors so building security at New Relic will know who to let up. 

Can someone help me get this list? Thanks!

**Comment by jedireza** [comment]
@agminusthev I'll email you the attendees list. The mentors/organizers are at the top of #15

**Comment by dshaw** [comment]
@johnmarkos I've always been a big fan of bringing the kids along. (It's usually only stressful for you, the parent.) My kids came to the last SFNode which happened to be at New Relic. Nice space with ample room to stay out of the way or get involved, as appropriate.

**Comment by dshaw** [comment]
@johnmarkos Mine are 8 and 9.

**Comment by groundwater** [comment]
@johnmarkos should be fine!

**Comment by cantremember** [comment]
@groundwater i just scanned through your repos & npm packages and i do not see your Workshop for Runtime.js.  i'd like to run it through once on my own before playing a Mentor role for it -- even if it's a work-in-progress

could you please provide an npm package name?

**Comment by groundwater** [comment]
@cantremember unfortunately I still need to fix runtime before I can write the workshop.

**Comment by jedireza** [comment]
Congrats everyone. Our first event went great. Thanks you all.
