### ISSUE TITLE
Group Photos from September 2015

### ISSUE THREAD

**Issue by jedireza** [nodeschool/sanfrancisco#100]
![l1002050](https://cloud.githubusercontent.com/assets/979929/10121378/774dcf6e-649d-11e5-9d0d-e28747ff54ed.jpg)
![l1002054](https://cloud.githubusercontent.com/assets/979929/10121377/774dd478-649d-11e5-8306-e8dd7f377cb2.jpg)

**Comment by isurfbecause** [comment]
Awesome pic, thanks for posting and taking the pic @jedireza

**Comment by Fauntleroy** [comment]
Next time I'm gonna Photoshop you in, @jedireza

**Comment by austocratic** [comment]
Another awesome NodeSchool. Thanks Reza, thanks Lydia, thanks to all the mentors for volunteering your time.  Big shout out to Bryan for teaching the NPM workshop.  Those mentor led workshops present interesting challenges as a teacher, so thanks for your patience and enthusiasm.  It is much appreciated.

I would love to see more of these specialized workshops in the future.  I see them as a way for Node School SF to build on its community while still welcoming new attendees.

I look forward to the next one!

**Comment by Trott** [comment]
I can't believe no one else came wearing a Mr. Rogers cardigan. I think that should be a requirement for attendance next time.

**Comment by jedireza** [comment]
Closing since these are on the site now.

No joke. I've been wanting to buy some cardigans for a while now. So if you see me wearing one it wasn't because of what Rich said :stuck_out_tongue_winking_eye:
