### ISSUE TITLE
Mentor Registration for October 24th 2015

### ISSUE THREAD

**Issue by jedireza** [nodeschool/sanfrancisco#101]
Mozilla is hosting us on October 24th from 1pm - 5pm. The address is: 2 Harrison St, San Francisco, CA 94105

As before, we'd like to stay close to a 5:1 attendee:mentor ratio. We're accepting up to 50 attendees for this workshop. So we'll need about 10 mentors.

Mentors should commit to completing (or have already completed) the [core NodeSchool workshoppers](http://nodeschool.io/#workshopper-list) before the event. Having also completed elective workshoppers is a great bonus. We also encourage mentors to review the [Mentor Best Practices](https://github.com/nodeschool/organizers/wiki/Event-Mentor-Best-Practices) wiki page.

Comment to get involved or ask questions.

Confirmed mentors:

 - [x] @TheAlphaNerd
 - [x] @paulgrock
 - [x] @Fauntleroy
 - [x] @Trott
 - [x] @isurfbecause
 - [x] @LindsayElia
 - [x] @gregRV 
 - [x] @prattsj
 - [x] @dgbeck 
 - [x] @cantremember 

Organizers and helpers:

 - [x] @jedireza
 - [x] @llkats

**Comment by llkats** [comment]
:raising_hand:

**Comment by jedireza** [comment]
:grin:

**Comment by TheAlphaNerd** [comment]
me please!

**Comment by JacksonTech** [comment]
I'm still finding out if I can carpool to SF again, but I'm interested.

**Comment by paulgrock** [comment]
In

**Comment by jedireza** [comment]
@TheAlphaNerd thanks! :roller_coaster:

@JacksonTech sounds good, keep us posted. :car: :bus: :blue_car: :car: 

@paulgrock thank you! :rocket:

**Comment by Fauntleroy** [comment]
Y'all know you can't start without me.

**Comment by jedireza** [comment]
@Fauntleroy woot! :dancer:

**Comment by JacksonTech** [comment]
I've found transportation. I'm in.

**Comment by jedireza** [comment]
@JacksonTech nice, thanks! :fireworks:

**Comment by Trott** [comment]
I'd like to keep my perfect attendance record intact. In.

**Comment by jedireza** [comment]
@Trott bam! :100:/:100:

**Comment by jedireza** [comment]
:pager: @LindsayElia

**Comment by upekabee** [comment]
I'm out of town 😓😓😓

**Comment by Fauntleroy** [comment]
@upekabee 

![fry_feels](https://cloud.githubusercontent.com/assets/507047/10265316/3f8ec972-69e1-11e5-8fcf-d08d69f28356.gif)

**Comment by isurfbecause** [comment]
I'm in again 👍🏼👍🏼

**Comment by jedireza** [comment]
@isurfbecause thanks! :surfer:

**Comment by llkats** [comment]
Let's try to hold the remaining spots open for mentors who are from groups underrepresented in tech. We especially want to encourage these peeps to mentor so that we have a diverse team to represent to our attendees! 

If this is you, please volunteer! It's a great time and we're here to encourage and support you.

If this is not you, please come mentor with us in a future session!

**Comment by LindsayElia** [comment]
Sign me up! & thanks for the ping - I don't see the new issues unless I go looking for them.

**Comment by jedireza** [comment]
@LindsayElia thanks! :+1:

**Comment by gregRV** [comment]
I'm in!

**Comment by prattsj** [comment]
I'm in! 🙌

**Comment by dgbeck** [comment]
I've been looking forward to checkout out one of these events. Would be happy to mentor.

**Comment by cantremember** [comment]
yeah, i'm in ... wait ... if i count right, that'd make me the 11th

crap. *kicks can*. and here i finally had a free Sunday when i wouldn't be doing theater rehearsal

**Comment by llkats** [comment]
@gregRV, @prattsj, @dgbeck thanks all! Adding y'all to the list. :+1: :clap: :tada: 

@cantremember we miss you!!! Let's make room for 11 this time 'round. :sunglasses: 

GO TEAM MENTORS! :dancer:

**Comment by goodbedford** [comment]
@group, I just realized, I must bow out of Node School October. I am bummed  but I am also very happy because it is my 3 year wedding anniversary and I must spend it with my beautiful wife. I am pretty sure I have gathered 4 to 5 new Node Schooler to come in my absence. I will see you at the next one.
Have fun.

**Comment by smallhaxe** [comment]
Congratulations, @goodbedford! And well done on recruiting ;-)

@jedireza, @llkats: It seems all mentor needs are covered, but count me in if anyone can't make it.

High fives!

**Comment by jedireza** [comment]
Just a couple more days until our October workshop!!! :shipit:

**Comment by oazarova** [comment]
Hi everyone! How do I sign up for the actual workshop? Not sure how I came across this page (I started watching it a while back), but when I went to http://nodeschool.io/index.html, I didn't see a link to the 10/24 workshop in SF. Thanks in advance mentors! :)

**Comment by Fauntleroy** [comment]
Thanks for dropping in, @oazarova !

You can register here: https://ti.to/nodeschoolsf/october-24th-2015
The NodeSchool SF website can be found here: http://nodeschool.io/sanfrancisco/

**Comment by Trott** [comment]
I think @jedireza and @llkats already know this, but maybe if someone else wants to be pro-active, the way to get the info listed on the main NodeSchool page is to fill out https://docs.google.com/forms/d/1vYW-Yw82kt_q7WDgBY6gQqFrg3zuD2rDPXEG-cbq7e4/viewform

**Comment by jedireza** [comment]
@Trott yes, I might have spaced that again. Adding now.

**Comment by Trott** [comment]
@jedireza Well, I spaced on checking to see if you spaced, so we all spaced. I put it in the comment there so that everyone else knows too and maybe *someone* will remember to check next time. :-P

**Comment by JacksonTech** [comment]
Hi all, I am very sorry for the late notice, but I cannot make this NodeSchool. Carpooling plans fell through at the last minute because of unexpected but compelling reasons. Hopefully I'll see everybody at the next one!

**Comment by jedireza** [comment]
@JacksonTech thanks for letting us know. See you next time.

**Comment by nobso** [comment]
Thanks everyone, it was a pleasant experience! :smile:

**Comment by LindsayElia** [comment]
@llkats The school I mentioned to you to reach out to for potential future mentors is http://www.telegraphacademy.com/ . They're in Berkeley so it might make more sense for them to sync up with NodeSchool Oakland.

**Comment by llkats** [comment]
Thanks, @LindsayElia!

**Comment by goodbedford** [comment]
@group  Hi, I heard back from some of the people I sent to Oct NodeSchool. Two of them made it. They had a great time. Special shout out to @isurfbecause, my friend Riley said everyone was helpful and he would be back and that Winston helped him really understand callbacks. Thanks everyone.

**Comment by isurfbecause** [comment]
@goodbedford my pleasure. Riley and his buddy were very open to my suggestions. They weren't only satisfied with completing the exercises but wanted to learn more. :+1:

**Comment by llkats** [comment]
Thanks, all! Don't forget that we're all going to [Nodeschool Oakland](https://github.com/nodeschool/oakland/issues/16) on the 14th. See you then!
