### ISSUE TITLE
windows node event

### ISSUE THREAD

**Issue by llkats** [nodeschool/sanfrancisco#105]
Oh dang, check this out, a whole event on How To Node, Windows edition: https://www.eventbrite.com/e/nodejs-and-npm-for-the-windows-developer-tickets-19280683042 !

If you're interested, check it out!

**Comment by jedireza** [comment]
:tada: this is great

**Comment by TheAlphaNerd** [comment]
Already got my ticket

**Comment by Fauntleroy** [comment]
Am I allowed to go? I ain't got no Windows on my laptop

**Comment by TheAlphaNerd** [comment]
we can have a windows VM party before :P

**Comment by Fauntleroy** [comment]
Well, I do have the VMs...
