### ISSUE TITLE
Group Photos from October 2015

### ISSUE THREAD

**Issue by jedireza** [nodeschool/sanfrancisco#106]
![l1009652](https://cloud.githubusercontent.com/assets/979929/10991638/c1e2a014-8413-11e5-880b-7d276632b17b.jpg)
![l1009656](https://cloud.githubusercontent.com/assets/979929/10991639/c1f39dba-8413-11e5-84a3-3c22183ed450.jpg)

**Comment by isurfbecause** [comment]
Thanks Reza what a fun pic
