### ISSUE TITLE
Help me find photos / videos from Nodeschool International-day 2015

### ISSUE THREAD

**Issue by iancrowther** [nodeschool/sanfrancisco#107]
I have a look on google and twitter and did not find much, can you help me gather some assets?

**Comment by iancrowther** [comment]
The links in this issue are 404's now :-(

https://github.com/nodeschool/sanfrancisco/issues/69

**Comment by Fauntleroy** [comment]
I happen to have some photos from the event:

![cm_oak_november_imgp7113](https://cloud.githubusercontent.com/assets/507047/11815307/f57b14d2-a2ff-11e5-8ca3-ff02b906e979.jpg)
![cm_oak_november_imgp7130](https://cloud.githubusercontent.com/assets/507047/11815308/f57ba7a8-a2ff-11e5-8f9b-0bb639bb8f21.jpg)
![cm_oak_november_imgp7134](https://cloud.githubusercontent.com/assets/507047/11815306/f57b113a-a2ff-11e5-8a68-7f811e6ebab5.jpg)
![cm_oak_november_imgp7140](https://cloud.githubusercontent.com/assets/507047/11815309/f57f5ba0-a2ff-11e5-8652-3bab9655acee.jpg)
![cm_oak_november_imgp7167](https://cloud.githubusercontent.com/assets/507047/11815311/f590f202-a2ff-11e5-8767-d5801408acc8.jpg)
![cm_oak_november_imgp7172](https://cloud.githubusercontent.com/assets/507047/11815305/f578a79c-a2ff-11e5-8c29-cc6ab01a91af.jpg)
![cm_oak_november_imgp7178](https://cloud.githubusercontent.com/assets/507047/11815310/f58bdb1e-a2ff-11e5-82d8-69aa3652e4cb.jpg)
![cm_oak_november_imgp7183](https://cloud.githubusercontent.com/assets/507047/11815312/f591f2ba-a2ff-11e5-9995-be1ced2bbde0.jpg)

**Comment by iancrowther** [comment]
perfect, thanks for this
