### ISSUE TITLE
"dedicated pair" mentor type

### ISSUE THREAD

**Issue by llkats** [nodeschool/sanfrancisco#110]
I was thinking for the next event, I probably won't have the extrovert energy needed to float around the whole room assisting with questions, but that it might be fun to be a dedicated pair for a couple hours of the event with a newbie working on `javascripting` or `learnyounode`. And that having a "dedicated pair" mentor type might be a good way for newbie mentors to ease into the role. Thoughts?

**Comment by Trott** [comment]
I think it's a good idea but probably not worth formalizing so as to avoid the added cognitive load for organizers and attendees. 

Perhaps you can announce that you are hoping to pair with an attendee during the round of Mentors Introducing Themselves! 

That sort of information is (to my mind) far more relevant and timely than the usual "I work at Fancy Company X" boring biographical details. :-) 

You can even say (if you want) that you are specifically looking to pair on the streams workshop or whatever it is you'd most like to help someone with.

**Comment by jedireza** [comment]
> And that having a "dedicated pair" mentor type might be a good way for newbie mentors to ease into the role.

@llkats I read this as shadowing or mentor training. And I like this idea a lot! I've even thought about extending our organizer pool in a similar way. If however this is a dedicated mentor for one attendee... I had a similar idea recently. When I played it out in my head, I imagined a lot of down time since once an attendee gets unblocked, they're on their way until (maybe) another blocker surfaces.

**Comment by teone** [comment]
@llkats a bit late on this, I'm the Italian guy who join today...

In Italy we normally propose 4/5 workshop for events and then why try to create groups working on the same workshop. This normally helps a lot both mentors and developers as the both know what they'll be facing... People are normally shy and does not group by themselves...
