### ISSUE TITLE
Mentor Registration for February 27th 2016

### ISSUE THREAD

**Issue by jedireza** [nodeschool/sanfrancisco#113]
Mozilla is hosting us on February 27th from 1pm - 5pm. The address is: 2 Harrison St, San Francisco, CA 94105

We're accepting up to 70 attendees for this workshop. So we'll need about 10-ish mentors.

Mentors should commit to completing (or have already completed) the [core NodeSchool workshoppers](http://nodeschool.io/#workshopper-list) before the event. Having also completed elective workshoppers is a great bonus. We also encourage mentors to review the [Mentor Best Practices](https://github.com/nodeschool/organizers/wiki/Event-Mentor-Best-Practices) wiki page.

Comment to get involved or ask questions.

Confirmed mentors:

 - [x] @teone
 - [x] @cantremember
 - [x] @TheAlphaNerd 
 - [x] @iredelmeier
 - [x] @BerkeleyTrue
 - [x] @Trott
 - [x] @upekabee
 - [x] @prattsj
 - [x] @Shinobi881
 - [x] @janecakemaster
 - [x] @samccone

Organizers and volunteers:

 - [x] @jedireza
 - [x] @llkats

**Comment by jedireza** [comment]
Oh and BTW this month is our 1 year anniversary :tada: :birthday: :confetti_ball: :dancer:

**Comment by bengl** [comment]
Sadly, I will be in Canada. Next time.

**Comment by teone** [comment]
I would like to help as a mentor.

**Comment by jedireza** [comment]
@bengl it's been too long! I'm hopful for March have a good trip :airplane:

@teone that'll be great, thank you! :microscope:

**Comment by llkats** [comment]
Holy moly, one whole year! How time flies. Can't wait!

**Comment by cantremember** [comment]
i would like to help as a mentor

**Comment by llkats** [comment]
Yay @cantremember, it's been awhile! Glad to have you back! :)

**Comment by TheAlphaNerd** [comment]
o/

**Comment by llkats** [comment]
@TheAlphaNerd \o

**Comment by llkats** [comment]
PS: there will be cake :cake: :grinning:

**Comment by paulgrock** [comment]
Oh there's 🍰 I'm in

**Comment by iredelmeier** [comment]
I'd like to mentor! :grinning:

**Comment by Fauntleroy** [comment]
:cry:

**Comment by BerkeleyTrue** [comment]
I'd like to help as a mentor.

**Comment by Trott** [comment]
In!

**Comment by jedireza** [comment]
@paulgrock great to hear it :cake: 

@iredelmeier welcome and thank you! :cake: 

@BerkeleyTrue welcome and thank you! :cake: 

@Trott always a pleasure! :cake: 

@Fauntleroy is that a yes? :confused:

**Comment by jedireza** [comment]
:pager: @negomi @upekabee @LindsayElia @prattsj

**Comment by upekabee** [comment]
@jedireza yes!

**Comment by jedireza** [comment]
@upekabee rock and roll :guitar: :cake:

**Comment by prattsj** [comment]
@jedireza: count me in 🙌

**Comment by jedireza** [comment]
@prattsj thank you! :raised_hands:  :cake:

**Comment by llkats** [comment]
We're getting the band back together!!!

![](https://media.giphy.com/media/xdw4vjNB6ijfy/giphy.gif)

:cake: :cake: :cake: :cake: :cake:

**Comment by Shinobi881** [comment]
Me too please

**Comment by jedireza** [comment]
@Shinobi881 thank you :+1: :cake:

**Comment by negomi** [comment]
I can also mentor but it looks like you have enough people for now - let me know if anyone drops out :)

**Comment by jedireza** [comment]
@negomi wouldn't be the same without you :tada: :cake:

**Comment by negomi** [comment]
@jedireza :smile_cat:

**Comment by smallhaxe** [comment]
Can't wait to celebrate!

**Comment by janecakemaster** [comment]
hi! im coming from the east coast and I've snagged a ticket. If i so happen to bring a friend along, would that be ok? perhaps she can take my ticket and i can just mentor/volunteer/goof around

**Comment by Fauntleroy** [comment]
I'm vouch for this @janecakemaster . Maybe she wants to take over my door sentry duties? :)

**Comment by TheAlphaNerd** [comment]
double vouch for @janecakemaster legit AF

**Comment by jedireza** [comment]
Friends of my friends are friends :shipit:

@janecakemaster thank you and welcome! :balloon:

**Comment by janecakemaster** [comment]
@Fauntleroy @TheAlphaNerd @jedireza :tada:

**Comment by teone** [comment]
What do you think of proposing 3 or 4 (or 5) workshop to focus on? In Italy we were doing this as it helps people to collaborate (coder are normally shy!)

**Comment by jedireza** [comment]
@teone totally! We usually mention this during the introduction. On couple occasions we even had a dedicated track for one workshopper.

**Comment by paulgrock** [comment]
@jedireza @llkats I just found out about about a friend's going away party happening this Saturday. As much as I hate to miss Nodeschool, particularly the anniversary edition, are you two cool with me giving up my spot this weekend?

**Comment by llkats** [comment]
Aw, it won't be the same without you, @paulgrock!! Of course we're cool with it, you don't need our permission :smile: Catch you next time!

**Comment by Trott** [comment]
@paulgrock I totally understand, but my sneakers are miffed.

**Comment by paulgrock** [comment]
@Trott just make your fancy sneaks are featured prominently in the group photo so I can see them

**Comment by samccone** [comment]
I am totally down to be a mentor, or just a warm body that can help! I have a lot of experience setting up tables and folding chairs (can provide references on request).  

😃

**Comment by jedireza** [comment]
@samccone thanks! Welcome aboard :ship:

**Comment by negomi** [comment]
@jedireza @llkats I have caught some kind of cold/throat thing so I don't think I'll be able to make it tomorrow. Really sorry :mask:

**Comment by llkats** [comment]
Ohhh noooo! We're sorry to miss you! Feel better soon!!

**Comment by llkats** [comment]
@negomi Ohhh noooo! We're sorry to miss you! Feel better soon!!

**Comment by jedireza** [comment]
:cry: ... :cake:

**Comment by BerkeleyTrue** [comment]
What time should mentors be there?

**Comment by jedireza** [comment]
It's always nice for mentors to arrive a bit sooner, 12:40ish.

**Comment by BerkeleyTrue** [comment]
:+1:

**Comment by janecakemaster** [comment]
i had the best time yesterday!! thanks everyone for welcoming me in :heart_decoration:

**Comment by jedireza** [comment]
:pray: Big thanks to everyone! Our first year was a huge success. I look forward to the next year.
