### ISSUE TITLE
NodeSchool International Day

### ISSUE THREAD

**Issue by teone** [nodeschool/sanfrancisco#116]
May 21 will be the Nodeschool International Day,
http://nodeschool.io/international-day/

Should we organize something?

**Comment by jedireza** [comment]
May 21st might be a good NodeSchool Oakland day. @Fauntleroy maybe we could organize a fieldtrip to Oakland again? Also I'll be gone the weekend of May 28th so we might not host at Mozilla in May.

**Comment by Fauntleroy** [comment]
We can probably arrange something! I'll go ahead and pencil it in my calendar.

**Comment by Borgaard** [comment]
How can we contribute in organizing?

**Comment by teone** [comment]
I'm new in the area but if help is needed count on me!

**Comment by jedireza** [comment]
@Borgaard @teone thanks so much! Let's pick this back up after the weekend. Planning International Day for SF+OAK is going to be fun :+1: :shipit:

**Comment by jedireza** [comment]
:pager: we need to pick this backup. @Fauntleroy thoughts on the SF => OAK fieldtrip?

**Comment by Fauntleroy** [comment]
My only concern is how many people we can fit in **npm**, and how hot it will be. We'd have to find a sponsor to pay for the HVAC so our leaners don't sizzle.

**Comment by jedireza** [comment]
Would putting a max limit on ticket registration ease the worry about too many attendees?

**Comment by Fauntleroy** [comment]
Things should be fine so long as we don't get more attendees than we did at the last combined event

**Comment by jedireza** [comment]
Word! Once you have ticket registration setup and a mentor registration issue... I'll update the SF website to point to the right places.

**Comment by Fauntleroy** [comment]
You're gonna have March and April events first, aren't ya?

**Comment by jedireza** [comment]
Oh I was thinking this was in March :laughing:

**Comment by Fauntleroy** [comment]
@jedireza @llkats we need to get the venue for this event settled. Will we be having it at the unseen IBM location? Mozilla SF? NPM?

**Comment by TheAlphaNerd** [comment]
I'm back in town tomorrow. I can reach out to Wil and see if we can view
the space and confirm availability m

**Comment by jedireza** [comment]
Yup, last March I was talking with @TheAlphaNerd and Wil Pannell about possibly hosting at the IBM location. I will be in town on the 21st and I'm happy to reserve MozSF. I have not seen the IBM space yet. MozSF is pretty great for our needs (location, kitchen, snacks, living room).

**Comment by TheAlphaNerd** [comment]
It is worth mentioning that I am totally up for sticking with Mozilla. Do
we need a host from the company? Perhaps we should wait until a less
international event to experiment with spaces

That being said nothing to lose in checking it out.

**Comment by jedireza** [comment]
> Do we need a host from the company?

If you mean to get access to the Mozilla space, yes (that's me).

> Perhaps we should wait until a less international event to experiment with spaces. That being said nothing to lose in checking it out.

I agree.

**Comment by TheAlphaNerd** [comment]
I read your response wrong and thought you said you were not in town.

Let's stick with Moz and look at the IBM space as a potential future space.

**Comment by NorthDecoder** [comment]
Nodeschool International Day on 21-May 2016 is an
ad hoc celebration of all things nodejs.  I thought
it would be a good idea for me to volunteer
as the timezone coordinator.

I am writing to see if Tacoma-JS can collaborate 
somehow that day via video chat and gitter with your
group for some part of the time from 0830-1200 PST
following the guidelines at [:link:](http://nodeschool.io/international-day).

I can be reached at:
  http://www.meetup.com/Tacoma-JS/events/226412924/
  https://github.com/NorthDecoder

**Comment by jedireza** [comment]
Hi @NorthDecoder 

> I am writing to see if Tacoma-JS can collaborate somehow that day via video chat and gitter with your group for some part of the time from 0830-1200 PST following the guidelines at [:link:](http://nodeschool.io/international-day).

Our event starts at 1pm PST so we won't be around yet between 8:30a-12p.

Our group still needs to figure out if/how we're going to live-stream/video-chat/connect with other chapters that day.

**Comment by teone** [comment]
Do we want to register to the International Day list? https://docs.google.com/forms/d/13Kft4DVlrLgr0lsnhVGNgjV3CZJDkfsNysKxdeHPTFs/viewform?c=0&w=1&fbzx=-5207049056101054000

**Comment by jedireza** [comment]
> Do we want to register to the International Day list?

I did, I'm not sure why our logo isn't showing up there.

**Comment by llkats** [comment]
Thanks for a great Int'l Day everyone!!
