### ISSUE TITLE
Group Photos from January 2016

### ISSUE THREAD

**Issue by jedireza** [nodeschool/sanfrancisco#118]
:camera: Sorry for the delay :hourglass:

![l1004650_01](https://cloud.githubusercontent.com/assets/979929/13200563/8f09bbf8-d802-11e5-8324-7c9f885c4087.jpg)
![l1004655_01](https://cloud.githubusercontent.com/assets/979929/13200564/90dac576-d802-11e5-88d1-a8f4091f7cf7.jpg)

**Comment by SUPMIGUEL** [comment]
👌📸 Nice Photo!

**Comment by Fauntleroy** [comment]
<img width="379" alt="screen shot 2016-02-23 at 2 50 19 pm" src="https://cloud.githubusercontent.com/assets/507047/13269497/ce23f36c-da3c-11e5-8322-59c7d84056b7.png">

**Comment by jedireza** [comment]
LOL

**Comment by llkats** [comment]
@Fauntleroy :100:
