### ISSUE TITLE
Thank you mentors!

### ISSUE THREAD

**Issue by jedireza** [nodeschool/sanfrancisco#119]
__BIG THANKS__ to all of our mentors; past, present and future! :tada: :fireworks: :confetti_ball: 

If you're not mentoring this weekend feel free to register with Tito and join us for old times' sake. There are about 20 tickets remaining:

 - https://ti.to/nodeschoolsf/february-27th-2016

If you're unable to attend consider [spreading the word](https://twitter.com/nodeschoolsf/status/701506110298071041) to your Bay Area friends. We'd love to have a full house for our first birthday. :birthday: 

![nice](https://cloud.githubusercontent.com/assets/979929/13242087/1ec65694-d9a6-11e5-9343-eccc5ed4c653.gif)

:pager: @100ideas @agminusthev @azat-co @bdeanindy @bengl @BerkeleyTrue @brianleroux @cachrisman @cantremember @derekr @dgbeck @dshaw @duquet @erikasf @Fauntleroy @gregRV @groundwater @iredelmeier @isurfbecause @janecakemaster @jeffcarp @JonAbrams @kemitchell @linclark @LindsayElia @LizTheDeveloper @llkats @MrBri @negomi @noffle @prattsj @RichardLitt @Rolken @rstormsf @Shinobi881 @smallhaxe @stevengill @swang @teone @terinjokes @TheAlphaNerd @tlhunter @Trott @upekabee @wfro @Yonet

**Comment by RichardLitt** [comment]
Thanks, @jedireza! :) :cake:
