### ISSUE TITLE
Feedback Please!

### ISSUE THREAD

**Issue by bengl** [nodeschool/sanfrancisco#120]
Hey nodeshoolers!

This isn't *specifically* nodeschool related, but I put this together with nodeschool in mind, and I'd like to get some feedback from folks who've been helping to impart knowledge on others.

I found myself explaining `process.nextTick` and `setImmediate` pretty often, and it doesn't help that they're poorly named. So I made a module that gives them friendlier names, and does as good a job as I could at explaining the details at a very high level, for beginners.

https://www.npmjs.com/package/do-it-later

If you have time, please have a look. I'd like to know if I've messed anything up in the explanations in the readme. Any tips, PRs or issues on it would be helpful. Thank you!

**Comment by jedireza** [comment]
This is cool. It was informative and you describe things well. I'd use this as a learning tool for sure. Although the names of the standard functions are not great, I wonder if using non-standard names would create a crutch.

Philip Roberts did a talk about the event loop where he demonstrates a tool he created to visualize the event loop.
:movie_camera: https://www.youtube.com/watch?v=8aGhZQkoFbQ

**Comment by cantremember** [comment]
to explain the concept, a module with documentation is excellent -- thank you @bengl 

an additional approach might be to create a Workshopper with 3 or 4 exercises which demonstrate the concepts.  your motivation for your module seems to be around imparting knowledge, and i'd suggest that there's no better way for a student to come to an understanding than by trying it out themselves.  it should be reasonably easy to construct the exercises to produce predictable, assertable results around `nextTick`, `setImmediate`, `setTimeout` and `setInterval`

**Comment by teone** [comment]
@bengl great job!

I have no experience with creating workshopper (as @cantremember suggest)  but I like the idea. In case you want to proceed in that way I'll be glad to help!

**Comment by cantremember** [comment]
looks good, @bengl

**Comment by llkats** [comment]
Nice job, @bengl! I like how comprehensive you are with the documentation.

One thing that confused me was who this module is for. If I were a beginner, I don't know that I would think to search npm for a renaming library if I were struggling with those functions. Maybe a workshopper or koan library like Dan suggested would help as a strategy for putting it out there. I might suggest adding a section at the top that defines clearly the problems you observed and who the module is intended for, as well as how they might use it exactly (in a side project? in production code?)

Also I recommend staying away from language like "poorly named functions" in your first sentence. The use of "poorly" there reads like a value judgment of the authors of that API to me (they did a bad job and they should feel bad), whereas saying these function were confusingly or ambiguously named is less judgmental.

**Comment by bengl** [comment]
Thanks everyone for the feedback!

@jedireza Yeah, it's very crutchey. This is one thing a workshopper could solve. First by introducing `do-it-later`, and then taking it away as soon as all the concepts are covered.

@cantremember Yes! A workshopper is a great idea. Maybe this can be worked on at the next Nodeschool, or at workshopper-hack-night.

@llkats Right! I suppose I was thinking I'd direct people to the module as needed in order to help explain concepts to them, but if they're finding it organically (or even if they aren't), it makes a lot of sense to state the purpose/audience. Also, I'll find a better wording for "poorly named".

**Comment by jedireza** [comment]
@bengl would you like to keep this thread open?

**Comment by bengl** [comment]
Nah I'll close it. Thanks again everyone for the feedback!
