### ISSUE TITLE
Want to give a talk at the SFNode Meetup on April 7?

### ISSUE THREAD

**Issue by isurfbecause** [nodeschool/sanfrancisco#121]
Hi mentors,

We are looking for speakers to present at the SFNode Meetup on April 7.  We have two speaker slots available. We try to fill one slot for a "beginner" talk and the other with an intermediate to advanced topic. We would encourage first time speakers to present about any pain points they experienced and how they overcame them. Give me a shout at winsyee@gmail.com if you would like to present :)
http://www.meetup.com/sfnode/events/223344182/

**Comment by jedireza** [comment]
@isurfbecause could this be for anyone and not just mentors?

**Comment by isurfbecause** [comment]
@jedireza yes it could be for anyone. Thank you for the correction.

**Comment by teone** [comment]
@isurfbecause should be something hardly related to Node Development? I would like to make a talk sometimes on how node can speed up Front End development... Probably I can't be present on April 7th, but if it can work I'll start figuring out something for the next event...

**Comment by isurfbecause** [comment]
@teone your talk on how to speed up Front End Development sounds great. Feel free to reach out if you need help getting your talk together or need a second pair of eyes on your slides. :+1:

**Comment by teone** [comment]
@isurfbecause sure talk to you tomorrow!
