### ISSUE TITLE
Mentor Registration for March 26th 2016

### ISSUE THREAD

**Issue by jedireza** [nodeschool/sanfrancisco#123]
Mozilla is hosting us on March 26th from 1pm - 5pm. The address is: 2 Harrison St, San Francisco, CA 94105

Mentors should commit to completing (or have already completed) the [core NodeSchool workshoppers](http://nodeschool.io/#workshopper-list) before the event. Having also completed elective workshoppers is a great bonus. We also encourage mentors to review the [Mentor Best Practices](https://github.com/nodeschool/organizers/wiki/Event-Mentor-Best-Practices) wiki page.

Comment to get involved or ask questions.

Confirmed mentors:

 - [x] @Fauntleroy
 - [x] @TheAlphaNerd
 - [x] @BerkeleyTrue
 - [x] @Trott
 - [x] @isurfbecause
 - [x] @Shinobi881
 - [x] @smallhaxe
 - [x] @paulgrock
 - [x] @jeffcarp
 - [x] @LindsayElia
 - [x] @iredelmeier
 - [x] @samccone
 - [x] @SUPMIGUEL
 - [x] @azat-co

Organizers and volunteers:

 - [x] @jedireza
 - [x] @llkats

**Comment by Fauntleroy** [comment]
I would like to attend in accordance with the Treaty of NodeSchool BFFs.

![emissary_of_the_gorgonites](https://cloud.githubusercontent.com/assets/507047/13404598/4299e882-decf-11e5-84a7-c0fe04c502eb.gif)

**Comment by jedireza** [comment]
@Fauntleroy done and done! Thank you :+1:

**Comment by TheAlphaNerd** [comment]
o/

**Comment by jedireza** [comment]
@TheAlphaNerd o/ Thanks! :sunglasses:

**Comment by BerkeleyTrue** [comment]
I'm down

**Comment by Trott** [comment]
In!

**Comment by jedireza** [comment]
@BerkeleyTrue welcome back. Thank you :+1: 

@Trott Charo is happy. Thank you :guitar:

**Comment by jedireza** [comment]
:pager: @negomi @upekabee @LindsayElia @prattsj @iredelmeier

**Comment by llkats** [comment]
:grinning:

**Comment by isurfbecause** [comment]
I had a good break last Saturday. I'm in.

**Comment by jedireza** [comment]
@isurfbecause welcome back. Thank you :surfer:

**Comment by Shinobi881** [comment]
Me too please!

On Mon, Feb 29, 2016 at 10:20 PM, Reza Akhavan <notifications@github.com>
wrote:

> @isurfbecause <https://github.com/isurfbecause> welcome back. Thank you [image:
> :surfer:]
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nodeschool/sanfrancisco/issues/123#issuecomment-190566876>
> .
>



-- 
Muhsin "Moose" Abdul-Musawwir
_____________________________


* Full-Stack Software Engineer*
    - Github <https://github.com/Shinobi881> - Shinobi881
    - LinkedIn <https://www.linkedin.com/in/muhsin81> - muhsin81
   __________________________

Educator/Trainer
A+ Certified PC Technician
Martial Artist
Capoeira Formado
Eagle Scout

**Comment by smallhaxe** [comment]
\o  me, too!

**Comment by prattsj** [comment]
WANT. But have surgery on the 23rd, so no go this month. 😞

Definitely in for April (+ for whatever's going down after 🙃).

**Comment by jedireza** [comment]
@Shinobi881 always a pleasure :+1: 

@smallhaxe it's been a while. Thanks :+1: 

@prattsj we'll see you in April :crying_cat_face:

**Comment by paulgrock** [comment]
I'm in if there is still space available

**Comment by teone** [comment]
Parent in town :) this time I'll be out...

**Comment by LindsayElia** [comment]
I can mentor this time. In if needed! :star2:

**Comment by iredelmeier** [comment]
I'm in too! :smile:

**Comment by jedireza** [comment]
@paulgrock @jeffcarp @LindsayElia @iredelmeier welcome and thank you all! :+1:

**Comment by samccone** [comment]
oh drat, if you need any more help more than willing

**Comment by jedireza** [comment]
@samccone yes please! Thanks :+1:

**Comment by SUPMIGUEL** [comment]
I attended already three times as a student, recently finished my bootcamp and if you still need help I would love to be my first time as a mentor, the last time I help other students and would love to continue doing it.

**Comment by jedireza** [comment]
@SUPMIGUEL that's great to hear! Thanks :raised_hands:

**Comment by bengl** [comment]
Room for one more?

**Comment by llkats** [comment]
@bengl 'course! <3

**Comment by azat-co** [comment]
hey @jedireza Azat is here (author of expressworks and meanworks). I'll be glad to stop by for mentoring. Do you expect a lot of participants? Do you want me to do the focused group on Express?

**Comment by jedireza** [comment]
@azat-co hey hey! :wave: Thanks for volunteering! :+1: 

Since we're teaming up with the OAK chapter I increased the usual 70 ticket max to 100 and (just checked) all tickets have been registered.

It may be late in the process for a planned-focused-session. Let's take the temperture of the room during announcments and see how many people would like to group up on those.

**Comment by azat-co** [comment]
@jedireza wow, 100 is awesome! more people — more fun. :tada:  so you might need the mentor volunteers so I'm coming. RE: focused-session, we can play by the ear, i.e., poll the room to see the interest.

**Comment by jedireza** [comment]
> wow, 100 is awesome!

Yeah, there is usually about a 50% no-show rate. In any case I expect a full house. :raised_hands:

**Comment by jedireza** [comment]
Mentor friends:‌ In #126 we're thinking about new ways to improve our events. One thing we'd like is for mentors to be present before attendees. This will help create a warm atmosphere. It will also help us with greeting and checkins. We also going to try out having a dedicated setup area so we can direct people there as they arrive.

Please try to show up between 12:15p - 12:30p :heart:

**Comment by jedireza** [comment]
:pray: :tada: :clap: As always, thank you so much for making this happen!

https://twitter.com/nodeschoolsf/status/713837112399831040
