### ISSUE TITLE
2016 improvements list

### ISSUE THREAD

**Issue by llkats** [nodeschool/sanfrancisco#125]
As I'm sure I said several times on Saturday's event, I can't believe it's been a whole year of Nodeschool SF! I've been doing a lot of thinking about our events lately. Now that we have the structure and content down, and experimented a little bit with focused sessions, I was trying to think of other things we could improve too! Here's my initial list that I was making on Saturday -- we can eventually make each item its own issue, but I wanted to organize things together in one place first.
- mentors
  - [ ] growing new mentors
  - [ ] lanyards (custom ones?)
  - [ ] CoC conflict training
- [ ] food (different than pizza)
- [ ] focused sessions (different topics and presenters!)
- [x] streamlining introduction announcements
  - always a work in progress, but recent edits have seemed productive
- [x] refactoring workshoppers, maybe as a focused session or hack session
  - see #132 and watch the issues for more announcements!
  - ongoing
- [ ] soliciting feedback (maybe in a followup event email)
- [ ] better messaging around what to bring and expect (like bring a computer with)
- [ ] increase diversity of mentorship group
- [ ] mentor summit - get ideas of direction from our mentors
- [ ] mentor and attendee surveys

Any other things we should have on our radar to think about?

**Comment by jedireza** [comment]
:clap: thanks for creating this issue

**Comment by llkats** [comment]
So re: CoC report handling, I finally remembered how [CascadiaFest handled reports last year](https://github.com/cascadiajs/2015.cascadiajs.com/blob/master/COC_REPORTING.md) and it's super good! Would like to adapt for our events and have a document on hand for mentors to be able to consult. Will work on it this week to have something available by International Day.

**Comment by llkats** [comment]
Also re: focused sessions, it occurred to me that maybe we should have an issue for monthly signups so we can organize that. Will re-approach when I get back from travels.

**Comment by llkats** [comment]
2016 is

![fred from portlandia writing the word "over" in steam on a window](http://38.media.tumblr.com/a1dd1cc3758e3c6670a0704848612048/tumblr_namg5c6rap1t8enq1o1_400.gif)

On to 2017!
