### ISSUE TITLE
Pre-March 26th Workshopper Hacking Session

### ISSUE THREAD

**Issue by jedireza** [nodeschool/sanfrancisco#127]
The idea is to work on fixing bugs and improving workshoppers, especially the core + popular electives.

We need to find a venue and choose a date+time. We're shooting for a Wednesday evening; the 16th or 23rd of March.

Original thread on Twitter: https://twitter.com/bengl/status/709478255661678592

**Comment by Fauntleroy** [comment]
I'll be busy on the 23rd.

**Comment by jedireza** [comment]
I can't make it this Wednesday the 16th. I'll be cutting it close, but can do it on the 23rd. I've put a hold on the 7th floor commons if we'd like to do it at MozSF (pretty sweet venue).

**Comment by llkats** [comment]
I'm in for either evening!

**Comment by llkats** [comment]
We could try this place out if we meet on the 16th: http://www.workshopcafe.com/#!home/mainPage. I'm sure there's other places that would work as well.

**Comment by bengl** [comment]
Since some nights are better for some and some better for others, maybe both? I can probably do both.

Also @llkats that place looks super duper neato. 

I suggest both of:

* **March 16** at Workshop Cafe, 6PM-whenevs
* **March 23** at 7th Floor MozSF, 6PM-whenevs

**Comment by llkats** [comment]
JUST KIDDING CAN'T DO THR 23RD SRY SRY

**Comment by TheAlphaNerd** [comment]
16th is a bitttt short notice, but the 23rd is Purim 

¯\_(ツ)_/¯

**Comment by llkats** [comment]
Also there is always next month for mentor hackery!

**Comment by samccone** [comment]
I plan on running through all of the basic examples on windows this week :+1:

**Comment by cantremember** [comment]
i am seconding the next-month-mentor-hackery proposal!

a Wednesday night sounds like a good pattern to follow -- @jedireza would any Wednesdays from March 30th on work for MozSF?  unless everyone else is sold on the 16th or 23rd, of course ...

**Comment by jedireza** [comment]
@cantremember I'm co-hosting a [Connected Devices SF](http://www.meetup.com/San-Francisco-Connected-Devices-Meetup/) event on the 30th so I'll be unavailable that day. Besides that, I'm sure most Wednesday evenings could work.

**Comment by llkats** [comment]
We doing Workshop Cafe tomorrow?

**Comment by jedireza** [comment]
We doing Mozilla 7th floor tonight?

**Comment by TheAlphaNerd** [comment]
No can do tonight, I've got a Purim Party... basically drunk jewish halloween

**Comment by Fauntleroy** [comment]
Can't do tonight, getting hell drinky.

**Comment by jedireza** [comment]
Ok I'm cancelling this for today. I'm happy to give it a shot again.
