### ISSUE TITLE
`left-pad`-pocalypse

### ISSUE THREAD

**Issue by bengl** [nodeschool/sanfrancisco#128]
In the wake of `left-pad`-pocalypse, some nodeschool workshoppers may be broken.

In particular, `stream-adventure` depends on `provinces` which was affected: https://github.com/substack/provinces/issues/20

It's possible that all of this will get resolved by Saturday, but in the event that it doesn't, do we have a contingency plan? Perhaps simply tell folks to avoid that particular one?

**Comment by llkats** [comment]
:rage: 

Could we find the needed dependencies, point them to local resources, and push unbroken workshoppers up somewhere?

**Comment by Fauntleroy** [comment]
Wasn't `left-pad` un-unpublished? https://twitter.com/seldo/status/712414400808755200

**Comment by bengl** [comment]
@Fauntleroy it was, but 272 other packages were also affected. The un-un-publish only affected `left-pad`. `provinces` is among the other 272.

**Comment by TheAlphaNerd** [comment]
https://github.com/mattdesl/install-if-needed/pull/2#issuecomment-200470234

**Comment by jedireza** [comment]
Status check. Can we close this issue?

**Comment by bengl** [comment]
Closing, since stream-adventure works now
