### ISSUE TITLE
Workshopper Hack Night (6pm, Wed Apr 13 @ Mozilla SF)

### ISSUE THREAD

**Issue by bengl** [nodeschool/sanfrancisco#132]
> Basically reviving #127 but this time with no deadline.

Mentors: Let's get together and make the workshoppers more awesomer! This means:

* Fixing problems with existing workshoppers.
* Updating some of them to be more in line with the current state of node, npm, web, etc.
* Writing brand-new ones (looking at you @kemitchell).

I'm currently suggesting **Wednesday, April 13**.  @jedireza Can we get space at Moz?

**EDIT**: Now that we have a place, date and time booked (see title), I'll list the folks attending here. Space is limited so if you're not listed here and there's less than 10-12 folks, ask and I'll add your GH handle.

* @Trott  
* @jeffcarp 
* @kemitchell 
* @jedireza 
* @bengl
* @cantremember 
* @jkup
* @BerkeleyTrue 
* @tlhunter

**Comment by TheAlphaNerd** [comment]
I'll be out of town on the 13th... but I'm also out of town most of April ¯\_(ツ)_/¯

**Comment by bengl** [comment]
@TheAlphaNerd you gotta escape the backslash in the shrug emoticon: `¯\\\_(ツ)\_/¯` --> ¯\\\_(ツ)\_/¯

**Comment by TheAlphaNerd** [comment]
ಠ_ಠ

**Comment by Trott** [comment]
Be sure to use GitHub's new Saved Replies feature to save the properly-escaped shrug emoticon for easy recall.

Also, I'm tentatively in for the 13th, I guess, sure, whatever.

**Comment by jeffcarp** [comment]
I've never worked on a workshopper before but I'm free on April 13 and if it would be useful I would definitely be interested in pairing on them :smile:

**Comment by kemitchell** [comment]
@bengl, thanks for mentioning me! It's really hard for me to watch more repos. I'd probably have missed out on this.

Incidentally, I did land on [a hokey name for the licensing workshopper](https://github.com/kemitchell/shark-repellent.js). There's a preview release up that verifies application of MIT in the simplest, one-author case up right now. Shouldn't be too hard to expand to more complex cases. The hard part will be the interactive bits, probably involving a GitHub bot.

**Comment by jedireza** [comment]
We're booked in the Yoshis room (Moz 7th floor space) starting at 6pm.

**Comment by cantremember** [comment]
sounds great! i will totally be there. i will heckle you all and be altogether less-than-helpful

**Comment by jkup** [comment]
This sounds fun! I'll be there!

**Comment by bengl** [comment]
@jedireza What's our capacity limit? Should we start a list and cut off once we're full?

**Comment by jedireza** [comment]
I was just going to post about that. Let's cap this first version at 10-12 people for now.

We should also think about food. Should we figure it out as a group the day of? Should we try to find a food sponosor?

**Comment by bengl** [comment]
Alright. Edited the description w/ names.

Food: I'm not too concerned. Let's figure it out on-site.

**Comment by kemitchell** [comment]
Not concerned about food, either. Can we eat in the room? Would be nice to pitch in on something.

**Comment by BerkeleyTrue** [comment]
I'm down. I've got an idea for a workshopper I'm excited about.

**Comment by jedireza** [comment]
> Can we eat in the room?

Yup :fork_and_knife:

:pizza: :hamburger: :fries: :poultry_leg: :meat_on_bone: :spaghetti: :curry: :fried_shrimp: :bento: :sushi: :fish_cake: :rice_ball: :rice_cracker: :rice: :ramen: :stew:
:oden: :dango: :egg: :bread: :doughnut: :custard: :icecream: :ice_cream: :shaved_ice: :birthday: :cake: :cookie: :chocolate_bar: :candy: :lollipop: :honey_pot:

**Comment by kemitchell** [comment]
:see_no_evil:

**Comment by llkats** [comment]
Oh noooo I have plans that night 😭

**Comment by tlhunter** [comment]
Need a hand?

**Comment by jedireza** [comment]
:pager: reminder, this is tomororw. Any changes in attendance?

The front entrance reception desk will probably be closed for the day. I recommend entering through the side door on Harrison. Then head left and you'll see the security desk and elevators. Tell them you're here for NodeSchool and going to the 7th floor.

![mozsf-side-door](https://cloud.githubusercontent.com/assets/979929/14478210/54ce9a00-00c8-11e6-9921-f14b70c5ae85.png)

**Comment by bengl** [comment]
reminder:

@Trott
@jeffcarp
@kemitchell
@jedireza
@bengl
@cantremember
@BerkeleyTrue
@tlhunter

plz show up and help us make nodeschool workshops more awesomer-er. see the note above from reza on how to get in, etc. i'll be a little later, and @jkup has mentioned via twitter that he has the plague and therefore will not be there.

**Comment by jkup** [comment]
Sorry but also you are welcome 🤒

**Comment by bengl** [comment]
Oops, fat fingered that.

**Comment by BerkeleyTrue** [comment]
Omw!

**Comment by Trott** [comment]
Coming but won't be there until 7. Sorry about that!

**Comment by bengl** [comment]
let's gather ideas here https://etherpad.net/p/nodeschool-hack-night

**Comment by jedireza** [comment]
![cf-uavlw4aeivzs jpg large](https://cloud.githubusercontent.com/assets/979929/14516536/d43d5358-01b8-11e6-8ba5-7bb153290762.jpg)

https://twitter.com/nodeschoolsf/status/720457678301052928

**Comment by TheAlphaNerd** [comment]
So jelly! Have fun yall

**Comment by llkats** [comment]
How'd it go tonight??

**Comment by cantremember** [comment]
i was no help whatsoever  `(/◕ヮ◕)/`

**Comment by jedireza** [comment]
I think it went well.

**Comment by llkats** [comment]
I'll be at Nodeschool Oak on Saturday if anyone wants to do some hackalacking then :)
