### ISSUE TITLE
Mentor Registration for May 21st 2016

### ISSUE THREAD

**Issue by jedireza** [nodeschool/sanfrancisco#137]
Mozilla is hosting us on May 21st from 1pm - 5pm. The address is: 2 Harrison St, San Francisco, CA 94105

Mentors should commit to completing (or have already completed) the [core NodeSchool workshoppers](http://nodeschool.io/#workshopper-list) before the event. Having also completed elective workshoppers is a great bonus. We also encourage mentors to review the [Mentor Best Practices](https://github.com/nodeschool/organizers/wiki/Event-Mentor-Best-Practices) wiki page.

Please remember to arrive early (12:30pm) so we can cover logistics and give attendees a warm welcome.

🎉 __Focused session:__ There's a focused IoT workshop being held in the community space next to our main room. If you're familiar with [NodeBots](http://nodebots.io/), [Johnny-Five](http://johnny-five.io/), [Particle](https://www.particle.io/), [Losant](https://www.losant.com/) or similar things, please mention it. 

Comment to get involved or ask questions.

Confirmed mentors:

 - [x] @TheAlphaNerd 
 - [x] @Trott 
 - [x] @cantremember 
 - [x] @noffle
 - [x] @feross
 - [x] @bengl
 - [x] @teone
 - [x] @Shinobi881
 - [x] @tlhunter
 - [x] @BerkeleyTrue
 - [x] @samccone
 - [x] @iredelmeier
 - [x] @saposki  
 - [x] @veeweeherman

Organizers and volunteers:

 - [x] @jedireza
 - [x] @llkats
 - [x] @Fauntleroy 

Special guest presenter:

 - [x] @emilyrose

**Comment by TheAlphaNerd** [comment]
o/

**Comment by Trott** [comment]
:metal:

**Comment by llkats** [comment]
Righteous @TheAlphaNerd and @Trott ✨

**Comment by cantremember** [comment]
☜(˚▽˚)☞

**Comment by llkats** [comment]
@cantremember ☜(ﾟヮﾟ☜)

**Comment by cantremember** [comment]
also -- it's Talk Like Yoda Day.  *another focused session, we may need*

**Comment by negomi** [comment]
o/

**Comment by jedireza** [comment]
\o @negomi thanks for joining us! 🎉

**Comment by noffle** [comment]
I'm in! :tada:

**Comment by feross** [comment]
I'll help out too!

**Comment by jedireza** [comment]
@noffle @feross welcome aboard 🚢 and thanks! 👍

**Comment by paulgrock** [comment]
o7

**Comment by bengl** [comment]
https://www.youtube.com/watch?v=W-apaIOOoAo&t=27

**Comment by teone** [comment]
I'll join the party!

**Comment by jedireza** [comment]
@paulgrock @bengl @teone welcome back and thanks! 🎊

**Comment by jedireza** [comment]
:pager: @negomi @upekabee @LindsayElia @prattsj @iredelmeier

**Comment by prattsj** [comment]
👍 in

**Comment by llkats** [comment]
@prattsj 🙌 yay thanks!

**Comment by Shinobi881** [comment]
Dear mongod, please make it so I can be a mentor at `nodeschool`, with the most awesomest people ever.  🙏

**Comment by tlhunter** [comment]
I'm in

**Comment by jedireza** [comment]
@Shinobi881 @tlhunter thanks and welcome back! 🎉

**Comment by BerkeleyTrue** [comment]
I'm in!

**Comment by jedireza** [comment]
@BerkeleyTrue thank you! 🙏

**Comment by samccone** [comment]
I can help with this 🐐

**Comment by jedireza** [comment]
Thanks @samccone we needed a 🐐 pro

**Comment by iredelmeier** [comment]
Count me in!

**Comment by jedireza** [comment]
@iredelmeier thank you and welcome back 👍

**Comment by prattsj** [comment]
@jedireza: Oh noes! I have a work conflict Saturday and need to bow out. Will miss you guys... 😞

**Comment by jedireza** [comment]
@prattsj thanks for letting us know. See you next time 💯

**Comment by llkats** [comment]
Saturday is coming up quick, friends! Please remember to try to get to the space around 12:30-12:45 if possible so we can get organized beforehand. It's gonna be an awesome event, I can already tell! 🙌  😀

**Comment by negomi** [comment]
I've just realised I can't do this day after all! So sad to be missing it. See you next time 😿

**Comment by llkats** [comment]
@negomi oh no! We'll miss you, see you next time!! 😢

**Comment by saposki** [comment]
I am in

**Comment by llkats** [comment]
Hi @saposki, have you attended a NodeSchool event before?

**Comment by saposki** [comment]
yes I have also mentored at NodeSchool Oakland before 
SAPOSKI

**Comment by llkats** [comment]
@saposki Cool, welcome!

**Comment by paulgrock** [comment]
@jedireza @llkats I can't make it tomorrow either. Sorry I'm gonna have to duck out 😭

**Comment by llkats** [comment]
@paulgrock noooo 😭  😭  😭

**Comment by veeweeherman** [comment]
Hi I'm Vee, colleague of Muhsin's (@shinobi881). Hope this isn't too last minute--id like to volunteer to Mentor tomorrow/today as well!!

**Comment by jedireza** [comment]
@veeweeherman thanks and welcome!

All mentor friends; please arrive at 12:30p so we can get organized and have our mentor meeting.

**Comment by jedireza** [comment]
Intro slides: https://docs.google.com/presentation/d/1FZ2w2Q9Mx2HActq0krMSst2C2EoMtNmJemxu6YD7IC4/edit?usp=sharing

Shout-out slides: https://docs.google.com/presentation/d/1DP67730NFRD6GuGyYax43eOZL6W9kjmQ70sLo-7dTpc/edit?usp=sharing

**Comment by jedireza** [comment]
❤️
