### ISSUE TITLE
CoC report handling instructions

### ISSUE THREAD

**Issue by llkats** [nodeschool/sanfrancisco#139]
I wrote up a wiki page of How To Handle Reports. https://github.com/nodeschool/sanfrancisco/wiki/CoC-Report-Handling-Instructions. Would love feedback on the steps, wording, everything.

It seems very serious and kind of intense for our chill event, and it is my sincere hope that we never have to consult it. But it would be better to have a plan should something happen than to be unprepared.

🙏

**Comment by Trott** [comment]
Probable typo: `Mentor Instructions: Immediately After A Report` appears twice as a header. The second one seems to be Organizer Instructions rather than Mentor Instructions.

Suggestion: Might be good to spell out who the organizers are or include a link to a page that does. New mentors especially may not be aware of who is an organizer and who is a mentor.

Looks great to me by and large.

**Comment by llkats** [comment]
@Trott great calls on both counts! I've updated with your feedback.

**Comment by Trott** [comment]
Minor comment: It's not clear (to me, at least) what the meaning of this is: `Additional organizers from other chapters may join organizationally`

Does that mean `Organizers from other chapters may be present and function as organizers for NodeSchool SF events. For purposes of this document, they may be treated as organizers.` So (for example) Tim is effectively an organizer as well, at least for the purposes of this doc? Or is that only the case for events that are officially NodeSchool SF *and* NodeSchool Oakland events? Or something else?

**Comment by llkats** [comment]
I think that if organizers are joining us in an organizer capacity (such as joint SF/Oakland events), then they should handle reports in the way that is outlined in the document. However, if they are just joining in mentor or attendee roles, then not. Does that seem reasonable/make sense, before I try updating the doc again?

**Comment by Trott** [comment]
Yes, that totally makes sense.

I'm assuming you want comments here rather than others to go in and try to edit the wiki page directly. If that's not the case, let me know!

**Comment by llkats** [comment]
@Trott, if you (or anyone else) want to jump in, by all means go for it 😄  I appreciate it!

**Comment by Trott** [comment]
OK, I dove in! 

Thanks for doing this. Every month, when the CoC is discussed at the start of the event, it's always been marginally uncomfortable to contemplate the fact that I would kinda sorta be winging it if something did happen that came to my attention. It's :100: to have a procedure in place.

**Comment by jedireza** [comment]
Thank you. 🙏 👏

**Comment by TheAlphaNerd** [comment]
@llkats This is awesome, great idea!!

who has edit access to that wiki? I think it might be easier to lock down / audit / discover if it is in the repo as markdown as opposed to a wiki.

**Comment by llkats** [comment]
@TheAlphaNerd I think that people with Organizer level privileges have the ability to edit, not exactly sure. I put it in the wiki because that's where other organizational things are, and it still has [a sort of diffing capability](https://github.com/nodeschool/sanfrancisco/wiki/CoC-Report-Handling-Instructions/_history).

If someone wants to make a PR with a doc, I'd be all about it!

**Comment by TheAlphaNerd** [comment]
@llkats so I just did a test... I do not have organizer privileges on the repo, I just opened a PR and did not have the ability to land it.

I was able to open the wiki to make changes without any problems using the web interface.

We just had a problem yesterday where we noticed that someone had modified the node.js wiki and we had no idea for a couple days

**Comment by llkats** [comment]
@TheAlphaNerd okay, good to know.

Someone PR please?

**Comment by llkats** [comment]
I just ticked *Restrict editing to users in teams with push access only* in the repo settings. The settings note that "Public wikis will still be readable by everyone". 

I logged in to a different GitHub account and looked at the CoC wiki page; the "edit" and "new page" buttons are no longer available now. I think that's good enough. If anyone disagrees or wants to open that PR, please re-open this issue.
