### ISSUE TITLE
scroll page fills back button history

### ISSUE THREAD

**Issue by dmh2000** [nodeschool/sanfrancisco#14]
a single line scroll in the http://nodeschool.io/sanfrancisco web page causes an update to the back button history. after a little scrolling around the back button history is filled.  the problem is in custom.js

    if (window.curpage != $s.name) {
	var $link = $('ul.nav > li > a[href="#' + $s.name + '"]');
	$('ul.nav > li').removeClass('active');
	$link.parent().addClass('active');
       history.pushState(null, null, $link.attr('href')); ??? THIS IS EXECUTED ON EVERY PAGE SCROLL**
    }

at least, it is in chrome

**Comment by fmoliveira** [comment]
You're right, it's buggy. The original intention of this line was to push page states so the user can copy and paste the URL to a friend to land in the same section the first user was reading, but this was surely coded with few attention (by me).

I'll fix it and send a PR. Thanks for the bug report. :smiley:

**Comment by fmoliveira** [comment]
Fixed by @llkats in #17.
