### ISSUE TITLE
focused sessions for June, July, August

### ISSUE THREAD

**Issue by llkats** [nodeschool/sanfrancisco#141]
People really seem to like the focused sessions! This is an issue to solicit topics and speakers for focused sessions for the summer months.

Initial ideas:
  - intro to the terminal
  - intro to programming (ie, step through `javascripting`)
  - `git-it`

Volunteers for speakers and suggestions for topics welcome!

**Comment by feross** [comment]
I am happy to do a focused session on P2P technologies using @mafintosh's excellent [p2p-workshop](https://github.com/mafintosh/p2p-workshop), and if it's popular, maybe another one on p2p primitives like DHTs, etc.

Thoughts?

@mafintosh Want to come to SF and do this with me?

**Comment by TheAlphaNerd** [comment]
@feross please do this

**Comment by mafintosh** [comment]
@feross good idea! which dates are you thinking?

**Comment by teone** [comment]
@feross @mafintosh that looks super interesting! 

What about a session about testing?

**Comment by feross** [comment]
@mafintosh Whichever month you can be in the US! June 25 or July ?? is best for me.

@llkats Do you know the date in July?

**Comment by jedireza** [comment]
Jumping in... our July event will probably be July 30th. We shoot for the last Saturday of the month and adjust for special events like holidays or like international day 😉.

**Comment by TheAlphaNerd** [comment]
Just a heads up that NPM camp is July 30th… maybe do it a week early?

**Comment by jedireza** [comment]
Thanks for sharing the news about npm camp. 🙏

**Comment by BerkeleyTrue** [comment]
I'd like to do a focused session on the React workshoppers. I won't be able to make it for the June meetings, but I can for July.

**Comment by jedireza** [comment]
@BerkeleyTrue that's great. Do you plan on using the [`learnyoureact`](https://github.com/kohei-takata/learnyoureact) workshopper?

**Comment by BerkeleyTrue** [comment]
I haven't decided between that or the thinking-in-react lessons yet

**Comment by teone** [comment]
@BerkeleyTrue I would like to attend this one!

**Comment by nebrius** [comment]
Hiiii!

So I chatted with the @jedireza yesterday, and the rest of the NodeBots SF organizers today, and I have a proposal for everyone.

Currently, we change venues every meetup, and finding a new venue every month has gotten to be unsustainable for us. Given the success of the last IoT focused topic by @emilyrose (so I hear, I was in Detroit and couldn't make it sadly), @jedireza and I think there's room for something more regular.

So here's what @jedireza and I chatted about last night: the idea is that we merge NodeBots SF into NodeSchool SF. Every other month's focus session would be a "come play with hardware" meetup. NodeBots SF has quite a bit of hardware, most of which technically belongs to NodeSchool as it turns out (long story), so getting hardware for the meetup will be straight forward.

What does everyone think?

**Comment by nebrius** [comment]
Oh yeah, I suppose it could be helpful to mention what [NodeBots SF](https://github.com/nodebots/sf) is for those who are unfamiliar 😅.

NodeBots SF is a monthly (in theory) meetup where attendees hack on a themed hardware+JavaScript project. They're very hands-on focused and relatively undirected, go at your own pace like NodeSchool is. You can see a list of our past meetups at http://www.meetup.com/nodebotssf/.

It was originally created by @dshaw a few years ago after the success of [NodeBots Day](https://github.com/nodebots/nodebotsday), and I came on as lead organizer a little under two years ago.

**Comment by Shinobi881** [comment]
@nebrius Sounds awesome!

**Comment by jedireza** [comment]
👍 I like the idea of incorporating NodeBots. As focused sessions seem to be gaining interest, I think the every-other-event being a NodeBots session is good. Also if we don't have a focused session scheduled, we could always fallback to NodeBots.

As I'm no NodeBots pro, I'm curious how best to support attendees. Do we have two or more people dedicated to help leading these sessions?

**Comment by llkats** [comment]
Oh hai from Norway!

Sounds like an interesting proposal! I definitely understand the difficulty of lining up venues for a monthly event, we're so lucky to have Moz host us every month. 

I have a small misgiving around the wording of "merg[ing] NodeBots SF into NodeSchool SF". I won't speak for Reza, but for myself, with my other commitments, wrangling the regular meetups is about as much as I can manage right now. I just would like to make sure that the planning for NodeBots-focused sessions occurs by NodeBots people in NodeBots spaces. 

As a followup to Reza's question, who would coordinate mentors/teaching assistants (NB or NS?)? Would we be able to designate a focused session by the time that registration occurs, so we could potentially line up another focused session? (Based on the last session, we (NodeSchool) definitely need to do a much better job of describing and promoting the focused sessions.)

I think that, if there is to be an ongoing relationship between the two meetups, then the way I would like to characterize that relationship is that NodeSchool hosts NodeBots, not that they are the same event.

**Comment by llkats** [comment]
Actually, let's move NodeBots focused session discussion 👉  [over here](https://github.com/nodeschool/sanfrancisco/issues/145) 👈 .

**Comment by llkats** [comment]
Re: July: I would selfishly be okay with moving NodeSchool a week early because I will be on a plane that Saturday. 😿  But I also like consistency, so no worries if we keep it on the 30th.

At the moment, it seems like we have @feross potentially leading a session in June and @BerkeleyTrue for July. Are people cool with that? Could we lock that down by (arbitrary date) the 7th maybe?

**Comment by feross** [comment]
I'm cool with doing a session in June. @mafintosh want to join on the 25th or 30th? If not, let's delay until you an join? It's your session after all :)

**Comment by jedireza** [comment]
PSA: 10 days and counting until the June 25th event. As of now, 67/70 general tickets have been registered. If we don't have a focused session, I'd like to open the general admission to 100. ❤️

**Comment by mafintosh** [comment]
@feross i'll check my calendar today and see if i can squeeze in a trip.

**Comment by llkats** [comment]
Rad! @mafintosh @feross could one of you write a few sentences about the workshop that we can add to the signup page? Please include any information about pre-requisite skills (eg, familiarity with the command line) for attendees.

**Comment by jedireza** [comment]
I'm excited for this P2P Workshop in June. Thanks @feross and @mafintosh! I made a ticket for this and [it's live](https://ti.to/nodeschoolsf/june-25th-2016). The description reads as follows:

> This is a focused session on P2P technologies hosted by @mafintosh and @feross. This is a more advanced session. You should be comfortable with JavaScript (javascripting), Node.js (learnyounode), Scope Chains & Closures (scope-chains-closures) and Streams (stream-adventure).

I guessed at the prerequisites, so please let me know what changes we should make to that soon as we'd like to start tweeting and spreading the word.

**Comment by feross** [comment]
Looks good to me!

**Comment by jedireza** [comment]
Great. [The tweet is up.](https://twitter.com/nodeschoolsf/status/743777989746384896) Let's distribute the news 😉

**Comment by jedireza** [comment]
Closing this thread. Please follow up on #146 for July and #147 for August.
