### ISSUE TITLE
Mentor Registration for June 25th 2016

### ISSUE THREAD

**Issue by jedireza** [nodeschool/sanfrancisco#142]
Mozilla is hosting us on June 25th from 1pm - 5pm. The address is: 2 Harrison St, San Francisco, CA 94105

Mentors should commit to completing (or have already completed) the [core NodeSchool workshoppers](http://nodeschool.io/#workshopper-list) before the event. Having also completed elective workshoppers is a great bonus. We also encourage mentors to review the [Mentor Best Practices](https://github.com/nodeschool/organizers/wiki/Event-Mentor-Best-Practices) wiki page.

Please remember to arrive at 12:30pm so we can get setup and have our mentor meeting.

Comment to get involved or ask questions.

Confirmed mentors:

 - [x] @feross
 - [x] @Trott  
 - [x] @jeffcarp
 - [x] @bengl 
 - [x] @cantremember 
 - [x] @samccone
 - [x] @iredelmeier 
 - [x] @upekabee 
 - [x] @mafintosh 
 - [x] @EmmaRamirez 
 - [x] @tlhunter 

Organizers and volunteers:

 - [x] @jedireza
 - [x] @llkats

**Comment by TheAlphaNerd** [comment]
OH NO! I'm out of town this time. Have so much fun  without me!

**Comment by feross** [comment]
I'm in!

**Comment by jedireza** [comment]
Thanks @feross!

**Comment by Trott** [comment]
In! Do note that this will be Pride weekend, so there will be competing events and probable street closures.

**Comment by jedireza** [comment]
Thanks @Trott! And thanks for sharing the news about Pride weekend. 👍

**Comment by noffle** [comment]
I'm out of town this time too. Have much fun!

**Comment by jeffcarp** [comment]
I'm in!!

**Comment by jedireza** [comment]
Thanks @jeffcarp!

**Comment by mickberber** [comment]
Hey @jedireza I am interested in helping on that day if you still need mentors.  I have previous experience volunteering teaching people to code in JS. Please let me know what additional steps I can take to help on 6/25. 
Looking forward to hearing from you,
Mick

**Comment by jedireza** [comment]
@mickberber thanks for getting involved! I do recommend people attend before mentoring. Have you been to a NodeSchool event before?

**Comment by bengl** [comment]
![i'm in](https://lh3.googleusercontent.com/AGazORXelDY-PJTgAzTQMwb7I7Xf40FINr8i8sMCfCN-EE6kTC-zPCUsnpU9Eao2gkKq=w300)

**Comment by mickberber** [comment]
Hey Reza,

I have not attended a Node School event. A friend of mine has though, and I thought it’d be a good opportunity to help out.

-Mick

**Comment by Shinobi881** [comment]
Me please!

**Comment by jedireza** [comment]
@mickberber I'd really like you to experience an event first hand before mentoring. Are you willing to give that a try first?

@Shinobi881 thank you!

**Comment by llkats** [comment]
@jedireza you forgot @bengl!! 😱

**Comment by jedireza** [comment]
Sorry about that. Thanks @bengl 🚀

**Comment by bengl** [comment]
![](https://s-media-cache-ak0.pinimg.com/736x/4b/83/bd/4b83bdd2b1e99f7cba6538506fa05860.jpg)

**Comment by mickberber** [comment]
Hey Reza,
I would totally be interested in still coming and seeing how it all works.

-Michael

**Comment by jedireza** [comment]
@mickberber yay! See you on the 25th 🎊

**Comment by nebrius** [comment]
I'm in :)

**Comment by jedireza** [comment]
Thanks @nebrius ✌️

**Comment by cantremember** [comment]
if you would please, let me in on this Mentoring action !!

**Comment by llkats** [comment]
You got it, @cantremember!!

**Comment by samccone** [comment]
:goat: :fish: :dancer: :tangerine: :wave:

**Comment by jedireza** [comment]
@samccone :wave: :goat: :fish: :dancer: :tangerine:

**Comment by iredelmeier** [comment]
I'm in! :)

**Comment by llkats** [comment]
@iredelmeier yassss! 🤘

**Comment by upekabee** [comment]
I'm free to mentor if you're still looking @jedireza :)

**Comment by llkats** [comment]
@upekabee always!!

**Comment by EmmaRamirez** [comment]
I want to be in! I'm part of node school Oakland if that helps!

**Comment by llkats** [comment]
@EmmaRamirez welcome and thanks! Please review our [mentorship guidelines](https://github.com/nodeschool/sanfrancisco/wiki/Mentorship-Guidelines-and-Advice) and [CoC report handling](https://github.com/nodeschool/sanfrancisco/wiki/CoC-Report-Handling-Instructions) documents and see you on the 25th!

**Comment by tlhunter** [comment]
I'm in

**Comment by llkats** [comment]
@tlhunter yay!

**Comment by jedireza** [comment]
Into slides:
https://docs.google.com/presentation/d/1kr2-LKk23_bJ595uNy7NRNTA41I0A-B9nbbvMp33w24/edit?usp=sharing

Shout-out slides:
https://docs.google.com/presentation/d/1xRojfDHNT_sRHGopir7BF4Z9jhgzhL8p_E-2zg8kvI4/edit?usp=sharing

Shout-out slides (auto play loop):
https://docs.google.com/presentation/d/1xRojfDHNT_sRHGopir7BF4Z9jhgzhL8p_E-2zg8kvI4/pub?start=true&loop=true&delayms=5000

**Comment by jedireza** [comment]
Thank you everyone for another great event. Until next time. ❤️
