### ISSUE TITLE
NodeBots and NodeSchool bffs 4eva?

### ISSUE THREAD

**Issue by llkats** [nodeschool/sanfrancisco#145]
Moving discussion [over from here](https://github.com/nodeschool/sanfrancisco/issues/141)!

### [@nebrius](https://github.com/nodeschool/sanfrancisco/issues/141#issuecomment-221748707)

> Hiiii!

> So I chatted with the @jedireza yesterday, and the rest of the NodeBots SF organizers today, and I have a proposal for everyone.

> Currently, we change venues every meetup, and finding a new venue every month has gotten to be unsustainable for us. Given the success of the last IoT focused topic by @emilyrose (so I hear, I was in Detroit and couldn't make it sadly), @jedireza and I think there's room for something more regular.

> So here's what @jedireza and I chatted about last night: the idea is that we merge NodeBots SF into NodeSchool SF. Every other month's focus session would be a "come play with hardware" meetup. NodeBots SF has quite a bit of hardware, most of which technically belongs to NodeSchool as it turns out (long story), so getting hardware for the meetup will be straight forward.

> What does everyone think?

> Oh yeah, I suppose it could be helpful to mention what [NodeBots SF](https://github.com/nodebots/sf) is for those who are unfamiliar 😅.

> NodeBots SF is a monthly (in theory) meetup where attendees hack on a themed hardware+JavaScript project. They're very hands-on focused and relatively undirected, go at your own pace like NodeSchool is. You can see a list of our past meetups at http://www.meetup.com/nodebotssf/.

> It was originally created by @dshaw a few years ago after the success of [NodeBots Day](https://github.com/nodebots/nodebotsday), and I came on as lead organizer a little under two years ago.

### [@jedireza](https://github.com/nodeschool/sanfrancisco/issues/141#issuecomment-222784595)

> 👍  I like the idea of incorporating NodeBots. As focused sessions seem to be gaining interest, I think the every-other-event being a NodeBots session is good. Also if we don't have a focused session scheduled, we could always fallback to NodeBots.

> As I'm no NodeBots pro, I'm curious how best to support attendees. Do we have two or more people dedicated to help leading these sessions?

### [@llkats](https://github.com/nodeschool/sanfrancisco/issues/141#issuecomment-222968933)

> Oh hai from Norway!

> Sounds like an interesting proposal! I definitely understand the difficulty of lining up venues for a monthly event, we're so lucky to have Moz host us every month. 

> I have a small misgiving around the wording of "merg[ing] NodeBots SF into NodeSchool SF". I won't speak for Reza, but for myself, with my other commitments, wrangling the regular meetups is about as much as I can manage right now. I just would like to make sure that the planning for NodeBots-focused sessions occurs by NodeBots people in NodeBots spaces. 

> As a followup to Reza's question, who would coordinate mentors/teaching assistants (NB or NS?)? Would we be able to designate a focused session by the time that registration occurs, so we could potentially line up another focused session? (Based on the last session, we (NodeSchool) definitely need to do a much better job of describing and promoting the focused sessions.)

> I think that, if there is to be an ongoing relationship between the two meetups, then the way I would like to characterize that relationship is that NodeSchool hosts NodeBots, not that they are the same event.

And... discuss.

**Comment by nebrius** [comment]
> NodeBots and NodeSchool bffs 4eva?

😍

> As I'm no NodeBots pro, I'm curious how best to support attendees. Do we have two or more people dedicated to help leading these sessions?

It can be done with one person, although two is preferable. I'm thinking these people will be NodeBots SF folks, so don't worry, no crash courses in NodeBots necessary! 😄 

> I have a small misgiving around the wording of "merg[ing] NodeBots SF into NodeSchool SF". I won't speak for Reza, but for myself, with my other commitments, wrangling the regular meetups is about as much as I can manage right now. I just would like to make sure that the planning for NodeBots-focused sessions occurs by NodeBots people in NodeBots spaces.

Yeah, planning will definitely be handled by NodeBots folks. Planning the sessions has historically been the easy part and the part that organizers are most eager to do.

> As a followup to Reza's question, who would coordinate mentors/teaching assistants (NB or NS?)?

This is an interesting question, and I feel somewhat existential. I think the people who coordinate mentors/teaching would be from NB, but this does raise a question of _where_ to do the organization. NB SF has a GitHub repo, a slack, and a meetup.com page, and what is the fate of these going forward? I'm not sure. I could see organizing everything in a parallel issue on this repo to mirror the main event issue to increase coordination between the focused session and the main event maybe? But that also may create too much chatter here?

> Would we be able to designate a focused session by the time that registration occurs, so we could potentially line up another focused session? (Based on the last session, we (NodeSchool) definitely need to do a much better job of describing and promoting the focused sessions.)

Yeah we should be able to get everything lined up before registration opens. I imagine that much of the time we'll be doing the [NodeSchool NodeBots workshop](https://github.com/tableflip/nodebot-workshop), which is easy to deploy and set up quickly.

> I think that, if there is to be an ongoing relationship between the two meetups, then the way I would like to characterize that relationship is that NodeSchool hosts NodeBots, not that they are the same event.

I think that makes sense too.

**Comment by llkats** [comment]
@nebrius thanks for addressing all of that! Puts any slight doubts I had at ease. We can figure out the mentors/coordination issues, but I am more than excited to host NodeBots at NodeSchool. Would you like to continue to discuss the details here, or in another issue?

**Comment by nebrius** [comment]
I think it makes sense to keep discussing here, it's pretty on topic IMO.

**Comment by jedireza** [comment]
After speaking with @llkats more about this yesterday. The primary concern for us is ensuring we have the right people to support attendees learning/questions. I think the easiest way to get started is by having NodeBots session leaders volunteer on our focused session threads like #146/#147. Thoughts?

**Comment by nebrius** [comment]
> After speaking with @llkats more about this yesterday, the primary concern for us is ensuring we have the right people to support attendee's learning/questions. I think the easiest way to get started is by having NodeBots session leaders volunteer on our focused session threads like #146/#147. Thoughts?

Sounds good!

**Comment by jedireza** [comment]
Yay, I saw you posted on the August thread. First steps are underway. 🎉  Closing this thread.
