### ISSUE TITLE
Focused session for August

### ISSUE THREAD

**Issue by jedireza** [nodeschool/sanfrancisco#147]
Original thread #141

**Comment by nebrius** [comment]
Let's do a focused session on https://github.com/tableflip/nodebot-workshop. NodeBots SF has the hardware for it already, so people just need to bring a laptop.

**Comment by llkats** [comment]
@nebrius are you going to lead?

**Comment by nebrius** [comment]
@llkats yep :)

**Comment by llkats** [comment]
@nebrius rad 😀

**Comment by doron2402** [comment]
hi @nebrius, need an extra volunteer?

**Comment by jedireza** [comment]
@doron2402 thanks for volunteering.

@all I'm closing this issue since [mentor registration is open for August 27th](https://github.com/nodeschool/sanfrancisco/issues/152).
