### ISSUE TITLE
Need at least 7 mentors :)

### ISSUE THREAD

**Issue by agminusthev** [nodeschool/sanfrancisco#15]
We would like the attendee:mentor ratio to be at 5:1. 

At present we've @groundwater, @linclark and @richardlitt confirmed as mentors. 

@maxogden @jedireza  @tlhunter @cantremember @johnmarkos @bengl your names have all come up at as being interested in mentoring. Are you available Saturday, February 7 from 1-5pm? If not that's a-ok :)

- - - -

Confirmed mentors:

 - [x] @jedireza
 - [x] @johnmarkos 
 - [x] @cantremember 
 - [x] @bengl 
 - [x] @wraithan 
 - [x] @Trott 
 - [x] @tlhunter

Organizers and helpers:

 - [x] @llkats 
 - [x] @RichardLitt 
 - [x] @agminusthev

**Comment by jedireza** [comment]
I'll be there. I think @llkats will be there too.

**Comment by johnmarkos** [comment]
I'm planning on being there.

**Comment by llkats** [comment]
I'm more than wiling to help with JS questions but might not be as strong with Node concepts, so I'm unsure if a tutor position would be right for me. I'll be at the event though!!

**Comment by RichardLitt** [comment]
I'm also not strong. Going to do what I can anyway.

**Comment by cantremember** [comment]
i plan on being there

**Comment by bengl** [comment]
Also planning on being there. Can tutor for probably 80% of the existing workshoppers.

**Comment by wraithan** [comment]
@agminusthev I'll likely be getting into SFO that morning and I can help mentor. I've ran and mentored at NodeSchool events in PDX.

**Comment by agminusthev** [comment]
Excellent! I'm looking forward to seeing everyone there :smile:

**Comment by Trott** [comment]
I'm late to this party but if there's still a  mentor shortage, I'd like to help.

**Comment by jedireza** [comment]
Ok we're fully booked for 35 attendees. I've updated the top thread with confirmed mentors and organizers/helpers. Do you all think we need another mentor?

Fun, fun, fun.

**Comment by jedireza** [comment]
:pray: BTW, sorry if I categorized anyone incorrectly.

**Comment by tlhunter** [comment]
Sorry for the late reply! I can be there Saturday to Mentor as well.

**Comment by jedireza** [comment]
Ok great @tlhunter thanks!

**Comment by johnmarkos** [comment]
I mentioned this in the other thread, but I'll bring it up here as well, to make sure it's OK. I'm planning on bringing my kids, ages 7 and 9, because my child care arrangements didn't work out. They'll keep quiet with screens -- they're not quite ready for Nodeschool yet, but they can play Minecraft.

**Comment by agminusthev** [comment]
@jedireza @groundwater @tlhunter @cantremember @johnmarkos @bengl @linclark @RichardLitt @llkats @wraithan @Trott friendly reminder tomorrow we've got Node School at New Relic's office :) 

I am planning on arriving at 12pm, if you could be there by 12:45pm that would be lovely. The event itself runs from 1-5pm. See you tomorrow!

**Comment by jedireza** [comment]
:fireworks:

**Comment by llkats** [comment]
I'll be there at 12!! \o/

**Comment by wraithan** [comment]
I'm going directly there from the airport. Should be there at noonish,
might need a couple mins to eat before helping to setup and such.

**Comment by linclark** [comment]
I have a little bit of a cold coming on and don't want to pass it on to others, so I'm going to bow out of mentoring unless it gets better in the next few hours. From the list in the post, it looks like there will still be > 7 mentors.

**Comment by jedireza** [comment]
@wraithan sounds good. @linclark get well soon.

**Comment by paulgrock** [comment]
Is there still a need for another mentor?

**Comment by jedireza** [comment]
That'll be great @paulgrock! Please come.

**Comment by paulgrock** [comment]
@jedireza cool, I'll be there.

**Comment by agminusthev** [comment]
Hey everyone! There is going to be someone down in the lobby letting people in close to the event start time. If you get here and don't see that person you can ping me on Twitter. My handle is agminusthev

**Comment by llkats** [comment]
I got going a little later than I'd've liked this morning, I'm hopping on my bike and heading over now. See you all soon!
