### ISSUE TITLE
Attendee Survey

### ISSUE THREAD

**Issue by llkats** [nodeschool/sanfrancisco#151]
I want to survey our present and past attendees about their experience specifically at NodeSchool San Francisco and with the NodeSchool workshoppers in general. My goal is to understand how attendees feel about NodeSchool and what improvements we can make. Below is the list of questions I've come up with so far - please give me any and all feedback/suggestions you have!

# NodeSchool SF survey questions

everyone who fills out a survey gets a free lifetime pass to a future NodeSchool (with available capacity)

## NodeSchool SF event experience
- do you feel prepared to know what to expect at an event?
- how many events have you attended?
- will you continue to attend NodeSchool SF?
- are the mentors helpful? do you get the support you need?

## workshoppers
- which workshoppers have you used?
- rate ease of use (1-5, very easy to use to very difficult)
- rate the quality of material (1-5, high quality to low)
- how could they be improved?

## overall community engagement
- how did you find out about NodeSchool SF?
- do you feel engaged with the node community?
- do you feel like you know where to go for more help, to progress in your learning? 
	- do you know what your next steps are?
- when you come to NodeSchool, what do you want to learn and why?
	- what do you want to do with NodeJS?

## general
- what do you like about NodeSchool SF?
- what could we do better?

**Comment by feross** [comment]
Great list of questions!

**Comment by Trott** [comment]
This looks great to me. I have two comments:

* Small comment: "ease of use" may be misinterpreted as "how challenging was the workshopper" when I think you're trying to get at usability; Not sure if there's anything to do there; just noting.

* Survey-writing is notoriously pitfall-laden. It's easy to write a survey that skews results or doesn't get you the information you think it will. (I know I said "this looks great to me", but this comment is also an admission that I don't know what I'm talking about!) It might be worthwhile to seek out the opinion of someone versed in this stuff. (I don't know where you'd find such a person unless you have a friend who works at Gallup or something.)

**Comment by Trott** [comment]
Oh, I'll also add:

* I think you cover all the areas that are worth covering. Like, there's no gaps that seem to leap at, at least not to me. So 👍 on that.

**Comment by llkats** [comment]
Thanks for the feedback so far, folks. I know that survey-writing is really hard to do without bias, so I'm trying as hard as I can. If anyone has any marketing contacts or other resources to proof the survey, I'd love to hear from them. I've created a Google Form, [which you can preview here](https://docs.google.com/forms/d/e/1FAIpQLScZY3VJozYXuDU-7vQkNle1r1a6_0qxkUICVqXp2gbX9mEJoA/viewform?fbzx=-7985693584892464000).

I've been thinking hard about what I want to learn from this survey. Here are the questions I would like to be able to answer from survey responses:

- Who are our attendees?
	- What is their background with tech?
	- What is their demographic background? How could we reach a more diverse set of attendees? (age, race/ethnicity, gender)
	- What are their goals w/r/t Node and tech? How can we help them achieve those goals?
- How do our attendees feel about NodeSchool SF events?
	- Do they find it valuable, and in what ways? (learn a lot, good networking, just have fun, etc.)
	- What is suboptimal about NodeSchool SF, and how can we improve?
	- What is suboptimal about the NodeSchool organization in general, and how can we improve?
	- What is good and bad about the workshoppers?
	- What is good and bad about the SF focused sessions?
	- Do attendees feel connected to the broader Node community?
	- Do attendees feel like they know how to continue their code/tech/node education?
- Feedback for mentors
	- What do mentors do that is great?
	- How can mentors improve?

Another motivation that I have is to gather insight and quotes about NodeSchool SF for an upcoming talk I'm giving at Node Interactive EU in September. I added a section about granting permission for me to do so, but if anyone feels it's inappropriate, please let me know.

Right now, I think the main problem with the survey is that it's _really long_. What questions could we remove outright?

As far as feedback on the form, please take the whole thing and let me know if you think the responses will answer the questions I listed above, if asking for permission to publish quotes in my talk is okay, if there are wording/language issues with any of the titles, questions, or choices, if I'm missing anything, and if I can make it more concise somehow.

Really appreciate everyone's time and feedback on this!

**Comment by jedireza** [comment]
Thanks @llkats!! I took the survey. It wasn't _that_ long, maybe some of the pages could be compressed so it felt shorter.

> ...how helpful were the mentors?

I think this could have been easier to read and answer with a simpler scale (very helpful, helpful, neutral, meh, not very helpful). Also, radio buttons instead of checkboxes. Multiple answers don't seem helpful here.

> Would you recommend NodeSchool to your friends/family/colleagues/acquaintances/people in general?

I'd change "Maybe, but with caveats." to just "Maybe"

- - - -

$0.02 💸

**Comment by llkats** [comment]
@jedireza thanks, Reza! Maybe it just looked really long when I was typing it all out in the same file. I guess I'm just nervous that a long survey might decrease the number of completions. I agree with the changes you suggested and will make those edits!

**Comment by llkats** [comment]
@jedireza I made those changes, and also added a question to the demographics section: "How do you describe your race or ethnicity?" I left it as a short answer response.

**Comment by llkats** [comment]
I'd like to send this survey out on Monday, so if anyone has any additional feedback, please speak soon or forever hold your peace ✌️

**Comment by llkats** [comment]
Sent it finally! Surveys are really hard. Also sending an email to 200+ people is pretty nerve-wracking. 👀 😵

I'll be tweeting the link from the NodeSchool SF account, but if anyone wants to spread the word, the link is here: https://goo.gl/forms/DhXAX4UBtkBElIPx1

WHEW.
