### ISSUE TITLE
Is NodeSchool SF seeking Sponsorship?

### ISSUE THREAD

**Issue by tlhunter** [nodeschool/sanfrancisco#157]
Is NodeSchool SF interested in receiving sponsorship from third parties?

I recently started an IEEE San Francisco Computing chapter and we're looking for events to help sponsor. My employer (as well as others) might be also interested in sponsoring.

If we had sponsors we could perhaps purchase kits for talks such as @nebrius's Arduino and Johnny Five talk. Or of course cover pizza.

**Comment by llkats** [comment]
Tom and I discussed this briefly at NodeSchool on Saturday and I asked him to file this issue :)

I think @jedireza's and my philosophy has been to strongly discourage recruiters, promotion, etc., at the event since we want to focus on learning. That being said, I don't really see there being a problem with making an announcement along the lines of, for example, "IEEE SF Computing bought us pizza today, yay thanks!" Especially if the group is another meetup or avenue of learning for our attendees. Mozilla has been soooo generous to us, and it might be nice to share the load around.

**Comment by BerkeleyTrue** [comment]
@tlhunter Any deets on this new chapter? I'm interested in joining.

**Comment by tlhunter** [comment]
@BerkeleyTrue You would at least need to become an IEEE member. If you do signup my account number is 93962465. Joining our chapter should be super easy after that, but I can get you more info.

**Comment by jedireza** [comment]
I wouldn't say we're _seeking_ sponsorship, though I'm not against trying to enhance what we have. I have always wanted to get customized mentor lanyards. 😉

**Comment by BerkeleyTrue** [comment]
@jedireza Bedazzled custom lanyards.

**Comment by nebrius** [comment]
So I've had this thought for a while, and maybe this is the right opportunity. We have a bunch of Arduino kits (an older revision of this one), but they've been through so many workshops that we've had to cannibalize a bunch of them for parts, to the point that only about a quarter or so of them are still fully stocked and working. We have all the arduino's still, the things we're missing are little things like motors, jumpers, etc. We should be able to replace just the missing pieces for considerably less than it would cost to replace the entire kits.

How much it would cost and how much needs to be ordered is an open question though. Someone (or preferably several someone's that isn't just me) needs to go through all the kits and test/catalogue what we need. Perhaps for the November session, which should be an off-session for NodeBots, we could set up in a corner somewhere and get a couple people together to help me catalogue and get a quote together.

Thoughts?

**Comment by tlhunter** [comment]
I'll run this by my employer on Monday!

They'd probably want their logo up on the big screen and for me to give a one minute "we're hiring" talk. Will update this thread with details.

**Comment by tlhunter** [comment]
(We haven't yet secured the funds from IEEE)

**Comment by nebrius** [comment]
> They'd probably want their logo up on the big screen and for me to give a one minute "we're hiring" talk. Will update this thread with details.

I don't mind, @llkats is this ok with you?

**Comment by llkats** [comment]
I'm okay with it for the attendees in the focused workshop. @jedireza, any thoughts?

**Comment by jedireza** [comment]
Ditto. I wouldn't mind giving sponsors a mention in our regular intros. Companies supporting open source is awesome and a commercial and/or hiring shout-outs are harmless IMO.

Maybe there's different levels of sponsorship. Intro mention, intro mention + shout-out rotation slide, etc...

**Comment by llkats** [comment]
@tlhunter would IEEE or OpenTable being willing to help us out with #187?

**Comment by tlhunter** [comment]
I will ask as soon as I can, though we have Monday off.

IEEE still doesn't have any funds :(

**Comment by llkats** [comment]
@tlhunter thanks!! IIRC, the pizza bill runs about $300, but we'd be grateful for any amount!

**Comment by tlhunter** [comment]
Our sponsor guy has been on vacation until today, I'm probing him for information now!

**Comment by jedireza** [comment]
FYI: The pizza has been closer to $400. Thanks for getting helping @tlhunter 🙏

**Comment by tlhunter** [comment]
I've confirmed that we can sponsor the food. I'll pay with my card and get it reimbursed.

Can we get an OT logo on the screen and can I say a few words at the beginning of the event?

**Comment by llkats** [comment]
Yay! Anything OpenTable wants, we're supremely grateful!

**Comment by jedireza** [comment]
🍕 !

**Comment by llkats** [comment]
This seems done for now. We can open new issues for sponsorship if it comes up again in the future.
