### ISSUE TITLE
Spooky NodeSchool for October 29th?

### ISSUE THREAD

**Issue by llkats** [nodeschool/sanfrancisco#158]
Would people be open to encouraging mentors/attendees to come in costume? I'm mostly excited because I already know what I want to be for Halloween 😁  👻

**Comment by Fauntleroy** [comment]
If nothing else, I can always reprise my simple-but-adorable dinosaur.js outfit:

![img_20160624_172708](https://cloud.githubusercontent.com/assets/507047/18413174/32453062-7755-11e6-8795-cb13e5149c00.jpg)

**Comment by llkats** [comment]
![hmm yes perfect](https://dl.dropboxusercontent.com/u/37968874/img/hmm-yes-perfect.jpeg)

**Comment by llkats** [comment]
It's super spoopy up in here 🙌  👍  👻  🎃
