### ISSUE TITLE
Anyone attending ForwardJS?

### ISSUE THREAD

**Issue by zelator29** [nodeschool/sanfrancisco#16]
Drop me a note - zelator@gmail.com or mitch@summa-tech.com!

I am the new coordinator for Pittsburgh NodeSchool :)

-Mitch

**Comment by Trott** [comment]
ForwardJS was today. It's over now. Mitch and I had a swell time. Dude knows good coffee. Total old-school Peet's customer from the "roast to order and we'll mail the beans to you" days.  He and I commiserated about working on mainframes running JCL back before the web existed (literally). But I digress. What I really want to say is: 

Someone should close this issue.
