### ISSUE TITLE
Mentor Registration for October 29th, 2016

### ISSUE THREAD

**Issue by llkats** [nodeschool/sanfrancisco#160]
Mozilla is hosting us on October 29th from 1pm - 5pm. The address is: 2 Harrison St, San Francisco, CA 94105 -- Comment to get involved or ask questions.

Mentors should:

 - Have already completed the [core NodeSchool workshoppers](http://nodeschool.io/#workshopper-list) before the event.
   - _Having also completed elective workshoppers is a great bonus._
 - Review the [Mentor Best Practices](https://github.com/nodeschool/organizers/wiki/Event-Mentor-Best-Practices) wiki page.
 - Arrive 30 minutes early so we can get setup and have our mentor meeting.

Confirmed mentors:

👻 @zerosquadron 
👻 @BerkeleyTrue 
👻 @samccone 
👻 @Trott 
🎃  @tlhunter (maybe)
👻 @bengl 
👻 @cantremember 
👻 @btamayo 
👻 @Fauntleroy 
👻 @paulgrock 
👻 @itsmed
🎃 you?

Organizers and volunteers:

👻 @jedireza
👻 @llkats

**Comment by llkats** [comment]
Also, let's make it a spooky one -- bonus high-fives for showing up in costume. See #158!

**Comment by zerosquadron** [comment]
I'd like to help out this time. I attended yesterday and talked to Lydia about volunteering after the workshop.
@skipzero

**Comment by BerkeleyTrue** [comment]
Comment

**Comment by llkats** [comment]
@zerosquadron: great to meet you yesterday, and welcome aboard!

@berkeleytrue: wat

**Comment by samccone** [comment]
🐐

**Comment by Trott** [comment]
In

**Comment by tlhunter** [comment]
I'm a maybe; I have an event out of town that morning.

**Comment by bengl** [comment]
![](http://i.imgur.com/PAXmykx.png)

**Comment by llkats** [comment]
Can't wait to see @bengl dressed up as Aragorn!!

**Comment by cantremember** [comment]
\ (•◡•) / pick me!  oh, pick me!

it will make for a ridiculous day -- because that night i'm on stage in

![image](https://cloud.githubusercontent.com/assets/50385/18863522/8e33320e-8446-11e6-8cf4-65857333b613.png)

**Comment by btamayo** [comment]
I'm in! :)

**Comment by Fauntleroy** [comment]
Me.

![woody](https://cloud.githubusercontent.com/assets/507047/19287810/30c5fc5a-8fb8-11e6-89c4-b7da65f544e6.gif)

**Comment by paulgrock** [comment]
In

**Comment by itsmed** [comment]
I volunteer as tribute!

**Comment by jedireza** [comment]
Welcome aboard @itsmed ⛵️

**Comment by llkats** [comment]
Hi everyone! Thanks for signing up to mentor. We're really excited to see you tomorrow. Please arrive at 12:30 to get oriented and ready to welcome our attendees. Also, if you would like a different picture for the thank-you slides than your GitHub avatar, please email me or nodeschoolsf@gmail or DM @nodeschoolSF with your preferred pic. Thanks! 👯

**Comment by llkats** [comment]
Here are some slides, lmk if I messed anything up! 👻 

- [Intro Slides](https://docs.google.com/presentation/d/1s95JjIIhBtHjjYoMNs1i-nkeeFfCxJrc4kJS5F2YS0A/edit?usp=sharing)
- [Shout-out Loop](https://docs.google.com/presentation/d/1eaRfchw2YrKnXf74-BIo9dm5KWbPzzxg3AXgSZUWKr0/edit?usp=sharing)

**Comment by btamayo** [comment]
Y'all I won't be able to make it today :( Another event ended up conflicting. I'm sorry 🙏 Next time, promise.

**Comment by llkats** [comment]
Thanks everyone!! It was extra spooky this month, great job!! 🎃  👻  ❤️
