### ISSUE TITLE
Mentor Registration for November 12th, 2016

### ISSUE THREAD

**Issue by llkats** [nodeschool/sanfrancisco#162]
We will be taking a field trip to Oakland this month! See https://github.com/nodeschool/oakland/issues/34 to sign up to mentor. 👯

**Comment by zerosquadron** [comment]
?. I've never attended an Oakland event. I'm happy to help or just attend. Not sure how to approach that one.

**Comment by llkats** [comment]
@zerosquadron no worries! @Fauntleroy and @smallhaxe are the hosts for Oakland and I'm positive they'd be happy to have you 😄

**Comment by llkats** [comment]
Done, thanks all!

**Comment by cehsu** [comment]
Hi there, I'd like to help mentor at the next event. Also, would it be of interest to host the next meeting at Hack Reactor?

**Comment by jedireza** [comment]
👋 Hi @cehsu, thanks for volunteering. Our next event is likely going to be in January. Just keep an eye on this repo (by watching) and you'll see the mentor registration thread open up with more details. 🙏
