### ISSUE TITLE
Mentor Appreciation Party

### ISSUE THREAD

**Issue by llkats** [nodeschool/sanfrancisco#163]
Last year, we skipped having the December event because of the holidays, and tbh it was a really great idea. I think we should do the same for this year, but I would like to hold a mentor appreciation get-together that month. @jedireza offered the rooftop of the Mozilla building as a potential party space, and this would be for anyone who has volunteered as a mentor, at any event or location, who happens to be in town. That means Oakland mentors for sure! (/cc @Fauntleroy @smallhaxe)

We're thinking Saturday, December 17th, hopefully in the afternoon. It could maybe be potluck-style for food/beverages? I think we just need to confirm that we can use the roof that day.

Let the organizing begin!

![computer dance party](https://dl.dropboxusercontent.com/u/37968874/gifs/computer-dance-dancing-party.gif)

The guest list: 🎩 

 - [x] @jedireza
 - [x] @llkats 
 - [x] @Shinobi881 
 - [x] @samarthgulati 
 - [x] @smallhaxe
 - [x] @zerosquadron
 - [x] @cachrisman
 - [x] @tlhunter
 - [ ] you?

**Comment by jedireza** [comment]
> We're thinking Saturday, December 17th, hopefully in the afternoon.

I'd like to see this go from early evening into the evening since the view changes so much when the sun is up and when the lights on the Bay Bridge come on. 🌉 

> It could maybe be potluck-style for food/beverages?

Personally, I'd rather have it catered and think it's would be easier on everyone that way. I don't want people to feel like if they don't bring something, they shouldn't come.

> I think we just need to confirm that we can use the roof that day.

Yes I do need to reserve the 7th floor commons. I'll update this thread soon.

**Comment by mikeal** [comment]
> I'd rather have it catered

Will Mozilla cover that or should I start looking for sponsors :)

**Comment by jedireza** [comment]
I've reserved the 7th floor commons on the calendar from 2pm - 8pm. If anything changes I'll be sure to update this thread.

> Will Mozilla cover that or should I start looking for sponsors :)

I'd like to do something nicer than our regular pizza budget allows (~$400), so getting a food sponsor would be great! I'm open to ideas on food too. Also, we'll need to bring our own 🍸 "beverages" 🍺.

**Comment by llkats** [comment]
We're a little less than a month out now!

If there will be food and bevs, we should probably keep track of RSVPs. Should I set up a Tito event for it? I'm planning to cross-post to nodeschool/organizers soon too, for any mentors/organizers who happen to be in town.

@mikeal, as @jedireza mentioned, sponsors would be totes super awesome! Is that still a possibility?

**Comment by zerosquadron** [comment]
Is there anyway I can help at all? Setup beforehand or anything? I'd kinda like to be able to leave once its done and not stick around but could for a bit at least if I'm needed. Also, do we need a sign up for it to get a rough sense of the numbers attending? It's quickly approaching and happy to help in any capacity I'm able! 😺

**Comment by llkats** [comment]
@zerosquadron thanks for volunteering and for reminding me!!!

Since catering has not been arranged yet, I'm thinking that it probably won't be happening. I personally don't have the capacity to be calling around to places or anything right now. I don't think it'd be that difficult or weird to ask people to bring snacks and dessert-type things if they want. People can bring store-bought or homemade stuff or adult beverages, whatever they want, or not, it's not a big deal! I'll do a Trader Joe's run to ensure a good spread.

I can easily make a ti.to page for people to sign up so we can gauge how many noms to get, but is there an easier way? People could even just comment here in the issue if they plan on attending. Thoughts?

**Comment by llkats** [comment]
I'll just call it: comment here if you will drop by for any amount of time on Saturday the 17th!!

**Comment by llkats** [comment]
Also, please spread the word far and wide!

**Comment by Trott** [comment]
In!

Question: Bringing the family: Cool or not cool?

**Comment by llkats** [comment]
🤔 

@Trott, I say: totes cool! SO's and kiddos welcome!

**Comment by Shinobi881** [comment]
Sounds great! Let me know if there's anything I can help with.

**Comment by jedireza** [comment]
> Since catering has not been arranged yet, I'm thinking that it probably won't be happening.

We'll have pizza at a minimum.

**Comment by samarthgulati** [comment]
I'm in. 
I can get cookies for dessert. :)

**Comment by smallhaxe** [comment]
Finally, in! 😌 

I can bring pie and/or beer and/or kombucha.

🍻

**Comment by zerosquadron** [comment]
I'm in. Have to go to the city anyway. Happy to help out beforehand if needed. Might not stay till the end, then again... 😈

**Comment by llkats** [comment]
Can't wait! If you chat with other mentors, let them know about the gathering!

**Comment by cachrisman** [comment]
![I'm in](http://i.giphy.com/oDOnRIDjxlCzC.gif)

**Comment by jedireza** [comment]
Sweet y'all. I added a checklist at the top of this post to keep track of the official guest list.

**Comment by tlhunter** [comment]
Sorry, just realized this is an RSVP thing! I'd like to go as well.

**Comment by jedireza** [comment]
Hello friends.

Our group is pretty small and there is no formal agenda today. Let's all meet down stairs like we normally do and head upstairs together (shuttling people up stairs one by one is a drag).

Once everyone is present, we can see what we all want to do. We can hang out up stairs and catch the view and then figure out what we want to do for food and drinks. We can order pizza or since we have a small enough group, we could also go to Palominos for food and drinks.

What are your thoughts? Can we all commit to showing up at the same time?

**Comment by llkats** [comment]
Sounds good to me! We could still plan on 2pm since that's what we told everyone before, but if we could reach a consensus, we could maybe meet at 4pm for sunset on the roof and then go inside somewhere warm.

If people could weigh in before we change the time, that'd be swell. Thanks for being flexible, everyone!

**Comment by zerosquadron** [comment]
I can do 2. See y'all then!

**Comment by BerkeleyTrue** [comment]
I'm in!

**Comment by BerkeleyTrue** [comment]
Sorry, y'all. I twisted my ankle last night. I was going to brave the pain but I thought it be better to be a party pooper at home.

**Comment by Trott** [comment]
Sorry to cancel at the last minute, but...I can't make it today. :-(

**Comment by jedireza** [comment]
Thanks for checking in @Trott.

I'm heading over to the office, just come to the front-door like usual. See you all soon.

**Comment by jedireza** [comment]
We are heading over to Palomino now

**Comment by smallhaxe** [comment]
Still at Palomino?

**Comment by llkats** [comment]
Thanks y'all! 'Til next year! ❤️
