### ISSUE TITLE
Mentor Registration for January 28th, 2017

### ISSUE THREAD

**Issue by jedireza** [nodeschool/sanfrancisco#167]
Happy New Year 🍾🎉

Mozilla is hosting us on January 28th from 1pm - 5pm. The address is: 2 Harrison St, San Francisco, CA 94105 -- Comment to get involved or ask questions.

Mentors should:
- Have already completed the [core NodeSchool workshoppers](http://nodeschool.io/#workshopper-list) before the event.
  - _Having also completed elective workshoppers is a great bonus._
- Review the [Mentor Best Practices](https://github.com/nodeschool/organizers/wiki/Event-Mentor-Best-Practices) wiki page.
- Arrive 30 minutes early (12:30p) so we can get setup and have our mentor meeting.

Confirmed mentors:
- [x] @skipzero
- [x] @Trott 
- [x] @jeffcarp
- [x] @samccone 
- [x] @Fauntleroy 
- [x] @tlhunter
- [x] @arayi
- [x] @paulgrock
- [x] @teone
- [x] @LindsayElia
- [x] @jennabelle
- [x] @BerkeleyTrue 
- [x] @MylesBorins
- [x] @feross
- [x] @addaleax
- [x] @cachrisman
- [x] @aylanismello
- [x] @samarthgulati

Organizers and volunteers:
- [x] @jedireza
- [x] @llkats

Slides:

 - [Intros](https://docs.google.com/presentation/d/1x-VdfC-MhqbeB-HjU15a7sxHyKthnklf57hFVRmWxRU/edit?usp=sharing)
 - [Events](https://docs.google.com/presentation/d/1WmmR_eQ8mSkOuPPbu4SGeqi7rViK_OEWZ06dTp5lmTo/edit?usp=sharing)

**Comment by skipzero** [comment]
I'm in! 🗡

**Comment by Trott** [comment]
o/

**Comment by jeffcarp** [comment]
Let's get down to business
To defeat the NaNs

**Comment by skipzero** [comment]
But I'm NaN... Even tho the gov'ment tries to make me one... 😛

**Comment by deonna** [comment]
I'm interested in mentoring - anything else I'd need to do besides showing up and completing the core?

**Comment by samccone** [comment]
:+1: in

**Comment by Fauntleroy** [comment]
![maladroits_cannot_handle](https://cloud.githubusercontent.com/assets/507047/21619274/d1b65ec0-d1a3-11e6-81d8-2a2c6ad83a98.gif)

Can I come?

**Comment by jedireza** [comment]
![oh-fo-sho](https://cloud.githubusercontent.com/assets/979929/21619739/dde3d518-d1a5-11e6-848d-e516a4408f0a.gif)

**Comment by jedireza** [comment]
@deonna nope that's it. Thanks! 🙏

**Comment by tlhunter** [comment]
:pizza: :man_technologist: :beers:

**Comment by Hylinn** [comment]
I'd be down for mentoring!

**Comment by jedireza** [comment]
Thanks @Hylinn 🙏

**Comment by arayi** [comment]
interested in mentoring too! :tada:

**Comment by jedireza** [comment]
Thanks @arayi 🙏

**Comment by paulgrock** [comment]
In

**Comment by teone** [comment]
Count me in!

**Comment by LindsayElia** [comment]
I'm interested in being a mentor if you still need folks, otherwise I'll just show up and work on a Node-related project. Thanks!

**Comment by jennabelle** [comment]
Im in!

**Comment by BerkeleyTrue** [comment]
I'm in!

**Comment by MylesBorins** [comment]
GUESS WHO IS GOING TO BE IN TOWN

**Comment by feross** [comment]
I'm in too! I just moved to SF so it's way easier for me to make it out to volunteer now!!!

**Comment by addaleax** [comment]
👋 Hey everyone, I’m going to be around and I’d love to help out, too!

**Comment by jedireza** [comment]
Wow, this is a huge mentor turnout for our first event in 2017. Thank you all. 🙏 

There are still some attendee tickets available (23). You can help reduce that number by sharing this link with your network: https://ti.to/nodeschoolsf/jan-28th-2017

**Comment by skipzero** [comment]
Was just thinking there might be more mentors than attendees! ;)

**Comment by Fauntleroy** [comment]
MENTOR PARTY! 🎊 

![kpop_dancing](https://cloud.githubusercontent.com/assets/507047/22043458/88419f4e-dcc4-11e6-9a2c-019549392e9c.gif)

**Comment by BerkeleyTrue** [comment]
Looks like we are sold out :)

**Comment by jedireza** [comment]
Yep we are, that makes 100 attendees registered (70 general, 30 for NodeBots). Our turnout is typically 50ish% so I expect a full house. Thanks again everyone!

**Comment by cachrisman** [comment]
Need another mentor? I'm late to the party I know but I'd love to help out!

**Comment by jedireza** [comment]
@cachrisman see you there 😃

**Comment by aylanismello** [comment]
Hey there. Still need some mentors? I'd love to lend a hand Saturday !

**Comment by jedireza** [comment]
@aylanismello thanks! See you there.

**Comment by samarthgulati** [comment]
If there is still room, I would be happy to help as well!

**Comment by jedireza** [comment]
@samarthgulati thanks! See you there.

**Comment by jedireza** [comment]
Some important announcements: 📣 

 - With 20 volunteers, we're going to close mentor registration.
 - It's highly likely we'll have more mentor effort than attendees will need.
   - I don't see this as a bad thing.
   - @llkats and I will try to recruit some of you to help fix bugs in workshoppers and/or work on #171.
 - Everyone please do show up on time (at 12:30pm).
    - We'd like to have a successful mentor meeting before attendees start showing up and be able to give them a warm welcome.

**Comment by Trott** [comment]
If it's not in violation of the spirit of the whole thing, I might try to persuade @MylesBorins, @addaleax, and maybe one or two others to assist with powering through reviewing some pull requests and trying to get the number of open PRs in the node repository below 300.

But if that's hijacking resources that could be better applied directly to NodeSchool pursuits, I'll refrain.

**Comment by llkats** [comment]
@Trott There are definitely a couple projects we could use mentors to pitch in on, especially the NodeSchool SF website and triaging some of the workshoppers that we can now update. I'd love to organize people for these efforts first (which is why it'd be extremely helpful for people to show up early!!)

Maybe after we've gauged how many people will be needed to mentor and work on NodeSchool projects, if there are still more people than projects, we can point them your way. How does that sound, Rich?

**Comment by Trott** [comment]
> Maybe after we've gauged how many people will be needed to mentor and work on NodeSchool projects, if there are still more people than projects, we can point them your way. How does that sound, Rich?

Sounds great.

**Comment by skipzero** [comment]
I'm more than happy to fix bugs or anything else needed. Of course that includes mentoring as well, but I'm very open to writing a little code too. 😼

**Comment by Hylinn** [comment]
@deonna and I have to, unfortunately, miss the event tomorrow in order to take care of some of @deonna's health issues.

**Comment by llkats** [comment]
@Hylinn sorry to miss you! @deonna feel better soon! Hope to see you both next time 😄

**Comment by llkats** [comment]
Programming note: Bryan is under the weather and we will be canceling the NodeBots session for tomorrow. I'm about to let the attendees (who signed up for those tickets) know that they are still welcome to attend the regular event. See y'all tomorrowwww!

**Comment by bengl** [comment]
Hi folks! Dec/Jan have been pretty hectic so I forgot to drop my name in here. I'll show up and mentor, if that's alright.

**Comment by jedireza** [comment]
@bengl of course. See you soon.

**Comment by skipzero** [comment]
ugh. I just woke up. :(
Sorry. I hope you had enough mentors. I feel awful for missing class. was looking forward to it.

**Comment by jedireza** [comment]
@skipzero s'all good, see you next time 😀

**Comment by feross** [comment]
Sorry for missing this – something came up for me at the last minute. Hope to join next month!

**Comment by BerkeleyTrue** [comment]
I apologies for not making it out this time.

**Comment by jedireza** [comment]
@feross @BerkeleyTrue thanks for commenting, we'll see you next time 😀

**Comment by jedireza** [comment]
Thanks everyone for another great event!
