### ISSUE TITLE
Focused Session for January?

### ISSUE THREAD

**Issue by jedireza** [nodeschool/sanfrancisco#169]
Any ideas for a focused session this month?

**Comment by jedireza** [comment]
📟 @nebrius

**Comment by skipzero** [comment]
what about the workshopper bug fixes, etc. talked about at the mentor appreciation get together? I like that idea.

**Comment by nebrius** [comment]
We can always do the NodeBot workshopper. We have the hardware, and the workshop is ready to go, so it's pretty off-the-shelf.

piggybacking off of @skipzero's idea, there are updates I really want to make to the NodeBot workshopper sometime, and we do need to refurbish the kits with the new parts too. It shouldn't take long if we get enough people to help, so maybe work that in to the beginning or something?

**Comment by jedireza** [comment]
> what about the workshopper bug fixes, etc. talked about at the mentor appreciation get together? I like that idea.

@skipzero I think we could work on this stuff in the common room just like workshoppers. I don't think it's well suited to be a _focused learning session_. Maybe we could setup people to pair program on specific issues though. 💡 

> We can always do the NodeBot workshopper. We have the hardware, and the workshop is ready to go, so it's pretty off-the-shelf.

@nebrius I think a NodeBots session will work great. I say let's do it.

Any objections? Anyone?

**Comment by jedireza** [comment]
NodeBots Workshop tickets are live:

 - https://ti.to/nodeschoolsf/jan-28th-2017/

**Comment by jedireza** [comment]
@nebrius I remember that we needed a switch and cables for the last event. Do you have that covered for the 28th? If not we should create a list and check it twice. 😉

**Comment by nebrius** [comment]
No other hardware needed this time :) Just tables and chairs!
