### ISSUE TITLE
website should offer the ability to send a push notification to alert people when the next scheduled event is.

### ISSUE THREAD

**Issue by samccone** [nodeschool/sanfrancisco#170]
We can make finding out about the next event(s) more proactive on our part by utilizing web push notifications.

docs:
https://developers.google.com/web/fundamentals/engage-and-retain/push-notifications/

cc: @gauntface

**Comment by benhalverson** [comment]
@Xabad should this still be done?

**Comment by Xabadu** [comment]
@benhalverson I think it would be cool to have it. Do you wanna go for it? We can sync at our next event if you want and talk about it as well 😄

**Comment by benhalverson** [comment]
Yep I’d like to work on it.

**Comment by gauntface** [comment]
Feel free to mention me on GitHub or nudge me on twitter if you have any questions (@gauntface)

**Comment by benhalverson** [comment]
What do you think about a button right below the mentor and learner buttons? @Xabadu @nebrius @tlhunter 
I'm attempting to follow the best practice of not immediately asking for permission to send notifications. 

![screen shot 2018-09-06 at 2 57 11 pm](https://user-images.githubusercontent.com/7907232/45187410-6e3e3d80-b1e5-11e8-9433-2e96d9664196.png)

**Comment by gauntface** [comment]
Might be worth rephrasing the text to "Get Notifications for future events" (assuming thats what you are going to contact people about.

**Comment by benhalverson** [comment]
@gauntface I agree.

**Comment by benhalverson** [comment]
@xeodou I haven't forgotten about this. I have a repo here I am working on. I'm using firebase and firebase cloud messaging.
https://github.com/benhalverson/nodeschool-webpush-notifications
