### ISSUE TITLE
2017 improvements list

### ISSUE THREAD

**Issue by llkats** [nodeschool/sanfrancisco#171]
We got some stuff done last year! Like streamlining introductions at the beginnings of sessions, [partnering with NodeBots](https://github.com/nodeschool/sanfrancisco/issues/145) to host regular every-other-monthly focused sessions, and [surveying our attendees for feedback](https://github.com/nodeschool/sanfrancisco/issues/165). 

I've carried over things from [last year](https://github.com/nodeschool/sanfrancisco/issues/125), and adding new stuff at the bottom.

Maybe this issue should actually be a GitHub project? I shall explore that.

How should we proceed with these goals? What else should we consider this year? 

- mentors
  - [ ] growing new and supporting current mentors
  - [ ] lanyards (custom ones?)
  - [ ] CoC conflict training (if people are interested)
  - [ ] increase diversity of mentorship group
- [ ] food (different than pizza)
- [ ] focused sessions (different topics and presenters!)
- [ ] refactoring workshoppers, maybe as a focused session or hack session
  - most of the main workshoppers have been moved under the [workshopper](https://github.com/workshopper/) org. We now should have much more luck landing PRs to `javascripting`, `learnyounode`, `stream-adventure`, `how-to-npm`, `levelmeup`, and `how-to-markdown`, among others. How can we, as a chapter, contribute?
- improve the website
  - [ ] refresh appearance
  - [ ] add information around what to bring and expect (like bring a computer with)
  - [ ] other feedback listed in the [survey results](https://github.com/nodeschool/sanfrancisco/issues/165) (mostly near the bottom)

**Comment by skipzero** [comment]
so should these be done outside of 'class'? I'm happy to help. I can get one or two started. Happy to gather website requirements and knock that out one of these weekends, for example...

**Comment by llkats** [comment]
@skipzero They're more like ongoing topics to focus upon and discuss, hopefully collaboratively, and maybe even as learning/teaching opportunities for attendees and mentors. Would love to chat more about the site at the event! I have an outline written up with the information I'd like to see included, and definitely want to try to automate some parts of it. I'll try to make a GitHub project for organizing it soon. Thanks!

**Comment by benhalverson** [comment]
@llkats Maybe the [SF Node](https://www.meetup.com/sfnode/) group would be willing to help as mentors.
