### ISSUE TITLE
Website Refresh

### ISSUE THREAD

**Issue by llkats** [nodeschool/sanfrancisco#172]
Refreshing the website! 

Goals
- additional venue/logistical information
- more information about general/focused sessions
- single place to update upcoming event information
- enhancements: email newsletter, PWA push notifications, etc.

See [the Website 2.0 Project](https://github.com/nodeschool/sanfrancisco/projects/1) for details.

**Comment by llkats** [comment]
Here's the amazing wireframe that @samarathgulati and @tlhunter created today. Awesome job, guys!!

![wireframe](https://cloud.githubusercontent.com/assets/578156/22402338/41d35eb6-e5a8-11e6-908f-36f4a299572e.png)

**Comment by tlhunter** [comment]
Here's some example JSON. This would sit in the root of the repo (e.g. `nodeschool.json`) and would be modified over and over by pull requests.

A build process should check validation of this file, perhaps by performing [Joi](https://github.com/hapijs/joi) validation. If the file is ever corrupt the website will break. Travis CI is an excellent choice as it's free. We'd want an npm script for validation.

The nodeschool site allows us to access files from the repository. Here's an example of loading the `package.json` file (so of course we could change **package** to **nodeschool** and get the data file):
https://nodeschool.io/sanfrancisco/package.json

Due to the complexity of this file we should specify different use cases in a `CONTRIBUTING.md` file. Here's some example scenarios:
* Add a photo by putting an image in assets and changing `.photos`
* Add a mentor by putting them in `.mentor` and referencing in `.events[].mentors`
* Add an event by duplicating a similar event and putting entry at end of list
* Note that validation will run against a PR and it may fail

### Example nodeschool.json:

```js
{
  "title": "NodeSchool SF",
  "twitter": "nodeschoolsf",
  "website": "https://nodeschool.io/sanfrancisco/",
  "events": [ // Newest events occur later
    {
      "date": "2017-01-28T05:00:00Z", // ISO 8601
      "title": "NodeSchool Jan 2017",
      "focus": { // can be null if no focus session
        "title": "NodeBots",
        "description": "NodeBots are the best...<br />\nsuch HTML",
        "author": "Alice Bob",
        "author_url": "https://twitter.com/example",
        "image": "http://example.org/event.png" // Can be null, should be square
      },
      "register": {
        "student": "https://ti.to/nodeschoolsf/jan-28th-2017",
        "mentor": "https://github.com/nodeschool/sanfrancisco/issues/167"
      },
      "location": "mozilla", // refers to .locations
      "mentors": [ // refers to .mentors, add after event, default to []
        "tlhunter"
      ],
      "students": 10 // add after event, default to 0
    }
  ],
  "images": [ // Build with script?
    {
      "url": "http://example.org/group-photo-january.jpg",
      "title": "January 2017"
    }
  ],
  "locations": {
    "mozilla": {
      "name": "Mozilla SF",
      "address": "2 Harrison St, SF, CA, 94105", // used to link user agent to map
      "latitude": 37.789620, // optional, default to null
      "longitude": -122.388932, // optional, default to null
      "parking": "<ul><li>Drive down street</li><li>Take a spot</li></ul>"
    }
  },
  "mentors": {
    "tlhunter": { // populate display name and avatar from github profile API or twitter
      "display": "Thomas Hunter II", // GH .name
      "url": "https://github.com/tlhunter", // GH .html_url
      "avatar": "https://avatars.githubusercontent.com/u/551402?v=3" // GH .avatar_url
    }
  }
}
```

**Comment by teone** [comment]
Great job @tlhunter and @llkats.

The Json looks great, just a couple comments:
- what a bout changing `"parking": "<ul><li>Drive down street</li><li>Take a spot</li></ul>"` to an array like `"parking": ["Drive down street", "Take a spot"]`? You can add the markup while iterating on it and you don't have to mix Json and Html
- I have the impression that this file could quickly became huge, so how do you feel splitting it?

Count me in to do some actual work!

Do we want to keep it vanilla js or use some framework?

**Comment by llkats** [comment]
@teone, I've been taking a crack at the first draft of a scaffold based on the wireframe. Once that's pushed, I'd love to get feedback, come to a consensus on the direction forward, and then divide tasks up into individual issues for people to work on. I called dibs on the first pass because I've been dying to do a little modern frontend work lately!

The file definitely has the capacity to become huge, so I think modularizing it will be necessary. We can approach that when we get there.  I also think some of the smaller details, like the parking format, etc. will definitely evolve as we work through the initial stages.

Sorry I didn't make the next steps clear enough, will try to be more open about that in the future. Thanks!!

**Comment by teone** [comment]
@llkats great let me know if I can help!

**Comment by llkats** [comment]
Hi everyone,

I pushed some changes to the branch `new-site`. I just set up basic Handlebars templates and compilation into a static HTML file on the server. Hopefully that's enough for people to get started with.

Following along with the wireframe and sample JSON (the code I committed my diverge slightly, and can/should be edited!), I made initial markup with all of the different sections. I thought that if people wanted to build out a section and then commit that, that'd be a good way to divide up the code. I might be mistaken in that, unsure. To be honest, I've never really coordinated a project like this before, and I'm excited to give it a shot, but I just want to say that I'm open to feedback in all areas of this project. 😅 

In the [website project](https://github.com/nodeschool/sanfrancisco/projects/1), I added a few columns and tasks in each. If you want to volunteer for a task, then add your username to the task that you're working on, and add the the task to the "Done" column when you've pushed your work up to the branch. (If you're unable to edit the tasks to add your username, let me know in this issue and I'll try to figure out how permissions work).

Also, maybe we should be working off of forks and doing PRs to the `new-site` branch? Unsure of how to do review/feedback. (Which I'd love to get on my own contributions btw). Open to suggestions for the process here.

Go to it! 😁  Thanks!

**Comment by llkats** [comment]
Also I guess I should explain the template build step.

1. Pull code
2. `npm install`
3. `node build.js`
4. I didn't really do the server bit because I was using [this chrome extension](https://chrome.google.com/webstore/detail/web-server-for-chrome/ofhbbkphhbklhfoeikjpcbhemlocgigb?hl=en) and didn't really think about it. 😓 

Adding a task for the server thing right meow.

**Comment by skipzero** [comment]
@llkats, I can't click on anything in the Projects tab... I'd imagine that's the place to click? Never dealt with the Projects tab. Heck, I didn't realise there was one till now! ;)

**Comment by llkats** [comment]
@skipzero okay I will look into permissions and how to use the projects tab tomorrow, but now it's time for me to unwind away from my computer for tonight. Sorry for the delay! Will update once I have that sorted out.

**Comment by skipzero** [comment]
No worries. It might be just needing to make an issue for each TODO? Either way, it'll get sorted! I might be a little anxious to get started! :D

**Comment by teone** [comment]
@llkats I came up with a PR (#175) as I got some errors while building templates.
I'm all for PR to contribute as you can then do some code reviews before accepting those.

Do we want to go with a `css` framework (bootstrap, bourbon, inuit, whatever..) or build our own classes? I guess this needs to be decided and eventually defined before starting working all together and find ourself with 300 different classes for the same styling :)

**Comment by skipzero** [comment]
@teone & @llkats I've reviewed the PR. And it's safe and makes sense. 😈 
I'm happy to merge. or at least mark it as reviewed... I'm just not sure our process yet, if there is one even.

**Comment by llkats** [comment]
Okay, I'm going to make all of the tickets into hella issues. Apologies in advance for all y'all's inboxes.

Merged @teone's #175! I'll put the CSS framework decision to be determined in an issue. I'm not religious about anything, though my personal intention for assets would be to keep things as light as possible. For example, if we can do without a big ol' build tool and that sort of setup complexity, that'd be cool. But if/when cases for these tools are made, let's explore them. Does that make sense?

**Comment by skipzero** [comment]
so should we just grab tickets or do you wanna dole them out? i'm happy to start on one and get use to the process. i've forked the repo and will just submit a PR from mine, yes?

**Comment by llkats** [comment]
@skipzero yes, please!

**Comment by llkats** [comment]
Here's a cleaned-up version of the wireframe. Hope it helps as people are building out things! I'll chop up the individual sections and post them in each ticket eventually.

![wireframe-sketch](https://cloud.githubusercontent.com/assets/578156/23336118/e05c8f8e-fb7a-11e6-9b46-bfe19be68274.png)

**Comment by paulgrock** [comment]
This looks great

**Comment by skipzero** [comment]
Thanks Lydia, that'll definitely help a bunch!!

**Comment by jedireza** [comment]
📣 I just noticed Oakland has a new website. It's pretty excellent. https://nodeschool.io/oakland/

**Comment by jedireza** [comment]
I'd like to propose that we fork the Oakland website and re-visit a SF website redesign another time.

**Comment by llkats** [comment]
I forked Oakland's site, and requesting help with that direction in: https://github.com/nodeschool/sanfrancisco/issues/210

Write-up of why this effort stalled out here: https://github.com/nodeschool/sanfrancisco/issues/209
