### ISSUE TITLE
Mentor Registration for February 25th, 2017

### ISSUE THREAD

**Issue by jedireza** [nodeschool/sanfrancisco#173]
Mozilla is hosting us on February 25th from 1pm - 5pm. The address is: 2 Harrison St, San Francisco, CA 94105 -- Comment to get involved or ask questions.

Mentors should:
- Have already completed the [core NodeSchool workshoppers](http://nodeschool.io/#workshopper-list) before the event.
  - _Having also completed elective workshoppers is a great bonus._
- Review the [Mentor Best Practices](https://github.com/nodeschool/organizers/wiki/Event-Mentor-Best-Practices) wiki page.
- Arrive 30 minutes early (12:30p) so we can get setup and have our mentor meeting.

Confirmed mentors:
- [x] @skipzero 
- [x] @Trott 
- [x]  @cachrisman
- [x] @Xabadu
- [x] @JacopoDaeli
- [x] @feross
- [x] @tlhunter 
- [x] @BerkeleyTrue 
- [x] @itsmed
- [x] @samccone
- [x] @samarthgulati
- [x] @Shinobi881 
- [x] @bengl 

Organizers and volunteers:
- [x] @jedireza
- [x] @llkats

Slides:
 - Intros: https://docs.google.com/presentation/d/1rWi5Wqogf6Xs5yyKnwE4eLkOkaFWWK2aQHv7ym2E-aY/edit?usp=sharing
 - Shoutouts: https://docs.google.com/presentation/d/1yeLJfuBH64J_U84wqgPlV0mJ_P8dGDcIq78h6B_W5ac/edit?usp=sharing
 - Shoutout loop: https://docs.google.com/presentation/d/1yeLJfuBH64J_U84wqgPlV0mJ_P8dGDcIq78h6B_W5ac/pub?start=true&loop=true&delayms=10000

**Comment by skipzero** [comment]
me me me me... and this time I'll set my alarm! 😛

**Comment by Trott** [comment]
o/

**Comment by cachrisman** [comment]
count me in!

**Comment by jorgepvenegas** [comment]
Hey guys! I wanna join as a mentor :)

**Comment by jedireza** [comment]
@jorgepvenegas welcome!

**Comment by Xabadu** [comment]
Hey!, I'd like to join :D

**Comment by JacopoDaeli** [comment]
Happy to join as mentor :-) 👍  
http://jacopodaeli.com

**Comment by llkats** [comment]
@Xabadu @JacopoDaeli thanks!!

If it's your first time mentoring with us at NodeSchool SF, it's _especially_ important for you to please arrive at the event half an hour early, at 12:30pm, for mentor orientation. (Also important for return mentors! 😄 )

February also marks our 2nd NodeSchool anniversary! 🎂 🎂 🎂 🎉

**Comment by JacopoDaeli** [comment]
Consider it done @llkats !
Also, thanks for accepting me.

**Comment by tlhunter** [comment]
:arrow_left: :man_teacher:

**Comment by BerkeleyTrue** [comment]
Me!

**Comment by itsmed** [comment]
I'm in!
<img src="https://media.giphy.com/media/xT1XGUM8m88TVfDh5K/giphy.gif" />

**Comment by samccone** [comment]
:hand:

**Comment by samarthgulati** [comment]
Me, too :-)

**Comment by Shinobi881** [comment]
Me too please.

**Comment by BerkeleyTrue** [comment]
@Shinobi881 What up!

**Comment by bengl** [comment]
:hand:

**Comment by jorgepvenegas** [comment]
@jedireza @llkats hey guys, I'll can't make it to the event. I got sick and I'm still recovering :( . I hope I can join you on a next session. Thanks!

**Comment by jedireza** [comment]
@jorgepvenegas thanks for letting us know. See you next time.

**Comment by samccone** [comment]
aw shucks @jedireza @llkats I had some things come up that I need to resolve, see y'all next month!

**Comment by llkats** [comment]
No worries @samccone, see you next time!

**Comment by jedireza** [comment]
Thanks again everyone!
