### ISSUE TITLE
Build out About section markup

### ISSUE THREAD

**Issue by llkats** [nodeschool/sanfrancisco#179]
Create the about section file `partials/_about.hbs` and write up the markup according to the wireframe.

![about](https://cloud.githubusercontent.com/assets/578156/23391870/db795912-fd2c-11e6-9d14-269745811c10.png)

The image gallery will probably be created later on, so a placeholder element indicating where it would be will be fine. I left the Contact portion on because I got lazy, sorry.

This is just a first draft of the content, so placeholder text is acceptable. Please use semantic HTML and your best judgment for markup, but it doesn't have to be perfect! UI styles will follow later, so please use minimal, if any, CSS.

**Comment by benhalverson** [comment]
Hi @llkats 
I have started to work on the about section. I don't see anyone else assigned to it.

**Comment by llkats** [comment]
@benhalverson awesome, thanks! I will invite you to the repo and assign the issue to you once you accept.

Just for general knowledge, I'll be unable to review/merge contributions until after May 7th. Please ping another contributor if you need a hand before then. Thanks again!

**Comment by benhalverson** [comment]
@llkats @skipzero What should the image gallery look like? Is it a slider gallery or something else?

**Comment by benhalverson** [comment]
@llkats  The circles next to the Contact us text and About. What image should I use?

**Comment by llkats** [comment]
@benhalverson hi!

The image gallery has not been fleshed out at all - you can skip it for v1. Maybe leave a placeholder element for where it can be developed later.

For the circles, I don't think we have any new assets yet, so anything out of the assets folder, or just an element with a background color, or placekitten.com, whatever you want.

Let me know if you have more questions!
