### ISSUE TITLE
NodeSummit Day 0: Call for mentors

### ISSUE THREAD

**Issue by CrabDude** [nodeschool/sanfrancisco#18]
I'm organizing NodeSummit's Day 0 NodeSchool event, Monday, February 9 @ 9a-12. The room fits 100 and I'm hoping for 10+ mentors. We currently have the 4 BayNode organizers committed (myself + @generalhenry @rosskukulinski @tonypujals ). Hoping @mikeal @substack @maxogden et. al. will join.

We're planning 2-3 tracks with 3 sessions and 1 workshop per session.

Currently schedule:
9:00-9:30 - Node primer
9:30-10:20 - Session 1
10:20-11:10 - Session 2
11:10-12:00 - Session 3

Track "Beginner": javascripting + count-to-6, learnyounode, promise-it-wont-hurt or async-you
Track "Advanced": functional-javascript-workshop, expressworks or makemehapi or kick-off-koa, stream-adventure
Track "Non-web": (I'm unfamilliar with these) bug-clinic, bytewiser, goingnative

Further, we can group tracks near each other, pair people up, have a local npm mirror, have a runnable for each of the workshops, etc...

**Comment by CharlesBeeler** [comment]
Everyone who signs up to be a mentor (and shows up) gets a free pass to Node Summit 2015 and a custom t-shirt that will only be given to the Day Zero speakers and volunteers.

**Comment by CrabDude** [comment]
@ceejbot

**Comment by RichardLitt** [comment]
I'd be happy to help. Not sure how proficient I am in Node, but I could help with the beginner segment for sure.

**Comment by CrabDude** [comment]
@RichardLitt We're going to have similar tracks group together, so if you feel confident helping with the "Beginner" track (javascripting, count-to-6, learnyounode, async-you, promise-it-wont-hurt), then we'd be happy to have you! =)

**Comment by RichardLitt** [comment]
I'm happy to help with that. I'll brush up on those before then. :palm_tree:

**Comment by rosskukulinski** [comment]
:+1: @RichardLitt

**Comment by oelamri** [comment]
I'm in for advanced! :8ball:

**Comment by CrabDude** [comment]
@oelamri Awesome. Thanks for helping out!

**Comment by mikeal** [comment]
I'll be there :)

**Comment by jedireza** [comment]
I'm in.

**Comment by tonypujals** [comment]
Awesome!

**Comment by tonypujals** [comment]
Nice!

**Comment by CrabDude** [comment]
@mikeal Awesome. Thanks for joining!

**Comment by chapel** [comment]
@tonypujals and @CrabDude contacted me directly through email about this, but wanted to say here that I am coming as well.

**Comment by lucamaraschi** [comment]
I'm in for mentoring!

**Comment by Trott** [comment]
In for mentoring if there's still a need.

**Comment by pvenkatakrishnan** [comment]
In for mentoring for the beginner session

**Comment by tonypujals** [comment]
For all those offering to help mentor, that's awesome. The help is
appreciated (plus it gets you a ticket)!

Tony

**Comment by CrabDude** [comment]
Discussion moved to https://gitter.im/nodeschool/nodesummit2015 to better facilitate planning conversation.

**Comment by tonypujals** [comment]
Am I the only one who feels that a major disservice is being done to those
expending effort into Day 0 workshops?


   - http://nodesummit.com/

Node Summit, a two-day conference at the Mission Bay Conference Center in
San Francisco - February 10-11, 2015


   - http://nodesummit.com/agenda/

Agenda

   - *Day One* <http://nodesummit.com/agenda/#day-one>
   - *Day Two <http://nodesummit.com/agenda/#day-two>*


Having a single link to "Day 0" on the site menu doesn't really make it
clear to quite a few people I've shared the http://nodesummit.com link with!

They could do a lot better with the message.

Tony

**Comment by CharlesBeeler** [comment]
Hopefully yes.  We've planned it this way from the start since we can only accommodate 100 ppl per track (two tracks already full).

Share the Day Zero link if you are trying to promote that part of the event.

**Comment by tonypujals** [comment]
I've seen conferences that included a Day Zero on the agenda page; e.g., Day 0 | Day 1 | Day 2, etc., and I think it would have been great to see NodeSummit do the same.

Just a quick random sample from Google across a few industries:

 * http://tbmconference.org/agenda/
 * http://www.osisoft.com/UsersConference2011/Agenda/
 * http://www.questexevent.com/IHIF/2015th/conference-day-0/

While we can share links to promote Day Zero, event promotion is one of the things ideally done most effectively by the conference site itself. 

I don't mean for my criticism to come across so harsh, however. I think this NodeSummit's going to be a great conference, I appreciate that it takes an **enormous** amount of planning, effort, and coordination to make it successful, and I'm looking forward to participating and hopefully contributing a small bit of value to it myself on Day Zero.
