### ISSUE TITLE
Make sure the development web server works.

### ISSUE THREAD

**Issue by llkats** [nodeschool/sanfrancisco#183]

**Comment by skipzero** [comment]
So I've nothing to commit, but I've forked, updated and went through the steps in the README.md. I did `npm install`, then `npm start`, navigated to `localhost:8080` and I have the website up and running locally!
:)

**Comment by skipzero** [comment]
is there a way to take or assign issues? or maybe I don't have the correct permissions...

**Comment by teone** [comment]
Is possible to assign issues but I believe you need to have write permissions to the repo in order to do that

**Comment by llkats** [comment]
I tried to outline in the contributing document that if you aren't a collaborator yet, then leave a comment in the issue you'd like to volunteer for, and I'll add you as a collaborator to this repo and assign the issue to you. I think once you're a collaborator, you can self-assign a ticket or assign to others.

Thanks for checking out the functionality, @skipzero. I think this part might evolve with the build process, but for now I'll call it good.

**Comment by skipzero** [comment]
Yeah, I'm sorry. I wasn't really putting it all together last night when I read this... 😊 
well, I'll happily follow through with the evolution of the script. Funny thing, I'm working on the build tools at work today... 😳

**Comment by skipzero** [comment]
Just retested this now that we've browserSync and gulp in. Server works and serves page! I notice a css file in the src/assets dir but it's not being moved nor seems linked to the handlebar template. 

But, it works and we're ready for dev work! 😄 

(just my due diligence since I sorta jumped the gun last week!)
