### ISSUE TITLE
Create a watcher to auto-compile changes to the templates

### ISSUE THREAD

**Issue by llkats** [nodeschool/sanfrancisco#184]

**Comment by teone** [comment]
Why not to use a build tool here instead writing our own? If this want to be an exploration exercise I'm also for it, otherwise we can just throw in `gulp` and I guess we can find plugins that will suit our needs

**Comment by llkats** [comment]
If you're keen on a build system, go for it. I don't tend to use them in my own development most of the time lately, so I look forward to reviewing your PR. I just want to stress simplicity for the ease of contribution from others.

**Comment by teone** [comment]
I can come up with a PR in the next days, then will see how it looks :)

**Comment by llkats** [comment]
Thanks @teone!!
