### ISSUE TITLE
Build out the JSON data file with actual data for use in the templates.

### ISSUE THREAD

**Issue by llkats** [nodeschool/sanfrancisco#185]

**Comment by skipzero** [comment]
is the info for this on the pics taken from last month's nodeSchool? Perhaps I should just wait till Saturday to go over things in person before starting to dig in?

**Comment by samarthgulati** [comment]
Hi all, I messed up my [last commit](https://github.com/nodeschool/sanfrancisco/commit/7978bda80e05ba3067de0e31c10e5c9b0bfe93c4) a bit :( , and committed my changes directly to the new-site branch. I have explained the changes I made in the commit message.
Will make sure to fork and send pull request from next time on. 
Sorry for the inconvenience.

**Comment by llkats** [comment]
@samarthgulati to help prevent this in the future, I added a protected status to the `new-site` branch, so all commits should have to go through the PR process or else will be rejected from direct pushing. Would you mind adding a January event and perhaps the March event so we have some past data and future data? The descriptions for the focused events can be very general text or just placeholder text for now.

Do we see this JSON file as including historical data? Could be a little tedious to add, though might be a nice way to help people make PRs who've never made them before.
