### ISSUE TITLE
Food Sponsor for February Event

### ISSUE THREAD

**Issue by llkats** [nodeschool/sanfrancisco#187]
Hi everyone,

We are looking for a group/organization/company to sponsor food for this month's event. Please get in touch with us at nodeschoolsf@gmail.com if you or someone you know would like to sponsor. Your org will get shoutouts at the beginning and end of the event, and we can talk about other ways to thank your org for their generosity as well.

Thanks! 🍕  🌮  🌯  🎂

**Comment by tlhunter** [comment]
How much money are we looking for?

**Comment by llkats** [comment]
Thank you @tlhunter and OpenTable!!!
