### ISSUE TITLE
Venue for March 25th

### ISSUE THREAD

**Issue by jedireza** [nodeschool/sanfrancisco#193]
We're looking for a venue for our March 25th event. All help is very much appreciated. 🙏

**Comment by jedireza** [comment]
@groundwater we once talked about the possibility of using the GitHub space.

@MylesBorins we once talked about the possibility of using an IBM location (Bluemix Garage?).

**Comment by BerkeleyTrue** [comment]
@jedireza What about Microsoft Reactor?

**Comment by jedireza** [comment]
Yes please. At this point we need anything we can get. 🙏 ❤️

**Comment by skipzero** [comment]
What's the minimum capacity? would there need to be a dedicated separate area for the breakout track?

**Comment by BerkeleyTrue** [comment]
@jedireza Which email of yours can I use for this?

**Comment by BerkeleyTrue** [comment]
@jedireza email sent

**Comment by llkats** [comment]
As tweeted earlier, we're going to plan for April's event instead. We're in touch with @BerkeleyTrue's contact, but other leads for venues will be very much appreciated!
