### ISSUE TITLE
question

### ISSUE THREAD

**Issue by decareano** [nodeschool/sanfrancisco#197]
Hi reza, is this the proper github repo to send PR's if, say, I have a question on a project I am working on?. I am not clear on it. Also, I dont know what can I do but I am willing to help to find a new place.

**Comment by Trott** [comment]
> ...if, say, I have a question on a project I am working on?.

There is an official Node.js repo for general help with Node.js questions that might be more in line with what you're looking for. It is https://github.com/nodejs/help. If you are having trouble with a NodeSchool workshopper, it's generally OK to open an issue in a chapter's repo (like this one). But for more general Node.js stuff, you may be better off with the nodejs/help repo. instead.

(Of course, if @jedireza or @llkats says anything that contradicts anything that I've written above, listen to them and ignore me.)

**Comment by jedireza** [comment]
> I have a question on a project I am working on?

Is the project public? Does it have it's own GitHub repo? If it isn't public, it'll be more difficult for other to help you debug and/or reproduce the error/bug you're dealing with.

**Comment by decareano** [comment]
Yes, it's public. I am posting it here. It's a project I work on NodeSchool Oakland and SF. https://github.com/decareano/node-sequelize-postgresql/blob/passport_WIP. The error is in app.js Line 16. I am using the wrong model or the model is not properly setup in the app. I was following Jared Hanson Passport document. I would be glad to move it to what Rich suggested if this is the wrong forum.

**Comment by tlhunter** [comment]
Oh, I received your email, haven't had a chance to look into it yet.

**Comment by jedireza** [comment]
Since you have a repo setup for the project let's move the discussion there, I opened a new issue on your repo.
