### ISSUE TITLE
Venue for April

### ISSUE THREAD

**Issue by llkats** [nodeschool/sanfrancisco#198]
Picking up from #193, this is a planning issue to find a venue for April's event. The date can be flexible except for avoiding overlap with NodeSchool Oakland's event. All leads on venues are appreciated! :bowing_woman: 🙏

**Comment by nebrius** [comment]
As part of my first day in MS developer evangelism, I checked, and (assuming I'm remembering the calendar correctly) Microsoft's Reactor space is available on Saturday April 29th. Does that date work for you? Let me know and I can reserve it.

**Comment by llkats** [comment]
I am (personally, selfishly) partial to the 22nd because I will be out of the country on the 29th. But the 29th also works!!

**Comment by nebrius** [comment]
Unfortunately the reactor space is already booked on the 22nd :-/

**Comment by llkats** [comment]
Aw, shucks! 29th is great, thank you and congrats, @nebrius!! 🎉🎉🎉🎉

**Comment by nebrius** [comment]
The Reactor space is reserved! http://microsoftreactor.com/event/nodeschool-sf-april-2017/

**Comment by jedireza** [comment]
Yay thanks @nebrius!! Are you our main point of contact and host that day? If not, who is? Can I swing by the space and get a feel for it and what we may need to plan for (I'm back in town April 3rd)? Is food sponsorship included?

**Comment by nebrius** [comment]
> Are you our main point of contact and host that day?

Yep!

> Can I swing by the space and get a feel for it and what we may need to plan for (I'm back in town April 3rd)?

Yeah, I'm in the space most work days, so ping me whenever is convenient for you.

> Is food sponsorship included?

I can get pizza for the event, want me to confirm and lock it in?

**Comment by jedireza** [comment]
> I can get pizza for the event, want me to confirm and lock it in?

Yes please 🙏

**Comment by llkats** [comment]
Mentor registration is open! #200 

With the venue ironed out (A MILLION THANK YOUS, @nebrius!!!!), I'll close this issue.

**Comment by nebrius** [comment]
Following up: pizza is confirmed!

**Comment by nebrius** [comment]
> Can I swing by the space and get a feel for it and what we may need to plan for (I'm back in town April 3rd)?

@jedireza I'm going to be in Chicago from April 24th through April 27th, so if Friday April 28th doesn't work, can you stop by this week?

**Comment by jedireza** [comment]
@nebrius great timing I was just going to ping you. This week works, I'll DM.
