### ISSUE TITLE
Mentor Registration for April 29th, 2017

### ISSUE THREAD

**Issue by llkats** [nodeschool/sanfrancisco#200]
Microsoft is hosting us on April 29th from 1pm - 5pm. The address is: 680 Folsom Street, Suite 145 San Francisco, CA 94107 -- Comment to get involved or ask questions.

Mentors should:
- Have already completed the [core NodeSchool workshoppers](http://nodeschool.io/#workshopper-list) before the event.
  - _Having also completed elective workshoppers is a great bonus._
- Review the [Mentor Best Practices](https://github.com/nodeschool/organizers/wiki/Event-Mentor-Best-Practices) wiki page.
- Arrive 30 minutes early (12:30p) so we can get setup and have our mentor meeting.

Confirmed mentors:
- [x] @skipzero 
- [x] @cantremember 
- [x] @Xabadu 
- [x] @upekabee 
- [x] @Zahidul-Islam 
- [x] @itsmed 
- [x] @amazingandyyy
- [x] @samarthgulati

Organizers and volunteers:
- [x] @jedireza
- [ ] @llkats

Slides:
 - Intros: https://docs.google.com/presentation/d/1ENluPX6f_KFa_2075lMu-m2gMIushszzrEqHdFFn5Ao/edit?usp=sharing

**Comment by llkats** [comment]
I hit "submit" too early 😓

**Comment by Trott** [comment]
o/

**Comment by skipzero** [comment]
me. I'm thinking I need to get out the house more! ;)

**Comment by cantremember** [comment]
me me! *oh, me!* i can do it! **me!**

**Comment by Xabadu** [comment]
Hey, I'm in 🤘

**Comment by upekabee** [comment]
I'd like to help too! :)

**Comment by Zahidul-Islam** [comment]
I would like to help!

**Comment by itsmed** [comment]
Sorry I missed last month, but I'll be there this time!

**Comment by amazingandyyy** [comment]
I just helped out #Nodeschool-oakland last week.
It's really fun.

I am willing to help Nodeschool SF. 🥇

**Comment by samarthgulati** [comment]
Hey, I am in as well!

**Comment by jedireza** [comment]
thanks @samarthgulati

**Comment by jedireza** [comment]
Ok folks tomorrow is the day! 🎉

It feels like forever since we skipped last month. Please remember to arrive @ 12:30p so we can have our mentor meeting. Also remember we're in a new location, the Microsoft Reactor space (which is pretty dang awesome).

There are still tickets available. Please  spread the word to your network: 

 - https://ti.to/nodeschoolsf/april-29th-2017
 - https://twitter.com/nodeschoolsf/status/849034174572908544
 - https://twitter.com/nodeschoolsf/status/855194047664738304

See you tomorrow!

**Comment by skipzero** [comment]
And just cause I forgot where it was, I'll leave this here for others who have issues remembering stuffs and things!

MS Reactor Space
680 Folsom St #145, San Francisco, CA 94107

**Comment by Trott** [comment]
Woke up with a sore threat and congestion, so I'm not going to make it today. Sorry to miss it.

**Comment by jedireza** [comment]
Oh darn. Feel better @Trott 🤒

**Comment by nebrius** [comment]
Hey mentors! I wanted to give a few quick notes about the venue today:

1. Microsoft's office is on the first floor of the build, with the door to our office directly inside the lobby.
1. We won't have building security today, which means that the front door will be _locked_. It can, of course, be opened from the inside, and my badge opens it from the outside.
  1. This means that we will need some mentors to stay by the door to let folks in
  1. We can rotate mentors in and out so you're not gone too long from the hacking, and many thanks for anyone who helps!
1. I will be at the office by 12. If I'm not around to let you in at the front door, please DM me on [Twitter](twitter.com/nebrius) and I'll come let you in (my DM's are open).

@jedireza I just had the thought: we should probably let attendees know that there's a chance the door will be locked and if there's no one at the front to door to DM one of us.

**Comment by jedireza** [comment]
For anyone reading... the door isn't locked.

**Comment by cantremember** [comment]
sooo -- not at Mozilla today.  guess i'll be taking a walk ...

**Comment by jedireza** [comment]
❤️ Thank you mentors for volunteering your time and creating another great event. And a special thanks @nebrius for hosting us. I hope we can use this space again after the 🚧.
