### ISSUE TITLE
Venue for May

### ISSUE THREAD

**Issue by jedireza** [nodeschool/sanfrancisco#202]
Let's stay on the ball and get the discussion for May started. Let's shoot for Saturday May 27th and see where it takes us. 🎓

**Comment by nebrius** [comment]
FYI I just confirmed that our other office space has a capacity of about 80 people, so that space should work while the reactor space is closed for construction (assuming the calendar is open of course).

**Comment by jedireza** [comment]
Thanks @nebrius! I have an email thread in flight to host NodeSchool SF @ Google SF in May. I'll try to get that confirmed ASAP. Otherwise we'd definitely love to use the Microsoft location.

**Comment by Anasauce** [comment]
I'm new to Node School, is there an email list? Or a way I can get updates on upcoming events?

**Comment by Anasauce** [comment]
I'm down to help organize if needed

**Comment by skipzero** [comment]
Welcome, @Anasauce!

If you watch the repo, you'll get notified when someone posts here. We will announce the dates and locations here. There'll be a call for volunteers, usually, at that time as well.

Thanks!

**Comment by jedireza** [comment]
We got confirmation that we can use Google's Launchpad space. I'll do my best to collect the details and get mentor registration and ticket setup ASAP.
