### ISSUE TITLE
Venue for June

### ISSUE THREAD

**Issue by jedireza** [nodeschool/sanfrancisco#203]
Let's stay on the ball and get the discussion for June started. Let's shoot for Saturday June 24th and see where it takes us. 🎓

**Comment by skipzero** [comment]
Are we having a May nodeschool?

**Comment by jedireza** [comment]
> Are we having a May nodeschool?

Yep. See https://github.com/nodeschool/sanfrancisco/issues/202#issuecomment-300279652

**Comment by skipzero** [comment]
Ah. I looked around and couldn't find it. ;p

**Comment by jedireza** [comment]
👊 bump 👊

**Comment by nebrius** [comment]
I'll check and see what availability is like at some of the other MS offices around SF, stay tuned!

**Comment by llkats** [comment]
@MylesBorins if you're in town, mayhaps you could open a Google space for us? 😀 😀 😀

**Comment by MylesBorins** [comment]
@llkats I'll check tomorrow

**Comment by nebrius** [comment]
Following up, the MS SF venues are booked on the 24th :(

**Comment by llkats** [comment]
Wuh oh. @MylesBorins any updates? We really need to figure out this month's venue soon!

**Comment by MylesBorins** [comment]
I checked and launch pad wasn't available :(

**Comment by llkats** [comment]
It's not seeming like it's in the cards to have NodeSchool SF in June. We tried talking to another venue which also fell through today, and it's getting late in the month. Additionally, the 24th is Pride, and I'd rather people didn't have to choose between Pride events or NodeSchool.

I propose trying to schedule an event on Saturday, July 8th. My primary concern with that is encroaching on NodeSchool Oakland's schedule. @Fauntleroy, do you have any qualms with that plan?

**Comment by Fauntleroy** [comment]
Our next event will be on July 15th, the weekend after July 8th. I don't have a problem with it, but would you also be having an event later in the month?

**Comment by llkats** [comment]
This would count as our community event for July, and we'll have our next
open event in August. @jedireza, what do you think about that plan? People
will be back in town again after the 4th too.

**Comment by jedireza** [comment]
I'm good with that.
