### ISSUE TITLE
Mentor Registration for May 27th, 2017

### ISSUE THREAD

**Issue by jedireza** [nodeschool/sanfrancisco#204]
dGoogle Launchpad is hosting us on May 27th from 1pm - 5pm. The address is: 301 Howard Street, 4th Floor, San Francisco, CA 94105 -- Comment to get involved or ask questions.

Mentors should:
- Have already completed the [core NodeSchool workshoppers](http://nodeschool.io/#workshopper-list) before the event.
  - _Having also completed elective workshoppers is a great bonus._
- Review the [Mentor Best Practices](https://github.com/nodeschool/organizers/wiki/Event-Mentor-Best-Practices) wiki page.
- Arrive 30 minutes early (12:30p) so we can get setup and have our mentor meeting.

Confirmed mentors:
- [x] @Trott 
- [x] @Shinobi881 
- [x] @nebrius
- [x] @sotayamashita 
- [x] @paulgrock 
- [x] @tlhunter 
- [x] @Xabadu 
- [x] @ultrasounder
- [x] @samarthgulati 
- [ ] you?

Organizers and volunteers:
- [x] @llkats
- [ ] @jedireza

Attendee registration link:
 - https://ti.to/nodeschoolsf/may-27th-2017

Slides:
 - Intros: TBD
 - Shoutouts: TBD
 - Shoutout loop: TBD

**Comment by llkats** [comment]
First! 😀

**Comment by jedireza** [comment]
📟 @upekabee @LindsayElia @Anasauce @Shinobi881 @BerkeleyTrue @bengl @jennabelle @btamayo @paulgrock @iredelmeier @prattsj @negomi

**Comment by BerkeleyTrue** [comment]
Sorry y'all, I'll have family staying with me for Carnaval. and also, Carnaval!!!

**Comment by skipzero** [comment]
Not gonna make this one. I was afraid it was that weekend. see you in June!

**Comment by Trott** [comment]
o/

**Comment by Shinobi881** [comment]
I'm in

**Comment by nebrius** [comment]
me. Also, would we be interested in a NodeBots focused session if the location has space for it?

**Comment by jedireza** [comment]
> Also, would we be interested in a NodeBots focused session if the location has space for it?

Nice! I'll try to do some recon soon and let you know.

**Comment by sotayamashita** [comment]
Hi, I am a member of Nodeschool Tokyo and I will be there. Can I join as a mentor?

**Comment by llkats** [comment]
@sotayamashita hi Sota! We'd be delighted to have you. Please do review our [Mentor Best Practices](https://github.com/nodeschool/organizers/wiki/Event-Mentor-Best-Practices) and we'll see you on the 27th!

**Comment by sotayamashita** [comment]
@llkats Thanks. I am looking forward to seeing you on the 27th.

**Comment by jedireza** [comment]
🤜 bump 🤛

**Comment by paulgrock** [comment]
In!

**Comment by tlhunter** [comment]
I'm in

**Comment by Xabadu** [comment]
I'm in! 🤘

**Comment by ultrasounder** [comment]
I am All In!📚👩‍💻coming from a bit of Python and learning to wrangle the Anaconda that JS is!

**Comment by samarthgulati** [comment]
me too!

**Comment by MylesBorins** [comment]
I MISS YOU ALL

**Comment by iredelmeier** [comment]
I can't make it tomorrow but maybe next time!

**Comment by llkats** [comment]
@iredelmeier no worries! Hopefully see you soon another time!

**Comment by Shinobi881** [comment]
Sorry ya'll. Got the on-call, call. Not gonna make it.

**Comment by llkats** [comment]
Thanks for a great event everyone! See y'all next time!
