### ISSUE TITLE
Venue for July

### ISSUE THREAD

**Issue by jedireza** [nodeschool/sanfrancisco#206]
Let's talk dates and then start looking for locations. 👨‍💻 👩‍💻

**Comment by llkats** [comment]
I think the ideal date will be July 8th. It'll be just after July 4th and won't conflict or be too close to NodeSchool Oak or other events happening later that month.

**Comment by llkats** [comment]
@nebrius might the Microsoft space be open?
@justinbeckwith 👋  hey there, is there a chance Google Launchpad could host us on July 8th?

**Comment by nebrius** [comment]
@llkats I just submitted a request, and should find out sometime in the next 24 hours.

**Comment by thesandlord** [comment]
We can probably do this in the Google Launchpad if the Microsoft space falls through. @nebrius I'll wait for your response.

**Comment by llkats** [comment]
@nebrius @thesandlord thank you both!!

**Comment by thesandlord** [comment]
@nebrius any updates?

**Comment by nebrius** [comment]
@thesandlord not yet, I just sent another email asking for a status update.

**Comment by llkats** [comment]
@nebrius any answer on this? I'm just afraid of getting turned down and losing our chance with Launchpad too. If @thesandlord can schedule for July, maybe we can work on scheduling Reactor for August? Let us know, thanks!

**Comment by nebrius** [comment]
@llkats I heard earlier tonight that the space has been booked! I'm still waiting for detailed and official confirmation which should come sometime tomorrow (today?), and I'll let you know any additional details I find out, but we for certain have the space on July 8th

**Comment by llkats** [comment]
@nebrius wonderful, thank you!! 🙏  💯  🎉

**Comment by nebrius** [comment]
Following up with a few details. This space is a different location than the previous MS office we hosted at (that one is still under construction).

- Address is 555 California St, Suite 200, San Francisco, CA
- We need to provide a list of attendees (and mentors) 48 hours in advance for building security
- We have a conference room booked that can hold up to 42 people in classroom configuration, or 72 people in a theatre configuration (I assume this means no tables, but I'm working on getting clarification). I get the impression there's a room next door that is connected to this one and can be opened up. Do we think 42 is enough, or should I investigate getting the room next door booked too?

**Comment by llkats** [comment]
I think classroom configuration would be most ideal for the event. I don't think we've had more than 40 people for a few events now, but it'd be nice to have a backup just in case there's overflow, if it's not too much trouble. Will Microsoft be sponsoring food as well, or should we plan separately to have pizza or something?

Thanks @nebrius!!!

**Comment by nebrius** [comment]
@llkats we can provide food! I'll investigate getting the room next door booked too and let you know once I learn more.

**Comment by nebrius** [comment]
The room next door has been booked too, and the partitioning wall will be open. We now have space for up to 84 people! If nothing else, this will give us room to expand and not have to be so close to each other.

**Comment by llkats** [comment]
@nebrius super rad, thanks!! 👍
