### ISSUE TITLE
Venue for August

### ISSUE THREAD

**Issue by jedireza** [nodeschool/sanfrancisco#207]
Let's talk dates and then start looking for locations. 👨‍💻 👩‍💻

**Comment by llkats** [comment]
We should try to go back to the regular last Saturday cadence, which will be the 26th of August.

**Comment by paulgrock** [comment]
@jedireza @llkats would you like me to ask about potential hosts for upcoming events at SFNode? I can add it to our slides or something.

**Comment by jedireza** [comment]
That would be rad! Thanks @paulgrock.

**Comment by llkats** [comment]
Just wanted to loop @thesandlord in about @MylesBorins having submitted a request for a Google space (Launchpad, I think?) for August 26th. We'd love to have your involvement if you're up for August!

**Comment by jedireza** [comment]
📟 @thesandlord @MylesBorins @llkats

**Comment by llkats** [comment]
Forgot to pass this along, but @MylesBorins confirmed Google for us back in June in DMs on Twitter.
![image](https://user-images.githubusercontent.com/578156/28762594-aef31686-756c-11e7-9624-4d41ff87618a.png)

**Comment by MylesBorins** [comment]
Yeah sorry I totally spaced on this. Space is reserved. We just need to confirm googlers who will be around to help y'all out on the day

**Comment by skipzero** [comment]
Am I just not seeing a signup list for august? or has it not started yet? And I'm guessing I missed july! ;p

**Comment by jedireza** [comment]
That's fantastic. I've opened registration so please let me know if the address is different or any other details need to be updated.

 - https://ti.to/nodeschoolsf/august-26th-2017
 - https://github.com/nodeschool/sanfrancisco/issues/220

**Comment by Shinobi881** [comment]
@tlhunter @Xabadu, @rykuehn is at Capital One and they are interested in hosting/sponsoring a Nodeschool event.

**Comment by Xabadu** [comment]
Thank you for letting us know @Shinobi881! I'll reach out :D
