### ISSUE TITLE
NodeSchool at Node Summit (July 25th, 2017)

### ISSUE THREAD

**Issue by llkats** [nodeschool/sanfrancisco#208]
[Node Summit](http://nodesummit.com/) is a three-day conference in San Francisco. It will be on July 25th-27th 2016 at [Mission Bay Conference Center](http://nodesummit.com/venue/). 

🎉 NodeSchool SF has been invited to host a NodeSchool on [Day Zero](http://nodesummit.com/day-zero/) (July 25th) of the Node Summit conference from 12:00pm - 5:00pm. 🎊 

Since this is a special event, we do ask that you've mentored at a NodeSchool before and that you're excited to engage with attendees. We're accepting up to 10 mentors for this event. Mentors will get a ticket to Node Summit for volunteering. Comment to get involved or ask questions.

Mentors should:
- Have mentored at a NodeSchool before.
- Have already completed the [core NodeSchool workshoppers](http://nodeschool.io/#workshopper-list) before the event.
  - _Having also completed elective workshoppers is a great bonus._
- Review the [Mentor Best Practices](https://github.com/nodeschool/organizers/wiki/Event-Mentor-Best-Practices) wiki page.
- Arrive 30 minutes early so we can get setup and have our mentor meeting.

Confirmed mentors:
- [x] @upekabee
- [x] @Shinobi881 
- [x] @Trott 
- [x] @Fauntleroy 
- [x] @Xabadu  
- [x] @paulgrock  
- [x] @BerkeleyTrue
- [x] @MylesBorins
- [x] @arayi
- [x] @Zahidul-Islam

Organizers and volunteers:
- [x] @jedireza
- [x] @llkats

**Comment by Xabadu** [comment]
Hey @llkats, I'll be attending the event, so I'd like to help mentoring if that's alright. (No ticket needed for me).

**Comment by paulgrock** [comment]
I'd love to help.

**Comment by llkats** [comment]
Sounds good, @Xabadu! You can just show up and we'll be happy to have you.

Welcome aboard, Paul! 😁

**Comment by BerkeleyTrue** [comment]
I'll be there!

**Comment by jedireza** [comment]
We'd like to fill these last 4 spots, and hopefully by Friday the 23rd. If our friends (you) could help spread the word we'd be very grateful. 🙏

The best part is that mentors at this event get a free pass to the whole NodeSummit event.

**Comment by upekabee** [comment]
@negomi ? :)

**Comment by Fauntleroy** [comment]
@kemitchell @itsmed I'm not sure if you've been contacted already, but would you be interested in helping out?

**Comment by itsmed** [comment]
Sorry all, I can't get off work :(

**Comment by negomi** [comment]
Aww I would love to, but I will be in Europe then, unfortunately :(

**Comment by MylesBorins** [comment]
o/

**Comment by arayi** [comment]
can help? 🥓🌈😊

**Comment by jedireza** [comment]
Thanks @arayi 🎉

**Comment by llkats** [comment]
Hi everyone! Thanks for volunteering, we're so excited for your help at Node Summit. If you haven't yet received registration instructions, please look out for an onboarding email from Node Summit organizers soon!

@arayi would you please send me an email address that would be good to contact you at ASAP? You can email it to me at llkats at gmail dot com or DM me on Twitter at @llkats, my DMs are open. Thanks!

**Comment by Zahidul-Islam** [comment]
I'd be happy to help.

**Comment by jedireza** [comment]
Great! Just in the nick of time @Zahidul-Islam 🎉

**Comment by jedireza** [comment]
@Zahidul-Islam please DM [@llkats on Twitter](https://twitter.com/llkats) with an email address that would be good to contact you at ASAP.

**Comment by llkats** [comment]
I sent along the one on @Zahidul-Islam's profile page, hope that was okay!

That's all the volunteers we need! Yay!

**Comment by jedireza** [comment]
Many thanks to everyone for making this happen. 👍 :shipit:
