### ISSUE TITLE
Website Refactor

### ISSUE THREAD

**Issue by llkats** [nodeschool/sanfrancisco#210]
A new issue for the website refactor. [Read why we're taking this new direction](https://github.com/nodeschool/sanfrancisco/issues/209).

Please check out the branch `forked-refactor` from this repo for the latest branch to work off of. See `package.json` for scripts to run, but the important ones are:

- `npm run docs:build` - build all of the files once
- `npm run docs:dev` - serve the site at `http://localhost:8080` and automatically compile Styles/Mustache on save (does not auto-reload in browsers)

TODOs:
1. a background image of some sort for the header, perhaps in the vein of [NodeSchool Oakland's](https://nodeschool.io/oakland/).
1. a refined color palette and the ability to add more sections that are separated by background colors. I'd like the section on Focused Sessions to stand out in particular. I picked colors straight from the logo as inspiration, but we could maybe use some more for different sections throughout the page?
1. probably some better fonts than the ones I picked out initially
1. any other design finessing that people think would make good additions

Please propose tweaks or submit a PR against `master` and drop a note here.

**Comment by jedireza** [comment]
👍 Let's ship it and fix this other things with other issues/PRs. :shipit:

I'm thinking it'll be better to work off of the master branch as the source of truth.

**Comment by llkats** [comment]
Sounds good. I think I'm going to hold off at least until we have details on the venue figured out for the next event so we can launch with real data there.

**Comment by llkats** [comment]
It's live! I also have changed the default branch from `gh-pages` to `master`, sorry if that messes anything up for anyone. Please make PRs against `master`.

**Comment by jedireza** [comment]
Oh, by master I meant one upstream branch. We can probably go back to `gh-pages` being the default. How is `gh-pages` being generated now?

**Comment by llkats** [comment]
GitHub Pages is pulling from the index.html inside of `master/docs/`, which is something you can configure in Settings.

**Comment by jedireza** [comment]
Ah, nice. I'd call this issue done. How about creating new issues for anything else?

**Comment by llkats** [comment]
Let's leave this one open until I get some more time to work on it.
