### ISSUE TITLE
Mentor Registration for July 8th, 2017

### ISSUE THREAD

**Issue by llkats** [nodeschool/sanfrancisco#211]
Microsoft is hosting us on July 8th from 1pm - 5pm. The address is:555 California St, Suite 200, SF, CA 94104 -- Comment to get involved or ask questions.

Mentors should:
- Have already completed the [core NodeSchool workshoppers](http://nodeschool.io/#workshopper-list) before the event.
  - _Having also completed elective workshoppers is a great bonus._
- Review the [Mentor Best Practices](https://github.com/nodeschool/organizers/wiki/Event-Mentor-Best-Practices) wiki page.
- Arrive 30 minutes early (12:30p) so we can get setup and have our mentor meeting.

Confirmed mentors:
- [x] @Trott 
- [x] @Xabadu 
- [x] @skipzero 
- [x] @JasonEtco
- [x] @EBiddlecome
- [x] @Zahidul-Islam
- [x] @samarthgulati
- [x] @paulgrock
- [ ] you?
- [ ] you?

Organizers and volunteers:
- [x] @llkats
- [x] @jedireza

Attendee registration link:
 - https://ti.to/nodeschoolsf/july-8th-2017

Slides:
 - Intros: TBD
 - Shoutouts: TBD
 - Shoutout loop: TBD

**Comment by Trott** [comment]
o/

**Comment by Xabadu** [comment]
I'm in 🤘

**Comment by skipzero** [comment]
I'd love to return to helping out. It's been a trying few months but I think I'm good to return if you'll have me!? ;)

**Comment by jedireza** [comment]
Heck yeah @skipzero. Everyone is welcome to mentor. 👍

**Comment by JasonEtco** [comment]
I'd love to help out! Mentored at Nodeschool in Toronto, would be fun to continue here.

**Comment by jedireza** [comment]
Nice. See you there @JasonEtco.

**Comment by fforres** [comment]
Oh man! I'd love to help out. But cannot really be sure before friday if I can make it..
(I organized the Nodeschool in Santiago Chile with @Xabadu, and I'm going to be around SFO at the time.)
Can I confirm in some days?

**Comment by jedireza** [comment]
@fforres keep us posted. Worst case, you should just come by and hang out.

**Comment by fforres** [comment]
Oh!! Shoot! @jedireza 
Meant to be written on #208 🤣 I was exploring the issues and wrote on the wrong one.
I can write there to keep it tidy

**Comment by jedireza** [comment]
@fforres we have a hard deadline for mentor registration for that event. The deadline is supposed to be tomorrow, but I may have a couple days buffer. Keep in mind; that's a special event and we need strong commitments. 👍

**Comment by EBiddlecome** [comment]
I'll help mentor!

**Comment by jedireza** [comment]
Welcome @EBiddlecome. We'll see you there.

**Comment by Zahidul-Islam** [comment]
I would like to help.

**Comment by samarthgulati** [comment]
Me too!

**Comment by llkats** [comment]
Hi everyone! Thank you for volunteering - we're very excited for the event tomorrow! Please plan on showing up around 12:30 so we can do a mentor check-in and make sure we're all set in the space. Let us know if you have any questions. Thanks!

**Comment by jedireza** [comment]
🕺

**Comment by Trott** [comment]
It's looking like I'm going to be late. Sorry about that. Hope it's OK.

**Comment by llkats** [comment]
@Trott no worries, we look forward to seeing you whenever you can make it!

**Comment by paulgrock** [comment]
I just realized I only said I could come to the other event in July. Still room for me today?

**Comment by llkats** [comment]
@paulgrock always!! See you soon!

**Comment by EBiddlecome** [comment]
Hey everybody, I'm trapped in a teachers' planning meeting, and I might not make it by 12:30 (or even 1).  Sorry; I'll get there as soon as I can!

**Comment by llkats** [comment]
@ebiddlecome no worries, come on by when you can!

**Comment by Zahidul-Islam** [comment]
Hi everyone, I just miss BART from East Bay and I think I can't make it at 12:30. However I will be there before 1:00. Sorry for that...

**Comment by llkats** [comment]
@Zahidul-Islam don't worry about it!

**Comment by JasonEtco** [comment]
@llkats the office seems to be closed and under construction 😔

**Comment by jedireza** [comment]
That's the wrong address. We're headed to 555 California St, Suite 200, SF, CA 94104

**Comment by JasonEtco** [comment]
@jedirza oh no! Address up above is wrong. Samarth and I are walking over.

**Comment by jedireza** [comment]
Yes sorry. I just updated it. Must have been copy pasta.

**Comment by jedireza** [comment]
Yes sorry. I just updated it. Must have been copy pasta.

**Comment by Zahidul-Islam** [comment]
I am in wrong place 😞 Folsom street. Walking to 555 California str.

**Comment by EBiddlecome** [comment]
Ha- that's where I've been teaching!  I hope to see you all soon

**Comment by EBiddlecome** [comment]
I'm so sorry, this faculty meeting (that was supposed to be over at 12) is still dragging on; I am still  trying to escape.  I hope you are all not struggling for lack of mentors, and I hope that I can still help out at a future event, if I can't make it today.

**Comment by llkats** [comment]
@EBiddlecome please don't stress at all! We have a good little group going and everything is going just fine. If you happen to have time you're more than welcome to come by, but otherwise we'll be glad to have you in the future!

**Comment by jedireza** [comment]
That was a great event folks. Thanks again, everyone. 👍 🕺
