### ISSUE TITLE
Become a NodeSchool SF organizer

### ISSUE THREAD

**Issue by jedireza** [nodeschool/sanfrancisco#219]
Currently @llkats and myself are the primary organizers and we'd like to expand. Having more organizers will help make running events easier, more consistent and distribute the work.

We're looking for folks who can help organize; find event space/sponsors, do opening announcements, manage GitHub issues, update the website, create Tito ticket registration, market the event, etc...

If you've been a mentor before and you're interested to help organize, this is your time. Comment or ask questions here.

**Comment by Xabadu** [comment]
Hey, I'd love to help, so count me in!

**Comment by tlhunter** [comment]
I'd like to throw my name into the hat

**Comment by skipzero** [comment]
I'd love to, I'm only concerned about redundancy. If there were several people doing it, I'd be one of several, but can't commit to being one of few like @jedireza and @llkats are now. I know it's only once a month, but lots goes on behind the scenes to make that once a month happen.

**Comment by llkats** [comment]
Some of the more tedious monthly tasks could definitely be automated leveraging @Fauntleroy's awesome work with the [scripts he's written for NodeSchool Oakland](https://github.com/nodeschool/oakland). The refactor of the NodeSchool website was the first step to make that happen, and y'all could continue that effort.

My own plan is to step away entirely from organizing NodeSchool SF. It's been a phenomenal 2.5 years, but I would like to put my energies towards new things. You will still see me around every so often as a mentor, but after August I'd like to hang up my metaphorical organizer hat. :)

**Comment by nebrius** [comment]
_throws hat in ring_. If nothing else, perhaps I could take on "venue wrangling" since I have pretty regular access to Microsoft venues.

**Comment by Zahidul-Islam** [comment]
I would love to help. Please let me know ***how can I help.***

**Comment by jedireza** [comment]
We're super happy to announce that @Xabadu and @tlhunter will be the lead organizers of NodeSchool SF after our August event. 🎉
