### ISSUE TITLE
Mentor Registration for October 28th, 2017

### ISSUE THREAD

**Issue by Xabadu** [nodeschool/sanfrancisco#226]
Microsoft is hosting us on October 28th from 1pm - 5pm. The address is: 680 Folsom Street, Suite 145 San Francisco, CA 94107 -- Comment to get involved or ask questions.

Mentors should:
- Have already completed the [core NodeSchool workshoppers](http://nodeschool.io/#workshopper-list) before the event.
- Having also completed elective workshoppers is a great bonus._
- Review the [Mentor Best Practices](https://github.com/nodeschool/organizers/wiki/Event-Mentor-Best-Practices) wiki page.
- Arrive 30 minutes early (12:30p) so we can get setup and have our mentor meeting.

Confirmed mentors:
- [x] @benhalverson 
- [x] @mattiaerre 
- [x] @n0f3 
- [x] @shiya 
- [x] @Trott 
- [x] @iqnivek 
- [x] @gsathya
- [x] @amazingandyyy 
- [x] @samarthgulati 
- [ ] *You?* 

Organizers:
- [x] @nebrius
- [ ] @tlhunter
- [x] @Xabadu

Attendee registration link: https://www.meetup.com/en-US/sfnodeschool/events/244163365/?eventId=244163365

Slides:
 - Intros: TBD
 - Shoutouts: TBD
 - Shoutout loop: TBD

**Comment by tlhunter** [comment]
😺 @Trott @bengl @benhalverson @xakirax @n0f3 @mattiaerre @diffalot @samarthgulati

**Comment by benhalverson** [comment]
Yep I can make it 👍

**Comment by mattiaerre** [comment]
yes man, count me in 👍 @tlhunter

**Comment by n0f3** [comment]
always in!

**Comment by xakirax** [comment]
I'll be there!

On Thu, Oct 12, 2017 at 10:22 PM, Alessandro Metta <notifications@github.com

**Comment by shiya** [comment]
Hi! I've love to help! I didn't learn node using nodeschool materials but can I help if I finish all the workshoppers and get myself familiarized with the content?

**Comment by Xabadu** [comment]
@shiya absolutely! Happy to have you with us.

**Comment by Trott** [comment]
\o

**Comment by xakirax** [comment]
Actually realized I'll be out of town and can't make it

**Comment by iqnivek** [comment]
Hi, I'd like to mentor as well if that's okay!

**Comment by Xabadu** [comment]
Absolutely @iqnivek, thanks for joining!

**Comment by gsathya** [comment]
I'd like to help mentor as well. I haven't been to one of these before but I'm familiar with the workshoppers content.

**Comment by amazingandyyy** [comment]
used to be mentor for oakland chapter, will love to help SF this weekend~

**Comment by Xabadu** [comment]
Awesome! Thanks for joining @gsathya @amazingandyyy!

**Comment by Trott** [comment]
Left-field question: Is it OK to bring my 5-year-old? She'll eat some snacks, draw on any whiteboards available, read books we bring, and watch Sesame Street on my laptop while wearing headphones so as not to disturb others. Oh, and spin in any chairs that rotate. Totally get it if that's not OK. Just want to know what my options are.

**Comment by Trott** [comment]
Also, if there are any [Scratch](https://scratch.mit.edu/) workshoppers in NodeSchool, I can get her started with that. :-D

**Comment by nebrius** [comment]
@Trott feel free to bring your daughter! Right after I joined MS Evangelism, one of my team members hosted a 300 person event specifically targeting young girls, so I think we're fine ;-)

**Comment by bengl** [comment]
I will sadly be missing this one. See you all next time!

**Comment by samarthgulati** [comment]
I'm in

**Comment by Xabadu** [comment]
Hey mentors! Thanks again for signing up and helping us tomorrow. Please remember to arrive around 12.30 so we can do a mentor check-in. 

If you have any questions, feel free to ask them here.

See you all tomorrow!

**Comment by amazingandyyy** [comment]
@Xabadu this is andy, I am sorry I cannot help out today >.<, I just got an unexpected meeting appointment. Hope to help out next month.

**Comment by Xabadu** [comment]
No problem @amazingandyyy! Thanks for letting us know!

**Comment by mattiaerre** [comment]
we are missing you @tlhunter hope the conf is going well 😉

**Comment by Xabadu** [comment]
Thanks everyone for attending and helping us today!. It was a great event 🙌 

See you next month!
