### ISSUE TITLE
Make gh-pages default branch?

### ISSUE THREAD

**Issue by Trott** [nodeschool/sanfrancisco#23]
Looks like the automatic closing of tickets isn't happening based on the "fix/resolve/close" words in PRs and issues because the default branch is master but all the action is over in gh-pages. It might be a good idea to make gh-pages the default branch and delete the master branch. People who have forked may need to adjust their remotes if you do this and/or do this in their own forks. I'm not sure. But hopefully that's a pretty small number right now of mostly power-users.

**Comment by RichardLitt** [comment]
Wouldn't just merging gh-pages into master do it, too?

**Comment by Trott** [comment]
Yes, that would do it. The one disadvantage is that you have to keep master and gh-pages in sync. It's simpler to just have gh-pages and that's it.

**Comment by jedireza** [comment]
Since we're not using `master`, I'm fine with making `gh-pages` the default.

**Comment by Trott** [comment]
A third and probably least-controversial alternative would be to just close all the issues and PRs manually. I would recommend sync'ing the `README` over from `gh-pages` though.

**Comment by jedireza** [comment]
I made `gh-pages` the default. It's super easy to change if we end up not liking it.
