### ISSUE TITLE
Focused sessions

### ISSUE THREAD

**Issue by benhalverson** [nodeschool/sanfrancisco#231]
@Xabadu Any idea on when the next focused session will be?

**Comment by Xabadu** [comment]
Hey @benhalverson, we have been discussing having a new one for a while, but haven't made the arrangements. I'm thinking that maybe the next event could be a good opportunity. Do you wanna drive one?

@tlhunter @nebrius what do you think?

**Comment by nebrius** [comment]
Sounds good to me, I was actually randomly thinking the other day that we should work on bringing them back.

**Comment by benhalverson** [comment]
@Xabadu Yes I'm interested in driving one / helping out.

**Comment by Xabadu** [comment]
That's awesome @benhalverson, thanks for volunteering! Let's plan something for the January event then. Any topics in mind for the session?

**Comment by benhalverson** [comment]
I was thinking something beyond todo apps. 
- How about parsing data from a resume / large data set. 
- Another topic might be using some api in a production environment 
- TDD with node core or some lib / framework 

These are 3 ideas while I am standing on my BART commute ride home.

**Comment by Xabadu** [comment]
Sounds good @benhalverson, I think all are good useful ideas. We'll reach out to you as soon as we start planning the next event and we can work out the details.

Thanks again!

**Comment by Xabadu** [comment]
Hey @benhalverson. We're planning our next event for Saturday, January 27th. Still up for a focused session?

**Comment by benhalverson** [comment]
Yep @Xabadu what's the topic?

**Comment by Xabadu** [comment]
I'm open to ideas @benhalverson, do you have something in mind?

@nebrius @tlhunter any preferences?

**Comment by tlhunter** [comment]
I like the idea of consuming a real API and working with the data. Maybe pick a self-contained project that folks could complete by the time they leave the session?

**Comment by bengl** [comment]
Hello! As discussed today at NodeSchool, I'd like to do a focused session/workshop on performance investigation and tools.

**Comment by Xabadu** [comment]
That's awesome @bengl. Thanks for offering! I'm gonna figure out the details of the next event and we'll reach out to start coordinating this. (cc @n0f3)
