### ISSUE TITLE
Mentor Registration for February 24th, 2018

### ISSUE THREAD

**Issue by Xabadu** [nodeschool/sanfrancisco#234]
Microsoft is hosting us on February 24th for our 3 year anniversary from 1pm - 5pm!. The address is: 680 Folsom Street, Suite 145 San Francisco, CA 94107 -- Comment to get involved or ask questions.

Mentors should:
- Have already completed the [core NodeSchool workshoppers](http://nodeschool.io/#workshopper-list) before the event.
- Having also completed elective workshoppers is a great bonus.
- Review the [Mentor Best Practices](https://github.com/nodeschool/organizers/wiki/Event-Mentor-Best-Practices) wiki page.
- Arrive 30 minutes early (12:30p) so we can get setup and have our mentor meeting.

Confirmed mentors:
- [x] @fforres
- [x] @benhalverson
- [x] @bengl
- [x] @n0f3  
- [x] @joshleichtung 
- [x] @vdeturckheim 
- [ ] *You?*
- [ ] *You?*
- [ ] *You?*
- [ ] *You?* 

Organizers:
- [x] @nebrius
- [x] @tlhunter
- [x] @Xabadu

Attendee registration link: https://www.meetup.com/sfnodeschool/events/247528443/

Focused Session: **Open Source Contributions with NodeSchool Workshops by Alessandro Metta** (@n0f3)

**Comment by Xabadu** [comment]
@Trott @fforres @samarthgulati @bengl @benhalverson @n0f3 @shiya @iqnivek @itsmed @bradvogel 👍 ? 🍕 ?  😎 ?

**Comment by fforres** [comment]
Can I!? Can I!? 
I moved to SFO, so count me in from now on 😃

**Comment by Xabadu** [comment]
@fforres welcome to SF! (and to NodeSchool SF!) (and to the Jungle!)

![welcome-nerd-zone](https://user-images.githubusercontent.com/3161019/35835613-883a9e74-0a90-11e8-9ad4-6855b84c208d.gif)

**Comment by itsmed** [comment]
Alas, I wil be out of town this time. and for the three year anniversary party, too! See you in March!

**Comment by Xabadu** [comment]
Aww that's unfortunate @itsmed. See you in March!

**Comment by benhalverson** [comment]
I'll be there 👍  🍕

**Comment by shiya** [comment]
Taking a vacation in China during this time, have fun you all!

**Comment by tlhunter** [comment]
@llkats @jedireza 😸

**Comment by bengl** [comment]
![i'm in](https://i.pinimg.com/originals/49/af/fc/49affc2244d933a0930f98461474ab6b.gif)

**Comment by n0f3** [comment]
I'll be there!

**Comment by llkats** [comment]
I'm going to come hang out, but prefer to not mentor. Looking forward to it!

**Comment by jedireza** [comment]
I can't commit. Though it's on my calendar now so if I can swing by, I will. :shipit:

**Comment by Xabadu** [comment]
@cantremember @jeduan @marulango @aszheng @joshleichtung @LewisJEllis @MaitreyaBuddha 👍 ? 🍰?  🎉 ? 😎 ?

**Comment by MaitreyaBuddha** [comment]
Thanks for the reminder @Xabadu ! I'll be out of town, but hopefully sending a student your way

**Comment by joshleichtung** [comment]
I'll be there 🍰

**Comment by Xabadu** [comment]
Thanks for the heads up @MaitreyaBuddha !

Awesome @joshleichtung, thanks for joining!

**Comment by vdeturckheim** [comment]
So I'm in SF this week, I probably can help :D

**Comment by Xabadu** [comment]
Awesome, thanks for joining @vdeturckheim!

**Comment by Xabadu** [comment]
Thanks everyone for coming, it was a great event! See you in March! ✌️
