### ISSUE TITLE
Mentor Registration for April 28th, 2018

### ISSUE THREAD

**Issue by Xabadu** [nodeschool/sanfrancisco#239]
Hello everybody 👋!

Mixmax is hosting us on April 28th from 1pm - 5pm!. The address is: 512 2nd Street, San Francisco, CA 94107 -- Comment to get involved or ask questions.

If this is your first time mentoring and are in doubt, we're sure you can! Just leave us a comment and we'll help you in any way we can.

Mentors should:
- Have already completed the [core NodeSchool workshoppers](http://nodeschool.io/#workshopper-list) before the event.
- Having also completed elective workshoppers is a great bonus.
- Review the [Mentor Best Practices](https://github.com/nodeschool/organizers/wiki/Event-Mentor-Best-Practices) wiki page.
- Arrive 30 minutes early (12:30p) so we can get setup and have our mentor meeting.

Confirmed mentors:
- [x] @bengl
- [x] @n0f3 
- [x] @samarthgulati 
- [x] @cantremember
- [x] @MaitreyaBuddha
- [x] @itsmed
- [x] @tauseefk
- [x] @benhalverson
- [x] @iqnivek
- [x] @hath995
- [ ] *You?*

Organizers:
- [ ] @nebrius
- [ ] @tlhunter
- [x] @Xabadu

Thanks for joining! 🙌 

Attendee registration link: https://www.meetup.com/sfnodeschool/events/249466981/

**Comment by bengl** [comment]
Ya! Also, perf focused session?

**Comment by Xabadu** [comment]
@bengl Yas! We're shooting you an email in a bit to coordinate :)

![referee-thumbs-up](https://user-images.githubusercontent.com/3161019/38384565-5d14a9bc-38c4-11e8-9c0a-ee66e732f997.gif)

**Comment by n0f3** [comment]
@Xabadu always in

**Comment by Xabadu** [comment]
@n0f3 🙌 

![yeah-cage](https://user-images.githubusercontent.com/3161019/38396679-38389250-38ee-11e8-934e-7fe863fd4d74.gif)

**Comment by fforres** [comment]
![](https://media.giphy.com/media/ChMy4X2DkiLTy/giphy.gif)

**Comment by Xabadu** [comment]
Yaaas @fforres ✌️

![yay-seinfeld](https://user-images.githubusercontent.com/3161019/38396928-a1b101b2-38ef-11e8-9ee7-04d386eea57e.gif)

**Comment by Xabadu** [comment]
@cantremember @MaitreyaBuddha glad to have you with us again! 🙌

![macho-man-oh-yeah](https://user-images.githubusercontent.com/3161019/38403726-5c6992c4-391a-11e8-882a-103baf138b28.gif)

**Comment by itsmed** [comment]
reporting for duty 
<img src="https://media.giphy.com/media/uMANNaqTUVz0s/giphy.gif" />

**Comment by Xabadu** [comment]
@itsmed youuuuu're in! 🙌

![ninja-turtles](https://user-images.githubusercontent.com/3161019/38438887-b267ca6c-3990-11e8-8201-2f9bba834589.gif)

**Comment by benhalverson** [comment]
I’ll be there 🎉

**Comment by Xabadu** [comment]
Yaaas @tauseefk @benhalverson! See you there ✌️

![high-knive](https://user-images.githubusercontent.com/3161019/38829255-5d767eba-416d-11e8-9668-810f0c5fd8fc.gif)

**Comment by iqnivek** [comment]
I'd be interested!

<img width=350 src=https://user-images.githubusercontent.com/396006/38850437-45ad26fe-41c6-11e8-9bae-5b1025f76366.gif>

**Comment by Xabadu** [comment]
Aww Yeah! Welcome back @iqnivek!

![welcome-back-wd](https://user-images.githubusercontent.com/3161019/38852099-499ebd98-41cd-11e8-84a0-a83e2b6146b3.gif)

**Comment by hath995** [comment]
I'll sign up to mentor.

**Comment by Xabadu** [comment]
Aw Yeas @hath995, you're in! 🙌

![bow](https://user-images.githubusercontent.com/3161019/39089918-166200d6-4586-11e8-9458-7d249bda6616.gif)

**Comment by n0f3** [comment]
Hi guys I have to echo Felipe something came up super last minute and I won't be there. See you next time!

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by itsmed** [comment]
I ran late and ended up getting a lyft form hayward, because maps said it
would be faster; it hasn't been. See you all soon, hopefully by 1:30 at least
Dejon Gilldejonjgill@gmail.com






On Sat, Apr 28, 2018 12:13 PM, Alessandro Metta notifications@github.com  wrote:
Hi guys I have to echo Felipe something came up super last minute and I won't be
there. See you next time! 

Get Outlook for iOS<https://aka.ms/o0ukef> 
________________________________

**Comment by Xabadu** [comment]
Thanks everyone for coming today, it was a great event. See you next month! ✌️

**Comment by jetong** [comment]
Thanks everyone for making this happen.  Really awesome stuff, great mentors!!
