### ISSUE TITLE
build instructions and/or source files needed

### ISSUE THREAD

**Issue by Trott** [nodeschool/sanfrancisco#24]
There's a bug in docs.min.js (it's trying to load the zeroClipboard SWF file from `/assets/flash` but since the site's docroot is a subdirectory, it doesn't find it) but it's not obvious how `docs.min.js` is built. No other files mention `/assets/flash` so the source file is quite likely not in the repo at all.

**Comment by Trott** [comment]
Looks like the `docs.js` bug was introduced by the Campinas fork. I suspect we are not using the zeroClipboard SWF (or at least not depending on it, since it isn't loading) and can probably remove the JS and SWF file.

**Comment by jedireza** [comment]
That's correct. We don't use flash for anything right now.
