### ISSUE TITLE
NodeSchool at Node Summit - July 23rd, 2018!

### ISSUE THREAD

**Issue by Xabadu** [nodeschool/sanfrancisco#244]
[Node Summit](http://nodesummit.com/) is a five-day conference in San Francisco. It will be on July 23rd-27th 2018 at [Mission Bay Conference Center](http://nodesummit.com/venue/). 

🎉 NodeSchool SF has been invited to host a NodeSchool on [Day Zero](http://nodesummit.com/day-zero/) (July 23rd) of the Node Summit conference from 12:30 pm - 5:00 pm. 🎊 

Since this is a special event, we do ask that you've mentored at one of our events before and that you're excited to engage with attendees. We're accepting up to 6 mentors for this event. Mentors will get a ticket to Node Summit for volunteering.

Comment to get involved or ask questions.

Mentors should:
- Have mentored at a NodeSchool before.
- Have already completed the [core NodeSchool workshoppers](http://nodeschool.io/#workshopper-list) before the event.
  - _Having also completed elective workshoppers is a great bonus._
- Review the [Mentor Best Practices](https://github.com/nodeschool/organizers/wiki/Event-Mentor-Best-Practices) wiki page.
- Arrive 30 minutes early so we can get setup and have our mentor meeting.

Confirmed mentors:
- [x] @Trott
- [x] @n0f3 
- [x] @fforres 
- [x] @paulgrock 
- [x] @benhalverson
- [x] @creedarky
- [x] @Fauntleroy
- [x] @cantremember

Organizers and volunteers:
- [x] @nebrius
- [x] @tlhunter
- [x] @Xabadu

**Comment by Xabadu** [comment]
@Trott always good to have you indeed! :)

@n0f3 but... but... I thought **we** were your family 😞  - Totally fine! Keep us posted 😄

**Comment by fforres** [comment]
That's so cool!!
I'm up for it! 😄

**Comment by fforres** [comment]
If there's stuff you need help before the date, count me in also! 
🙏

**Comment by nebrius** [comment]
FYI I just chatted with Joe, and he had a scheduling conflict come up and can't make it now. Next time perhaps :)

**Comment by Xabadu** [comment]
@paulgrock you're in! Thanks for joining 🙌

**Comment by benhalverson** [comment]
Count me in 
👍

**Comment by Xabadu** [comment]
@benhalverson you're in! 🤘

**Comment by creedarky** [comment]
I want to join! 😄

**Comment by Fauntleroy** [comment]
👋

**Comment by Xabadu** [comment]
@creedarky @Fauntleroy you're in, thanks for joining! ✌️

**Comment by cantremember** [comment]
there's one checkbox left -- and i can take it.  i don't even need a Conference ticket!

![check me!](https://assets.justinmind.com/blog/wp-content/uploads/2018/04/checkbox-v-radio-buttons-checkbox.gif)

**Comment by Zahidul-Islam** [comment]
@Xabadu I’d love to help out. Count me in.

**Comment by peanutenthusiast** [comment]
@Xabadu I'd love to help out in case of emergencies, etc. 😄

**Comment by Xabadu** [comment]
Thanks, everyone for joining and helping us out! We hope you enjoyed the conference!

See you at the next event ✌️
