### ISSUE TITLE
Mentor Registration for December 1st, 2018

### ISSUE THREAD

**Issue by Xabadu** [nodeschool/sanfrancisco#252]
Hello everybody 👋!

Microsoft is hosting us on December 1st from 1pm - 5pm!. The address is: 680 Folsom Street, Suite 145 San Francisco, CA 94107 -- Comment to get involved or ask questions.

If this is your first time mentoring and are in doubt, we're sure you can! Just leave us a comment and we'll help you in any way we can.

Mentors should:
- Have already completed the [core NodeSchool workshoppers](http://nodeschool.io/#workshopper-list) before the event.
- Having also completed elective workshoppers is a great bonus.
- Review the [Mentor Best Practices](https://github.com/nodeschool/organizers/wiki/Event-Mentor-Best-Practices) wiki page.
- Arrive 30 minutes early (12:30p) so we can get setup and have our mentor meeting.

Confirmed mentors:
- [x] @diffalot 
- [x] @creedarky 
- [x] @iqnivek 
- [x] @itsmed 
- [x] @bengl 
- [x] @tauseefk 
- [x] @benhalverson 
- [x] @Zahidul-Islam 
- [x] @blacktechgenius 
- [x] @austintackaberry 

Organizers:
- [x] @nebrius
- [x] @tlhunter
- [x] @Xabadu

Thanks for joining! 🙌 

Attendee registration link: https://www.meetup.com/sfnodeschool/events/256155086/

**Comment by Xabadu** [comment]
@bengl @benhalverson @n0f3 @shiya @itsmed @Fauntleroy @Trott @feross @wmsmacdonald @apapirovski @iqnivek @tauseefk @cantremember @Zahidul-Islam @hath995 @creedarky @fforres @pangperry @dkim1116 @diffalot @austintackaberry 👍? ⬡.js? 🍕? 😎?

**Comment by creedarky** [comment]
I'm in

**Comment by Xabadu** [comment]
@creedarky @iqnivek @diffalot yaas, thanks for joining 🙌

![](https://media1.giphy.com/media/120jXUxrHF5QJ2/giphy.gif?cid=e1bb72ff5be20a204d724c5763bc0224)

**Comment by itsmed** [comment]
Count me in 

<img src="https://media.giphy.com/media/A5OyYtJVA9TNymD7by/giphy.gif" />

**Comment by Xabadu** [comment]
@itsmed Yaas! So good to have you with us again! 🙌
![](https://media1.giphy.com/media/3oz8xCLEgsQ8NPx8Aw/giphy.gif?cid=e1bb72ff5bee258c794c444677cb5942)

**Comment by bengl** [comment]
I'm in (and so is the smoke).

![](https://pbs.twimg.com/media/DsFrBPLVsAA70xY.jpg:large)

**Comment by Xabadu** [comment]
@bengl 🙌🙌

![](https://media.giphy.com/media/MrxXXBriEIKBO/giphy.gif)

**Comment by tauseefk** [comment]
![I'm in](https://media.giphy.com/media/oDOnRIDjxlCzC/giphy.gif)

**Comment by benhalverson** [comment]
count me in 👍 🎉 @Xabadu

**Comment by Xabadu** [comment]
@benhalverson 🙌

![](https://media.giphy.com/media/l3V0sNZ0NGomeurCM/giphy.gif)

**Comment by Xabadu** [comment]
@Zahidul-Islam 🙌

![](https://media1.giphy.com/media/r2BtghAUTmpP2/giphy.gif?cid=e1bb72ff5bfc2b8167576f6567a5ef1a)

**Comment by blacktechgenius** [comment]
I'M DOWN

**Comment by Xabadu** [comment]
@blacktechgenius 🙌

![](https://media0.giphy.com/media/QN6NnhbgfOpoI/giphy.gif?cid=e1bb72ff5c01b486757172336b34c78f)

**Comment by Xabadu** [comment]
Hey everyone! Just a reminder (since we opened this issue a while back) that this is happening tomorrow! - For those of you that haven't been to the Microsoft Reactor space before: The entrance is right after crossing the main door on the right side. There's a big Microsoft logo, so you shouldn't miss it, but feel free to ping us on this issue if you can't find it.

See you there ✌️!

**Comment by austintackaberry** [comment]
i'm hella in

**Comment by Xabadu** [comment]
Thanks, everyone for coming! It was a great event! See you in January! ✌️

Happy Holidays! 🎅🎄☃️
