### ISSUE TITLE
Mentor Registration for February 16th, 2019

### ISSUE THREAD

**Issue by Xabadu** [nodeschool/sanfrancisco#257]
Hello everybody 👋!

Microsoft Reactor is hosting us on February 16th for our 4th Year Anniversary (🎊 🎂 🎆 ) from 1 pm - 5 pm!. The address is: 680 Folsom St, Suite 145, San Francisco, CA 94107 -- Comment to get involved or ask questions.

If this is your first time mentoring and are in doubt, we're sure you can! Just leave us a comment and we'll help you in any way we can.

Mentors should:
- Have already completed the [core NodeSchool workshoppers](http://nodeschool.io/#workshopper-list) before the event.
- Having also completed elective workshoppers is a great bonus.
- Review the [Mentor Best Practices](https://github.com/nodeschool/organizers/wiki/Event-Mentor-Best-Practices) wiki page.
- Arrive 30 minutes early (12:30p) so we can get set up and have our mentor meeting.

Confirmed mentors:
- [x] @iqnivek 
- [x] @creedarky
- [x] @cantremember
- [x] @benhalverson 
- [x] @klequis 
- [x] @itsmed 
- [x] @bengl
- [x] @skipzero 
- [x] @MarcoMedrano 
- [ ] You?

Organizers:
- [x] @nebrius
- [x] @tlhunter
- [x] @Xabadu

Thanks for joining! 🙌 

Attendee registration link: https://www.meetup.com/sfnodeschool/events/258536522/

**Comment by Xabadu** [comment]
@llkats @jedireza @bengl @bradvogel @benhalverson @n0f3 @shiya @itsmed @Fauntleroy @Trott @iqnivek @tauseefk @cantremember @czekaj @mpmckenna8 @hath995 @creedarky @pangperry @dkim1116 @diffalot @austintackaberry 👍? ⬡.js? 🍕? 🍰? 😎?

**Comment by llkats** [comment]
@Xabadu I'll have to see! But this reminded me to grant y'all admin rights to this repo, so just wanted to note that you now have _The Power_.

**Comment by Xabadu** [comment]
@llkats nice! Thanks for that! Hopefully, you can stop by. We'll save you a piece of 🍰 :)

**Comment by Xabadu** [comment]
@iqnivek indeed you are! 🙌

![](https://media.giphy.com/media/3ohs4dxsBnweXVAxkk/giphy.gif)

**Comment by creedarky** [comment]
I'm in

**Comment by cantremember** [comment]
`o/` i could also be in on this action

**Comment by Xabadu** [comment]
@creedarky @cantremember 🙌

![](https://media.giphy.com/media/26DMTfqxbJQzsHp0k/giphy.gif)

**Comment by klequis** [comment]
I'm up for mentoring as well

**Comment by benhalverson** [comment]
count me in 👍

**Comment by Xabadu** [comment]
@klequis @benhalverson 🙌 

![](https://media.giphy.com/media/xUOxeRRkTYdQJfyy2Y/giphy.gif)

**Comment by itsmed** [comment]
did I hear something about cake?!
<img src="https://media.giphy.com/media/S7i2sED2yfDGg/giphy.gif" />

**Comment by Xabadu** [comment]
@itsmed 😏🍰😏

![](https://media.giphy.com/media/3ohs80ubv3iyojPquY/giphy.gif)

**Comment by skipzero** [comment]
I'd love to volunteer this weekend. It's been a minute since I've been able to commit to volunteering, but I can definitely make it now! 👍

**Comment by Xabadu** [comment]
@skipzero 🙌 

![](https://media.giphy.com/media/3M7pmsN2jp9lAV9QTG/giphy.gif)

**Comment by manpreet024** [comment]
can anybody be mentor of this event without physically present there... i mean through video chat?

**Comment by MarcoMedrano** [comment]
@Xabadu, if you still need mentor I dont not consider myself a node developer, but have lot of experience with JS, Babel, TS, NPM,  inversify (IOC), winston log, mobx, react, some of cordoba, some node for aws lambda yeah! and actually many of the libs and frameworks I use were made for node but we use them trough webpack or browserify.

I will be glad to help otherwise will attend your workshop for sure XD

**Comment by Xabadu** [comment]
@MarcoMedrano absolutely, happy to have you join us! 🙌

![](https://media.giphy.com/media/l3mZfxgPWhmuXa8Cc/giphy.gif)

**Comment by tauseefk** [comment]
![](https://media1.tenor.com/images/faa086ffafa2a4b7419633b687cd639f/tenor.gif)
running a hackathon at Stanford..

**Comment by klequis** [comment]
Unfortunately I am sick :(  See you all next time.

**Comment by cantremember** [comment]
up-front, i know i may be a bit late

us Mentors are supposed to arrive @ 12:30p, but my ETA might be trending towards 1:15p

**Comment by skipzero** [comment]
cat emergency, sorry. I guess otta go to the vet today... :(

**Comment by benhalverson** [comment]
On my way in traffic 🤦🏼‍♂️

**Comment by Trott** [comment]
On my way too. Hope it’s ok to last-minute mentor-crash like this.

**Comment by Xabadu** [comment]
Thanks, everyone for coming and helping us, it was a great event! See you next month! ❤️ ✌️
