### ISSUE TITLE
Workshop Proposal: Node.js and Web APIs for starters! 

### ISSUE THREAD

**Issue by ErickWendel** [nodeschool/sanfrancisco#264]
I feel that my last workshop was advanced for the public and sometimes was hard for who is starting with node.js and Javascript. 
My goal in this workshop is to create a complete Web API using Hapi.js, MongoDB focused on starters in Node.js and Javascript. 

We'll need only the **Node.js 10+** installed and an account on **MongoDB** to get your MongoDB free instance :D

**Comment by benhalverson** [comment]
I thought the pace was kinda slow for me. It seemed like a lot of waiting between steps. 
🤔

**Comment by Xabadu** [comment]
@ErickWendel sounds great and I'm sure people will get a lot out of it. Our next event will be on March 30th, does that date works for you?

How long will this session last? 

@tlhunter @nebrius any thoughts?

**Comment by ErickWendel** [comment]
I think 90 minutes could work!

**Comment by tlhunter** [comment]
Sounds fine to me. A lot of our attendees are fairly new to Node.js so this workshop would probably have a good turnout.

**Comment by nebrius** [comment]
Sounds good to me too!

**Comment by Xabadu** [comment]
Thanks for doing this workshop @ErickWendel! It was a big hit :)

**Comment by ErickWendel** [comment]
thanks brother!! It was a fantastic experience for me as well
