### ISSUE TITLE
Focused Session/Workshop Proposal: worker_threads crash course

### ISSUE THREAD

**Issue by Trott** [nodeschool/sanfrancisco#265]
I could do a crash course for beginners on the worker_threads module. Maybe in late April or early May? It would be for people who are curious but haven't actually done much of anything with worker_threads.

**Comment by nebrius** [comment]
Heck, I'd sit in on this!

**Comment by Xabadu** [comment]
@Trott that sounds great! I'd definitely sit in on this as well 😄  - I'm gonna work on locking the dates for April asap and let you know so we can schedule it. Thanks!

**Comment by Xabadu** [comment]
Hi @Trott! Our next event will be on April 20th. Would that date work for you regarding this session?

**Comment by Trott** [comment]
I"m sorry for the delay in responding. I honestly don't know and won't know for a bit. I think I have to punt and say "Look for another focused session this time" and maybe if you have trouble finding one, the stars will align and I'll be all like "Yeah, turns out I can do it after all!" Sorry to be unable to commit. Life is weird right now.

**Comment by Xabadu** [comment]
No worries at all @Trott, really sorry to hear things aren't good at the moment. Take care of yourself, we'll be happy to have you whenever you want :)

**Comment by Trott** [comment]
Committing to this isn't anything I'm going to be able to do for a while, so I'm going to close this. Sorry.
