### ISSUE TITLE
Mentor Registration for April 20th, 2019

### ISSUE THREAD

**Issue by Xabadu** [nodeschool/sanfrancisco#267]
Hello everybody 👋!

Microsoft Reactor is hosting us on April 20th from 1pm - 5pm!. The address is: 680 Folsom St, Suite 145, San Francisco, CA 94107 -- Comment to get involved or ask questions.

If this is your first time mentoring and you're not sure you're ready, we're sure you are! Just leave us a comment and we'll help you in any way we can.

Mentors should:
- Have already completed the [core NodeSchool workshoppers](http://nodeschool.io/#workshopper-list) before the event.
- Having also completed elective workshoppers is a great bonus.
- Review the [Mentor Best Practices](https://github.com/nodeschool/organizers/wiki/Event-Mentor-Best-Practices) wiki page.
- Arrive 30 minutes early (12:30p) so we can get set up and have our mentor meeting.

Confirmed mentors:
- [x] @lzanol
- [x] @jorgepvenegas 
- [x] @creedarky
- [x] @bengl
- [x] @tauseefk
- [x] @Rob-ot
- [ ] You?
- [ ] You?
- [ ] You?
- [ ] You?

Organizers:
- [x] @nebrius
- [x] @tlhunter
- [x] @Xabadu

Thanks for joining! 🙌 

Attendee registration link: https://www.meetup.com/sfnodeschool/events/260312635

**Comment by Xabadu** [comment]
@bengl @benhalverson @shiya @itsmed @Fauntleroy @Trott @kevinsqi @tauseefk @cantremember @creedarky @pangperry @dkim1116 @MaitreyaBuddha @Zahidul-Islam @klequis @ErickWendel @lzanol  👍? ⬡.js? 🍕? 😎?

**Comment by lzanol** [comment]
Sounds good! 👍

**Comment by jorgepvenegas** [comment]
👍 👵

**Comment by Xabadu** [comment]
@lzanol @jorgepvenegas 🙌 

![](https://media.giphy.com/media/VIybTqiAz8E5W/giphy.gif)

**Comment by creedarky** [comment]
I'm in

**Comment by Xabadu** [comment]
@creedarky 🙌 

![](https://media.giphy.com/media/6drX3zwQvyd3O/giphy.gif)

**Comment by Xabadu** [comment]
Sorry for the noise folks! We're a bit short on mentors for this one, so just doing another round of tags in case someone missed this: @benhalverson @shiya @Trott @kevinsqi @tauseefk @cantremember @pangperry @dkim1116 @MaitreyaBuddha @Zahidul-Islam @klequis 👍? ⬡.js? 🍕? 😎?

**Comment by kevinsqi** [comment]
Sorry I can't make it - family is in town!

**Comment by Xabadu** [comment]
No worries @kevinsqi, sorry for the extra tag 😅- See you next time, have fun!

**Comment by tauseefk** [comment]
![Shazam!](https://media1.tenor.com/images/339eb729fa629cb507b3e20114a50e6e/tenor.gif)

**Comment by Xabadu** [comment]
@tauseefk 🙌

![](https://media.giphy.com/media/14aAJoti7DkZtm/giphy.gif)

**Comment by Rob-ot** [comment]
It's been a while since I last mentored but I'm back. I'm in!

![](https://giphy.com/gifs/yDObBMJRdc1kk)

**Comment by Xabadu** [comment]
@Rob-ot just in time! 🙌

![](https://media.giphy.com/media/1lk1IcVgqPLkA/giphy.gif)

**Comment by lzanol** [comment]
Hi everyone, got delayed, will get there at 1pm.

**Comment by Xabadu** [comment]
Thanks, everyone for coming today, it was a great event. See you next month!

**Comment by klequis** [comment]
Sadly going to miss this one. Getting a ligament tear in my hip fixed and will be spaced out on pain meds this day. Hopefully see you next time.
