### ISSUE TITLE
Workshop Session Proposal: Building a VSCode Extension using Typescript

### ISSUE THREAD

**Issue by ErickWendel** [nodeschool/sanfrancisco#269]
Hi friends. For this month I have a different idea (as talked to @Xabadu). Our workshop at this time will be focused to create a VSCode extension using Typescript. This workshop hasn't a goal to deep understand Typescript, otherwise, we'll create and publish a VSCode extension, to explore the power and facilities that VSCode could provide :D 

This could be executed in 90 minutes.

**Comment by Xabadu** [comment]
Hey @ErickWendel! Sounds great :), I think it's a fun and interesting topic that will gather a lot of interest from attendees. Just one minor question, how much effort would involve doing this in plain JavaScript instead of Typescript? I'm wondering if doing it in TS could add an extra layer of difficulty for people not familiar with it.

What do you think @tlhunter @nebrius?

**Comment by tlhunter** [comment]
@Xabadu interesting point... Many beginners do attend Nodeschool. Perhaps we should do a survey first to see how many attendees have TS experience?

**Comment by czekaj** [comment]
Aren't VS Code extensions exclusively written in TS?

**Comment by ErickWendel** [comment]
You’re right guys. Maybe add typescript could just confuse the attendees. I'll use  only Javascript for that

**Comment by nebrius** [comment]
🤔 the TypeScript question is a good one. You [can write extensions without TypeScript](https://code.visualstudio.com/api/get-started/your-first-extension#using-javascript), however the documentation for extensions isn't really written with that in mind. I'm actually on the fence. Perhaps you could introduce TypeScript later in the workshop after you've gotten the basics working?

**Comment by ErickWendel** [comment]
Yeah! For sure. I'll do it. I'll introduce Typescript and start our goal. I think it won't be a problem for the attendees because we'll use the VSCode environment, inside it could be easy to develop.

**Comment by ErickWendel** [comment]
Hi friends! Thanks for coming <3 I just published the resources that I used during the workshop. https://erickwendel.com \o/

**Comment by Xabadu** [comment]
Thanks for your session @ErickWendel, it was great! ✌️
