### ISSUE TITLE
Mentor Registration for June 1st, 2019

### ISSUE THREAD

**Issue by Xabadu** [nodeschool/sanfrancisco#272]
Hello everybody 👋!

Mixmax is hosting us on June 1st from 1pm - 5pm!. The address is: 512 2nd St, San Francisco, CA, 94107 -- Comment to get involved or ask questions.

If this is your first time mentoring and you're not sure you're ready, we're sure you are! Just leave us a comment and we'll help you in any way we can.

Mentors should:
- Have already completed the [core NodeSchool workshoppers](http://nodeschool.io/#workshopper-list) before the event.
- Having also completed elective workshoppers is a great bonus.
- Review the [Mentor Best Practices](https://github.com/nodeschool/organizers/wiki/Event-Mentor-Best-Practices) wiki page.
- Arrive 30 minutes early (12:30p) so we can get set up and have our mentor meeting.

Confirmed mentors:
- [x] @kevinsqi
- [x] @vincepmartin
- [x] @creedarky
- [x] @jasonsaisquoi
- [x] @itsmed
- [x] @tauseefk
- [x] @bengl
- [ ] You?
- [ ] You?
- [ ] You?

Organizers:
- [ ] @nebrius
- [x] @tlhunter
- [x] @Xabadu

Thanks for joining! 🙌 

Attendee registration link: https://www.meetup.com/sfnodeschool/events/261236115

**Comment by Xabadu** [comment]
@bengl @benhalverson @shiya @itsmed @Fauntleroy @Trott @kevinsqi @tauseefk @cantremember @creedarky @pangperry @dkim1116 @Zahidul-Islam @jorgepvenegas  @Rob-ot @lzanol  👍? ⬡.js? 🍕? 😎?

**Comment by dkim1116** [comment]
I'm in!

**Comment by lzanol** [comment]
Hi everyone, I'll be working from Brazil from this week through June 10th
and bringing/moving with my family to some city I don't know yet.

Looking forward to rejoining as soon as I can (most probably from
July/August on). Thanks for being such great team/people so far!

Best,
Leandro

**Comment by kevinsqi** [comment]
I'll be there!

**Comment by Xabadu** [comment]
@dkim1116 @kevinsqi :raised_hands:

![](https://media.giphy.com/media/YcMs3OGd89Pxu/giphy.gif)

@lzanol no worries, thanks for letting us know. See you when you get back!

**Comment by vincepmartin** [comment]
Let's do this.  I'd like to try my hand at mentoring :)

**Comment by creedarky** [comment]
I'm in

**Comment by Xabadu** [comment]
@vincepmartin @creedarky 🙌 

![](https://media.giphy.com/media/RLn2w2fLpcwTu/giphy.gif)

**Comment by jasonsaisquoi** [comment]
Nodeschool has been so helpful for learning JavaScript! It's time to pay it forward. I'm in!

**Comment by Xabadu** [comment]
@jasonsaisquoi hell yeah! This makes me really happy, welcome aboard! 🙌

![](https://media.giphy.com/media/fIVwYg5XgFfG0/giphy.gif)

**Comment by dkim1116** [comment]
... Hey Fernando, I'm on a project out of state and I was just asked to be
there for the weekend of 6/1-6/2 to support Prod issues after hitting a
milestone... I'm gonna try to squiggle out of it, but for now I don't think
I'll be able to make it. Sowie 🤒

**Comment by Xabadu** [comment]
Hey @dkim1116, no worries, duty calls! Thanks for letting us know. See you next time!

**Comment by itsmed** [comment]
<img src="https://media.giphy.com/media/26wku2hqwVCI2fsL6/giphy.gif" />

**Comment by Xabadu** [comment]
@itsmed aww yeah! 🙌

![](https://media.giphy.com/media/lT2BJjU4W2SQ0/giphy.gif)

**Comment by tauseefk** [comment]
![](https://media1.tenor.com/images/687f4b2f8aa83c09741cc95b18ea5198/tenor.gif)

**Comment by Xabadu** [comment]
@tauseefk 🙌 

![](https://media.giphy.com/media/3tpinSPvGf8MU/giphy.gif)

**Comment by Xabadu** [comment]
Thanks, everyone for coming, it was a great event! See you next time ✌️
