### ISSUE TITLE
Mentor Registration for February 29th, 2020: We're turning 5! 🎉🎂🍰🧁🎊🥳

### ISSUE THREAD

**Issue by Xabadu** [nodeschool/sanfrancisco#286]
Hello 👋!

Mixmax is hosting us on February 29th from 1pm - 5pm for our 5th Year Anniversary! 🎉🎂🍰🧁🎊🥳

The address is: **512 2nd St, San Francisco, CA, 94107** [(map)](https://www.google.com/maps/place/Mixmax,+Inc./@37.7827092,-122.3957529,17z/data=!3m1!4b1!4m5!3m4!1s0x80858079ab1e2721:0x8b4cccce0efa54ee!8m2!3d37.7827092!4d-122.3935642) -- Comment to get involved or ask questions.

If this is your first time mentoring and you're not sure you're ready, we're sure you are! Just leave us a comment and we'll help you in any way we can.

Mentors should:
- Have already completed the [core NodeSchool workshoppers](http://nodeschool.io/#workshopper-list) before the event.
- Having also completed elective workshoppers is a great bonus.
- Review the [Mentor Best Practices](https://github.com/nodeschool/organizers/wiki/Event-Mentor-Best-Practices) wiki page.
- Arrive 30 minutes early (12:30p) so we can get set up and have our mentor meeting.

Confirmed mentors:
- [x] @anchnk
- [x] @ch264
- [x] @creedarky
- [x] @amazingandyyy
- [x] @jasonsaisquoi
- [x] @sorrelbri
- [x] @mariohsieh
- [x] @Trott 
- [ ] You?
- [ ] You?

Organizers:
- [x] @nebrius
- [x] @tlhunter
- [x] @Xabadu

Thanks for joining! 🙌 

Attendee registration link:  https://www.meetup.com/sfnodeschool/events/268507800

**Comment by Xabadu** [comment]
@Trott @shiya @itsmed @Fauntleroy @kevinsqi @ch264 @tauseefk @cantremember @creedarky @pangperry @Abimzy @Zahidul-Islam @jorgepvenegas @jasonsaisquoi @vincepmartin @notfelineit @wongco @amazingandyyy @mariohsieh @anchnk @klequis ⬡.js? 🍕? 🍰? 👍?

**Comment by anchnk** [comment]
Let's celebrate!

**Comment by Xabadu** [comment]
@anchnk 🙌 

![](https://media3.giphy.com/media/m8crpzTJFRDPhqqhXJ/giphy-downsized-medium.gif)

**Comment by ch264** [comment]
I am in 🦄

**Comment by creedarky** [comment]
✋

**Comment by Xabadu** [comment]
@ch264 @creedarky 🙌 

![](https://media3.giphy.com/media/3oKIPjzfv0sI2p7fDW/giphy.gif)

**Comment by wongco** [comment]
leap year party time! should be able to make it. 🎉

**Comment by Xabadu** [comment]
@wongco 🙌 

![](https://media3.giphy.com/media/kPumojumw5hvHUnqop/giphy.gif)

**Comment by amazingandyyy** [comment]
I can help and HBD 5yr!!!!!!!

**Comment by Xabadu** [comment]
@amazingandyyy 🙌 

![](https://media3.giphy.com/media/QLvRBqfLXCphu/giphy.gif)

**Comment by kevinsqi** [comment]
Happy 5 years!! Probably won't be able to make it 😭 I'll give a shout if that changes though.

**Comment by jasonsaisquoi** [comment]
My favorite Saturday of the month!
![birthdaygif](https://user-images.githubusercontent.com/13142485/74275736-4b149900-4cc9-11ea-9be3-0b371d4dc45a.gif)

**Comment by Xabadu** [comment]
@kevinsqi thanks for the heads up! We'll keep our hopes up!

@jasonsaisquoi 🙌 

![](https://media1.giphy.com/media/xUPGcCaJGCqQfMroys/giphy.gif)

**Comment by sorrelbri** [comment]
Hi! I've never mentored before, but I would like to!

**Comment by klequis** [comment]
Unlikely I can come this month but I posted this event to my Facebook coding group. Maybe get you an attendee or 2.

**Comment by Xabadu** [comment]
@sorrelbri 🙌 happy to have you join us!

![](https://media3.giphy.com/media/12rDkxhcMzb1zG/giphy.gif)

**Comment by Xabadu** [comment]
@klequis thanks, Carl! See you next time ✌️

**Comment by mariohsieh** [comment]
i can help out, will be there!

**Comment by Xabadu** [comment]
@mariohsieh 🙌 

![](https://media0.giphy.com/media/NnGGHE0muVqpO/giphy.gif)

**Comment by wongco** [comment]
have to back out. slight sports injury. see ya all next month hopefully!

**Comment by Xabadu** [comment]
@wongco thanks for letting us know! Take care of yourself, we'll see you next month!

**Comment by Xabadu** [comment]
Hey!

It's been a while since we opened this, so just a quick reminder that this is happening tomorrow!

Looking forward to seeing you all! ✌️

**Comment by Trott** [comment]
Last minute reply: I'll be there!

**Comment by Xabadu** [comment]
@Trott 🙌  😅 

![](https://media1.giphy.com/media/3o7bu0amY1NoG6zvRC/giphy.gif)

**Comment by Xabadu** [comment]
Thank you all for coming and celebrating with us! It was a great event! See you next time ✌️
