### ISSUE TITLE
Call for Speakers: NodeSchool SF online focused sessions

### ISSUE THREAD

**Issue by Xabadu** [nodeschool/sanfrancisco#290]
Hey everyone! 👋 

Since sadly we won't be hosting events anytime soon, we are looking into hosting some online focused sessions!

### When?
We're currently thinking of Saturdays at 2 PM PDT, but happy to accommodate times if necessary!

### Topics
It can be any topic we normally do for focused sessions, such as anything Node.js/JavaScript related, Web Development, etc. Any ideas you may have let us know! Happy to make it work.

### Duration
Anywhere between 60 and 180 minutes. This would be for the session itself plus some time for Q&A.

### Technical Details
We'll take care of the technical setup (and coordinate some time before to do an A/V test), streaming and moderation of the session, all we ask of you is:

- Have a functioning A/V setup in your computer (Webcam/Mic/Headphones, etc.) so you people can see you/hear you. No need for any fancy equipment though, as long as we can all hear you, you're all set!
- Make sure you can share your screen so people can follow along.

Anybody up for leading one? Let us know and what topics you have in mind! 

Looking forward to hear from all of you! ✌️

**Comment by Xabadu** [comment]
Bat Signal to our mentors! - @Trott @shiya @itsmed @bengl @anchnk @Fauntleroy @kevinsqi @ch264 @tauseefk @cantremember @creedarky @pangperry @Abimzy @Zahidul-Islam @jorgepvenegas @jasonsaisquoi @vincepmartin @wongco @amazingandyyy @mariohsieh @anchnk @klequis

**Comment by mattiaerre** [comment]
👋 @Xabadu  now that this is a remote-friendly event can I join you once again? 😊

**Comment by Xabadu** [comment]
@mattiaerre 🙌 Yeeeeeeeah! So happy to have you again with us dude!. Wanna do a session?

**Comment by samccone** [comment]
👋  happy to do a presentation on basic performance profiling for web applications!!!

I was thinking of covering content similar to this https://www.youtube.com/playlist?list=PLbBhw-Qe-7jU1DhcNdM8d2HATHAm3-7Kx but from an end-to-end perspective.

Let me know if this is interesting to y'all and let's find a time and date that works best.

**Comment by vincepmartin** [comment]
> 👋 happy to do a presentation on basic performance profiling for web applications!!!
> 
> I was thinking of covering content similar to this https://www.youtube.com/playlist?list=PLbBhw-Qe-7jU1DhcNdM8d2HATHAm3-7Kx but from an end-to-end perspective.
> 
> Let me know if this is interesting to y'all and let's find a time and date that works best.

I'd like this for sure.

**Comment by Xabadu** [comment]
Hey @samccone, hells yeah, that'd be great! We'll shoot you an email to coordinate details. Is the email address from your GitHub profile the best way to reach you?

**Comment by samccone** [comment]
Yes that email works. Thanks.

**Comment by kevinsqi** [comment]
I'd be up for doing an intro database design session. Haven't really fleshed out the details, but it could involve building a typical relational DB schema (e.g. a blog with users, posts, and comments) in a SQL shell. Could talk about one-to-many and many-to-many relationships, joins, foreign keys, etc.

**Comment by Xabadu** [comment]
@kevinsqi 🙌 that sounds great! We'll email you in a bit!

**Comment by Xabadu** [comment]
Hey @derekmartinjs, thanks for reaching out! Live events are currently on hold until it's safe, but we're always open to do virtual events and host focused sessions. Sadly, we haven't had the time or availability to prepare any content ourselves during recent times, but if anyone wants to volunteer, we're more than happy to assist with organizing and producing.

As soon as we feel confident that it's safe to have live events again (and that we can support the necessary efforts), we will though, we're really looking forward to see you all again!
