### ISSUE TITLE
Mentor Registration for April 30th, 2022 - We're back! 🎉

### ISSUE THREAD

**Issue by Xabadu** [nodeschool/sanfrancisco#294]
_is thing on? 🎤_

Heeeelloooooo 👋! Guess what! **We're coming back!** 🎊 

<img src="https://media1.giphy.com/media/huJmPXfeir5JlpPAx0/giphy.gif"/>

### Where and when?

Microsoft Reactor is hosting us on April 30th from 1pm - 5pm for our first event back!

The address is: **680 Folsom St #145, San Francisco, CA 94107** [(map)](https://www.google.com/maps/place/Microsoft+Reactor/@37.7844728,-122.4006337,17z/data=!3m2!4b1!5s0x8085807c4ad752cf:0x8cce11dc92be2213!4m5!3m4!1s0x8085807c4ac95771:0x97838fa44b46f66a!8m2!3d37.7844686!4d-122.398445) -- Comment to get involved or ask questions.

### COVID-19 Guidelines

We are working with the Microsoft Reactor folks to have a welcoming and inclusive experience for everyone, and we want you all to feel as safe as possible by following all the recommended guidelines for the venue. That means:

- We will ask for proof of vaccination for all attendees and mentors.
- Microsoft Reactor will require everyone to fill a form before entering confirming you haven't had any COVID-19 symptoms.

If you have any questions around this, please don't hesitate to ask!

### Is this your first time? No worries, we got you!

If this is your first time mentoring and you're not sure you're ready, we're sure you are! Just leave us a comment and we'll help you in any way we can.

Mentors should:
- Have already completed the [core NodeSchool workshoppers](http://nodeschool.io/#workshopper-list) before the event.
- Having also completed elective workshoppers is a great bonus.
- Review the [Mentor Best Practices](https://github.com/nodeschool/organizers/wiki/Event-Mentor-Best-Practices) wiki page.
- Arrive 30 minutes early (12:30p) so we can get set up and have our mentor meeting.

### Confirmed mentors:
- @creedarky
- @ch264
- @vincepmartin
- @Zahidul-Islam
- @cantremember
- @wongco
- You?
- You?
- You?
- You?

### Organizers:
- @tlhunter
- @Xabadu

Thanks for joining! Looking forward to seeing you all again! 🙌 

Attendee registration link:  https://www.meetup.com/sfnodeschool/events/285103512/

**Comment by Xabadu** [comment]
@Trott @shiya @Fauntleroy @kevinsqi @ch264 @tauseefk @cantremember @creedarky @pangperry @Abimzy @Zahidul-Islam @jorgepvenegas @jasonsaisquoi @vincepmartin @wongco @anchnk @klequis ⬡.js? 🍕? 👍?

Not even sure who's still around anymore 😅 but sending a massive bat signal!

**Comment by creedarky** [comment]
I'm in
![](https://media.giphy.com/media/39jLB5XJvNYlTg33u2/giphy.gif)

**Comment by ch264** [comment]
Count me in too! Looking forward to it 👩‍💻🕺

**Comment by Xabadu** [comment]
@creedarky @ch264 hell yeah, can't wait! 🙌 

<img src="https://media3.giphy.com/media/3BMtWpQEVqwNk1aNWR/giphy.gif"/>

**Comment by vincepmartin** [comment]
Oh my, It's been so long.  I can probably make it.

**Comment by Xabadu** [comment]
@vincepmartin so long indeed!

<img src="https://media0.giphy.com/media/THYfPIXGqMp3cblgkR/giphy.gif"/>

**Comment by Zahidul-Islam** [comment]
I am in :-)

**Comment by Xabadu** [comment]
@Zahidul-Islam hells yea! So good to have you with us again!

<img src="https://media1.giphy.com/media/Q9FgEwFWDMfgxtgDiv/giphy.gif"/>

**Comment by olivier-martin-sf** [comment]
I can tag along but I will probably not be around before 2 PM as my kiddo has her swimming class during lunch time.

**Comment by Xabadu** [comment]
@olivier-martin-sf awesome! no worries, join us whenever you can!

<img src="https://media2.giphy.com/media/Y1GYiLui9NHcxVKhdo/giphy.gif"/>

**Comment by tauseefk** [comment]
![](https://i.imgur.com/9umnm.gif)

**Comment by Xabadu** [comment]
@tauseefk 😱 indeed! It's been ages!

<img src="https://media0.giphy.com/media/sa5Hd8qIVK6Eo/giphy.gif"/>

**Comment by cantremember** [comment]
🤚 yeah.  i can do the 30th

is there any idea of how many non-Mentors might attend?

is there *pent up demand* for NodeSchool that must be satisfied?

**Comment by Xabadu** [comment]
@cantremember hell yeah! 🙌 

No idea tbh. I wouldn't be surprised if attendance is a bit lower on this first one back since folks might be reluctant to public gatherings, but also there's a chance a lot of people from the community moved away from the Bay during this time, can't really say for sure though. Hopefully we'll get around the same numbers as before 🤞  

<img src="https://media3.giphy.com/media/2w5fMcorvrUzw14LDZ/giphy.gif"/>

**Comment by tauseefk** [comment]
Just realized I’m gonna be at a wedding on 30th 😭

**Comment by klequis** [comment]
Wow, good to hear things are starting back-up!

I'm still avoiding indoor events. Having already had a long-covid like disease that lasted years, I'm can't stop being a little more careful than most. I am very much, perhaps even desperately, hoping things continue to cool down so I can get back to some of the stuff I love like hanging out with people who code.

Have fun!

BTW - I've been learning Haskell. If anyone is interested in that I would be happy to chat.

**Comment by Xabadu** [comment]
@tauseefk :sads: - no worries, hope to see you on the next one!

@klequis absolutely, thank you for sharing with us! We want everyone to feel as safe as possible in the events, and that also means rejoining whenever you feel comfortable. Hopefully things will keep getting better and improving. Looking forward to hanging out with you again soon when they do! (and talk Haskell!) - Are you on [our Discord](https://discord.gg/2NS3MSxZa8)? It's a bit quiet these days, but it's a good place to chat about these things!

**Comment by Trott** [comment]
I’m also in “not hanging out indoors” mode for a bit longer but I am looking forward to being able to do stuff like this again.

**Comment by vincepmartin** [comment]
Can I bring my bike inside the building?  Trying to figure out if I can ride there :)

**Comment by Xabadu** [comment]
@Trott thank you for letting us know! Hoping things get better soon so we can see you again!

@vincepmartin yeah, that shouldn't be a problem.

**Comment by Trott** [comment]
On a completely irrelevant note, every time I see @Xabadu's handle (which I imagine is pronounced "zah bah doo" but what do I know?), I think of Bubs from Homestar Runner telling Marzipan that he's trying to come up with a catch phrase for himself:

> All anybody remembers about me is how I once stole an aircraft carrier. What kinda legacy is that? So I got a list here of some catch phrase candidates. Lemme— lemme try 'em out on you, see whatcha think. "Zabbledoo!" Huh? "Zabbledoo"? I'd say it like, "Zabbledoo, Marzipan! What can I zabbledoo for you?" I think that sounds pretty good.

So I would appreciate it if someone could greet Fernando/Xabadu at this event with "Oh, hey Zabbledoo! What can I zabbledoo for you?" Thank you in advance for your anticipated fulfillment of this request.

**Comment by wongco** [comment]
should be able to make it. looking forward to seeing ya all 👍

**Comment by Xabadu** [comment]
@wongco hell yeah! Looking forward to seeing you again!

<img src="https://media4.giphy.com/media/cuW2SRA9fyZ8BGE3oV/giphy.gif"/>

**Comment by kevinsqi** [comment]
Would have liked to make it, but will be out of town that weekend. Glad it's back though @Xabadu 😄

**Comment by Xabadu** [comment]
Bummer, but hopefully next time @kevinsqi! Happy to hear from you!

**Comment by Xabadu** [comment]
Hey mentors! Looking forward to seeing you all next week. In the meantime, wanted to drop a quick announcement:

We're looking for a food sponsor for this event. If you know of a company that would be interested, do you mind letting us know or making an intro? 

Some deetz: Food costs are usually $350~ish (could be less/more depending on numbers, I think it might be less for this one) for the event and we would add a slide into our presentation with the name/logo of the company, plus social media shoutouts and sharing some info with our attendees (or alternatively have someone from the company joining us that day to share some info, if they're hiring, etc.)

Any help is appreciated, thanks! ✌️

**Comment by olivier-martin-sf** [comment]
Oups it happens that I won't be in SF next Saturday, last-minute changes sorry about that. I won't be able to make it this time

**Comment by Xabadu** [comment]
@olivier-martin-sf bummer! no worries, thanks for letting us know. See you next time!

**Comment by Xabadu** [comment]
Hey folks! 👋 

Just a quick reminder that this is happening tomorrow! Can't wait to see everyone.

Please remember to bring proof of vaccination. The folks at the Reactor will ask for it and id at the entrance when checking everybody in.

If you have any questions or need anything, let us know. See you tomorrow!

**Comment by vincepmartin** [comment]
Sorry everyone, have to back out today.  I will try my best to make it next time though!  I hope everyone has fun on their first gathering!
