### ISSUE TITLE
Mentor Registration for May 21st, 2022

### ISSUE THREAD

**Issue by Xabadu** [nodeschool/sanfrancisco#297]
Heeeelloooooo 👋!  

It's time for our May(n) event! Apologies folks for the late start on this month's organizing, but have been sick for the past couple of weeks 💔 

<img src="https://media4.giphy.com/media/456FaSxPsjUBUQMgaZ/giphy.gif"/>

### Where and when?

Microsoft Reactor is hosting us on May 21st from 1pm - 5pm

The address is: **680 Folsom St #145, San Francisco, CA 94107** [(map)](https://www.google.com/maps/place/Microsoft+Reactor/@37.7844728,-122.4006337,17z/data=!3m2!4b1!5s0x8085807c4ad752cf:0x8cce11dc92be2213!4m5!3m4!1s0x8085807c4ac95771:0x97838fa44b46f66a!8m2!3d37.7844686!4d-122.398445) -- Comment to get involved or ask questions.

### COVID-19 Guidelines

We are working with the Microsoft Reactor folks to have a welcoming and inclusive experience for everyone, and we want you all to feel as safe as possible by following all the recommended guidelines for the venue. That means:

- We will ask for proof of vaccination for all attendees and mentors.
- Microsoft Reactor will require everyone to fill a form before entering confirming you haven't had any COVID-19 symptoms.

If you have any questions around this, please don't hesitate to ask!

### Is this your first time? No worries, we got you!

If this is your first time mentoring and you're not sure you're ready, we're sure you are! Just leave us a comment and we'll help you in any way we can.

Mentors should:
- Have already completed the [core NodeSchool workshoppers](http://nodeschool.io/#workshopper-list) before the event.
- Having also completed elective workshoppers is a great bonus.
- Review the [Mentor Best Practices](https://github.com/nodeschool/organizers/wiki/Event-Mentor-Best-Practices) wiki page.
- Arrive 30 minutes early (12:30p) so we can get set up and have our mentor meeting.

### Confirmed mentors:
- @vincepmartin
- @ch264
- @Zahidul-Islam
- @creedarky
- @kevinsqi
- @tauseefk
- @Fauntleroy
- You?
- You?
- You?

### Organizers:
- @tlhunter
- @Xabadu

Thanks for joining! Looking forward to seeing you all! 🙌 

Attendee registration link:  https://www.meetup.com/sfnodeschool/events/285872034/

**Comment by Xabadu** [comment]
@shiya @Fauntleroy @kevinsqi @ch264 @tauseefk @cantremember @creedarky @pangperry @Abimzy @Zahidul-Islam @jorgepvenegas @seraficaj @sorrelbri @vincepmartin @wongco @dkim1116 @anchnk  ⬡.js? 🍕? 👍?

**Comment by vincepmartin** [comment]
I'm going to try my best to actually make it this time lol :)

**Comment by ch264** [comment]
I am in 🙌

**Comment by Zahidul-Islam** [comment]
Count me in...

**Comment by seraficaj** [comment]
I can't make it 😭, but that clearly means I have to sign up for next time!

**Comment by creedarky** [comment]
I'll be there!

**Comment by Xabadu** [comment]
@vincepmartin @ch264 @Zahidul-Islam @creedarky hell yeah!

<img src="https://media2.giphy.com/media/LbemIUGkYgeqY/giphy.gif"/>

**Comment by pangperry** [comment]
i'm looking forward to joining again once covid vaccines are available for
my little guy (3 yr old), but really happy to see nodeschool is back :)

**Comment by kevinsqi** [comment]
I'll be able to join!

**Comment by Xabadu** [comment]
@kevinsqi @tauseefk awesome! looking forward to seeing you again! ✌️ 

<img src="https://media1.giphy.com/media/UzuKOSuYZwrjG/giphy.gif"/>

**Comment by olivier-martin-sf** [comment]
I will be alone with the kiddo so can't make it this time either! Hopefully next month

**Comment by Fauntleroy** [comment]
I will be there tomorrow

**Comment by Xabadu** [comment]
Hey folks! 👋

Just a quick reminder that this is happening tomorrow! Looking forward to see y'all.

Please remember to bring proof of vaccination. The folks at the Reactor will ask for it and id at the entrance when checking everybody in.

If you have any questions or need anything, let us know. See you tomorrow!

**Comment by Xabadu** [comment]
Thank you for coming and helping out yesterday, it was great event! See you next month!
