### ISSUE TITLE
Logo / sticker fun

### ISSUE THREAD

**Issue by jedireza** [nodeschool/sanfrancisco#3]
Let's share some ideas about logo/sticker colors.

You can create them in the browser here:
http://www.finnpauls.de/nodeschool-stickerify/

**Comment by jedireza** [comment]
I used `S*F` as the text but we could use `SFO` or a space in between `S F`. I had to convert these to `png`s to show here... but I have the `svg`s.

![sf-node-01](https://cloud.githubusercontent.com/assets/979929/5684465/7a54b996-97e5-11e4-83e8-396f99dfce32.png)
![sf-node-02](https://cloud.githubusercontent.com/assets/979929/5684469/7a5937f0-97e5-11e4-8c8d-b26d62fcf31a.png)
![sf-node-03](https://cloud.githubusercontent.com/assets/979929/5684466/7a54cf80-97e5-11e4-9b2d-4699e6a3689d.png)
![sf-node-04](https://cloud.githubusercontent.com/assets/979929/5684468/7a58af74-97e5-11e4-81cb-02ee11e770cb.png)
![sf-node-05](https://cloud.githubusercontent.com/assets/979929/5684467/7a561f70-97e5-11e4-833c-d02cd58133af.png)

**Comment by maxogden** [comment]
some vector wizard should put in the transamerica pyramid, full house houses and the ggb

**Comment by emkay** [comment]
+1 for full house houses. @jedireza this is a great idea, totally stealing this for NodeSchool LA

**Comment by jedireza** [comment]
+1 for a transamerica building. The [Painted ladies](http://en.wikipedia.org/wiki/Painted_ladies) may take up the whole sticker though.

**Comment by jasonrhodes** [comment]
full house houses or why bother

**Comment by jedireza** [comment]
I just saw the NodeSchool Hamburg logo, it all makes sense now. Anyone know a vector artist that could help us out? Maybe @oleharland could help :wink: :heart: 

https://github.com/nodeschool/hamburg/issues/9

**Comment by oleharland** [comment]
Hello, what are youre exactly thoughts? Maybe something with the Golden Gate?

**Comment by jedireza** [comment]
Hear a designers point of view would be much appreciated. So far the ideas have included:

 - using the [Transamerica Pyramid](http://en.wikipedia.org/wiki/Transamerica_Pyramid)
 - the full house houses, also called the [Painted ladies](http://en.wikipedia.org/wiki/Painted_ladies)
 - and the Golden Gate Bridge

With the amount of space in the hexagon and keeping line thickness in mind... the artwork should probably use few lines to communicate the subject. I think the Hamburg logo was executed perfectly.

**Comment by llkats** [comment]
I was playing a bit with a concept involving my personal favorite SF landmark: Sutro Tower!

![nodeschool-logo-sutro](https://cloud.githubusercontent.com/assets/578156/5697972/32626d32-99b5-11e4-8faf-32c54dedd7aa.png)

I was imagining that the Nodeschool text would run vertically on the left, and SF text on the right, with some more outlined embellishments like the original logos.

I really liked the orange-on-gray concept logo, so that's what I ran with. Though, of course, we don't need to limit ourselves to just one color option. Or even just one logo! I really like stickers, so the more, the merrier. :)

**Comment by jedireza** [comment]
Cool idea with Sutro Tower.

 > Though, of course, we don't need to limit ourselves to just one color option. Or even just one logo! I really like stickers, so the more, the merrier. :)

:+1: Agreed

**Comment by RichardLitt** [comment]
:+1: I like the tower. Different colors is cool, but I think the gray on orange is good. Remember, this will permanently be on all of our laptops people.

**Comment by RichardLitt** [comment]
The bridge might be something else we can claim.

**Comment by bengl** [comment]
Should we Stickermule the first one in this thread, given that it's on the website now?

**Comment by RichardLitt** [comment]
I'd prefer if we went for the Sutro Tower one, as it is cleaner and doesn't have as much detail and is more recognizably SF from a distance.

**Comment by jedireza** [comment]
I like the Sutro Tower design concept, but the artwork is incomplete at the moment right?

**Comment by RichardLitt** [comment]
To be honest, I'm a minimalist, and I think it's perfect as it is.

**Comment by llkats** [comment]
Personally, I'd love if someone finessed the Sutro design a bit. I don't think it's exactly symmetrical, the line-widths don't really match, and I'm not wild about such rounded ends on the lines. I'd also at least like to see some sort of Nodeschool SF text. Anyone have a designy/vectory artist friend who could lend a hand? I created it in Pixelmator and can provide that original file, such as it is. :)

We could also just print the first logo so as to maybe have something in time for the event and look at the Sutro design for a second run.

**Comment by jedireza** [comment]
As of today, if we ordered stickers we'd need to pay $29 for 2 day shipping so we'd get them before the 7th. I think we should do it. I'd like to give the attendees a sticker. Let's use the logo that's on the website for the first run. Thoughts?

**Comment by llkats** [comment]
Definitely go for it! I can send you a monetary donation to cover the cost
:)

**Comment by jedireza** [comment]
Cool. The order has been placed.

**Comment by RichardLitt** [comment]
:+1:

On Thu, Jan 29, 2015 at 9:16 AM, Reza Akhavan <notifications@github.com>
wrote:

> As of today, if we ordered stickers we'd need to pay $29 for 2 day
> shipping so we'd get them before the 7th. I think we should do it. I'd like
> to give the attendees a sticker. Let's use the logo that's on the website
> for the first run. Thoughts?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nodeschool/sanfrancisco/issues/3#issuecomment-72064596>
> .
>



-- 
Richard | @richlitt <https://twitter.com/richlitt> | burntfen.com
<http://www.burntfen.com>

**Comment by jedireza** [comment]
Closing for now. If you know any artists please send them to this thread. I'd love to get a unique sticker logo for NodeSchool SF.
