### ISSUE TITLE
When and where should we have the next event?

### ISSUE THREAD

**Issue by jedireza** [nodeschool/sanfrancisco#41]
At the last event some people said a monthly event was a reasonable goal. Should we shoot for round 2 in March?

**Comment by RichardLitt** [comment]
:+1:

**Comment by Trott** [comment]
![YASSSSSSS!!!!!](http://i.imgur.com/JKTF9GJ.gif)

**Comment by Trott** [comment]
Maybe set up a corresponding Meetup group? I think it costs a small amount, but I'd be willing to kick in a few $ in exchange for merging that one outstanding pull request on the website.

**Comment by RichardLitt** [comment]
You're ridiculous. 

What is normal for NodeSchools? Do they usually use MeetUps?

**Comment by Trott** [comment]
What's the point of having a kid if you can't make animated GIFs of them?

**Comment by jedireza** [comment]
Are we missing some functionality by only using GitHub?

**Comment by RichardLitt** [comment]
I meant the PR. I figured that was your kid, though. Cool. :dromedary_camel:

**Comment by Trott** [comment]
meetup.com probably has more visibility. Then again, we didn't exactly have a turnout problem, so yeah, you're probably right, let's not fix what isn't broken.

**Comment by bengl** [comment]
:+1: on monthly. As I was mentioning at the event, I'd expect some people to come back to learn more, if they really enjoyed it and got a lot out of it.

**Comment by llkats** [comment]
GitHub is super generous and has a community space; I can talk to my friends there and see if they can hook us up. As for dates, I am leaning more towards mid- to late-March, though I suppose it will depend upon a space's potential availability.

**Comment by jedireza** [comment]
:boom: Great idea. I love their office. Let's see when and if it's available.

**Comment by jedireza** [comment]
:pager:

**Comment by lizTheDeveloper** [comment]
Heyo- We could also host an event at Tradecraft, which is at 855 Front Street, right near the Exploratorium. Let me know if this would help. We could probably fit 60-80 people in a workshop. I'd love to come help mentor as well :smile:

**Comment by jedireza** [comment]
@lizTheDeveloper thanks so much. @llkats should we wait to hear back from GitHub?

What are everyone's thoughts on Saturday March 14th or 28th?

**Comment by Trott** [comment]
I can do the 28th but possibly not the 14th, so I guess I prefer that.

**Comment by RichardLitt** [comment]
I can't do the 28th, but should be able to do the 14th.

**Comment by llkats** [comment]
I dropped the ball and haven't even asked GitHub yet. Sorry! Let's check out Tradecraft, if the dates work for @lizTheDeveloper. (Thanks, Liz!) My Saturdays are all open in March so far, with an personal arbitrary preference for the 28th.... is the 21st out?

**Comment by jedireza** [comment]
Yeah I can't make it on the 21st, but don't let that stop everyone from choosing the 21st. First though, let's see when Tradecraft might be available for us.

**Comment by paulgrock** [comment]
I can't make the 28th but am open any of the other proposed dates.

**Comment by lizTheDeveloper** [comment]
Sorry super slow in response, I'll have an answer on that today, do we want the 21st or the 28th? Or should I clear both and then we can decide?

**Comment by jedireza** [comment]
28th for me pwease

**Comment by llkats** [comment]
28th for me toooo

**Comment by lizTheDeveloper** [comment]
Events team says the day is clear, what kind of stuff do we need? Internet obviously, but space / tables for how many? Also, food? We'll have some mentors attending as well :)

**Comment by lizTheDeveloper** [comment]
Oh also, don't announce juuuust yet, I'll let you know as soon as it's cool

**Comment by jedireza** [comment]
Good to hear! :grin: We started with a 5:1 ratio between attendees and mentors and I think it yields a good balance. I see you mentioned the space will hold 60-80 people. I think a maximum of 40 attendees is good. We'd need 8 mentors with a group that size. I'm sure there will be another handful of people helping besides mentors too. So we'd be just under 55 people total. That seems decent to me. Could anyone else share thoughts on those numbers?

Resources we'll need:

 - Internets of the wireless type
 - Power outlets
 - Tables and chairs (2 or more people per table)
 - I like healthy snacks and beverages but I'm open to what the crowd prefers

@lizTheDeveloper some questions

 - Could you post a photo of the space so we can get a mental picture?
 - Have the Tradecraft mentors committed to completing (or have already completed) the [core NodeSchool workshoppers](http://nodeschool.io/#workshopper-list)? Having also completed elective workshoppers is a great bonus.
 - How many Tradecraft mentors do you think will be attending?

I'm probably forgetting stuff. Again, thanks so much. :+1: :sparkles: :fireworks:

**Comment by Trott** [comment]
I think your numbers are spot on, @jedireza.

**Comment by jedireza** [comment]
@lizTheDeveloper could you confirm the address? I found this one online:
855 Front St San Francisco, CA 94111

Oh yeah. What time of day? The last event was from 1pm to 5pm. I thought that worked well. Would anyone else be willing to comment on that?

**Comment by atav32** [comment]
The 28th sounds good to me. I'd prefer afternoon or evening if possible. Really excited to meet all of you =D

**Comment by TheAlphaNerd** [comment]
I'd be open to helping with everything on the 28th.  

Just a heads up that dancejs was planning it's next event on the 28th --> https://github.com/dancejs/Oakland/issues/15

There really isn't any conflict if people are going to this earlier... i kind of like the idea of treating dance.js as the after party if people are open to that.  It will be hosted at @mikeal roger's new space in oakland

**Comment by jedireza** [comment]
@atav32 awesome same for us.

@TheAlphaNerd thanks you. We'll happily take you up on the offer. Dance.js as an after party is a great idea. :speaker: :dancer: :runner: :speaker:

**Comment by lizTheDeveloper** [comment]
Hey all, address is 855 Front Street 94111. 1-5 PM would be fine for us. We can provide drinks and snacks for 55 people easy. We have wireless fine too, but for 40 people using it all at once in the same room can be slow (unless we spread throughout the building, which is totally doable, there are many workspaces).

I can mentor, as well as the other track lead. I'll round up the students who have that day and get you a better count on that. We'll probably have *at least* two students who can mentor, but maybe more. 
@jedireza Thanks for organizing this! Also, when should we show up, are there "talks" or just "show up and do the workshops, there will be helpers here".

Also "Healthy Snacks" to me means KIND bars and Fruit (it's what we use at Girl Develop It events), and "beverages" means water bottles and drip coffee. Does that sound cool or???

Dance.js sounds awesome, def dropping by that afterwards

**Comment by jedireza** [comment]
Ok great.

> ...unless we spread throughout the building, which is totally doable, there are many workspaces...

The internet usage shouldn't be too excessive, mostly just download the workshoppers in the beginning. It's probably best to keep everyone in one general area instead of broken apart.

> Also, when should we show up, are there "talks" or just "show up and do the workshops, there will be helpers here".

Organizers and helpers can show up to prep about 20-30 minutes before. There aren't any formal talks. We do a light intro/announcement about how to use the workshoppers and talk about expectations in regard to the Code of Conduct. After that we break into groups (or pairs) of people working on the same workshoppers. This helps people help each other. The mentors generally float around and help anyone who needs it.

> Also "Healthy Snacks" to me means KIND bars and Fruit (it's what we use at Girl Develop It events), and "beverages" means water bottles and drip coffee. Does that sound cool or???

Works for me.

- - - - - -

@lizTheDeveloper can we start spread the word? :grin:

**Comment by lizTheDeveloper** [comment]
Just got word, go ahead and announce! Thanks!

**Comment by jedireza** [comment]
:boom: we're all set. I'll try get the registration setup and tweet it out this evening or tomorrow. Thanks again.

**Comment by jedireza** [comment]
Registration is open. The Tweet just went out. Spread the word.
https://ti.to/nodeschoolsf/march-28th-2015

**Comment by TheAlphaNerd** [comment]
Should people wanting to mentor purchase a ticket?  Also curious about where the proceeds go... I tried doing a quick grep and didn't come up with anything

**Comment by jedireza** [comment]
Nope, mentors should not register. I connected the Ti.to registration to a Stripe account I setup personally. The intended use of the funds is for stickers and snacks.

**Comment by TheAlphaNerd** [comment]
Wonderful.  I don't know how anyone expects to program JavaScript without stickers!

Is there an official sign up for mentors?

**Comment by jedireza** [comment]
Just created the issue for mentor signup :grin: 
https://github.com/nodeschool/sanfrancisco/issues/50

@lizTheDeveloper, would you be willing to share that link with the Tradecraft mentors?

**Comment by Trott** [comment]
@jedireza Did you add the event at https://docs.google.com/forms/d/1vYW-Yw82kt_q7WDgBY6gQqFrg3zuD2rDPXEG-cbq7e4/viewform so it (eventually?) shows up on the main NodeSchool events page? If so, I won't send a duplicate event. (Although I suppose there's probably no harm in that...)

**Comment by jedireza** [comment]
@Trott Thanks for the reminder, I just submitted it. :100:
