### ISSUE TITLE
NodeSchool at NodeSummit

### ISSUE THREAD

**Issue by CrabDude** [nodeschool/sanfrancisco#43]
# NodeSchool: NodeSummit 2015

[![NodeSchool logo](http://nodeschool.io/images/schoolhouse.svg)](http://nodeschool.io)

[![BayNode logo](http://i.imgur.com/DOjeQ2Z.jpg)](http://meetup.com/BayNode)

[![Noderiety logo](http://i.imgur.com/Ejm1fT0.png)](http://noderiety.com)

[nodeschool.io](http://nodeschool.io/) is a community driven, open source educational software that teaches various node.js and JavaScript skills in an interactive, self-guided format.

**Beginner**

* 09:00 - [Node.js primer](http://courseware.codeschool.com/node_slides.pdf)
* 09:30 - [javascripting](https://github.com/sethvincent/javascripting) & [count-to-6](https://github.com/domenic/count-to-6)
* 10:20 - [learnyounode](https://github.com/rvagg/learnyounode)
* 11:10 - [async-you](https://github.com/bulkan/async-you) or [promise-it-wont-hurt](https://github.com/stevekane/promise-it-wont-hurt)

** Don't have node.js installed yet? All the Beginner Track workshoppers are on [CodeFresh](http://codefresh.io/labs)!

**Advanced**

* 09:00 - [functional-javascript-workshop](https://github.com/timoxley/functional-javascript-workshop)
* 10:00 - [expressworks](https://github.com/azat-co/expressworks) or [kick-off-koa](https://github.com/koajs/kick-off-koa) or [makemehapi](https://github.com/hapijs/makemehapi)
* 11:00 - [stream-adventure](https://github.com/substack/stream-adventure)

**Non-web**

* 09:00 - [bug-clinic](https://github.com/othiym23/bug-clinic)
* 10:00 - [bytewiser](https://github.com/maxogden/bytewiser)
* 11:00 - [goingnative](https://github.com/rvagg/goingnative)

**Thanks Mentors!**

Ross Kukulinksi, Yodlr & BayNode
Tony Pujals, BayNode
Luca Maraschi, Joyent
Jacob Chapel, WalmartLabs
Mikeal Rogers, DigitalOcean
Meadhbh Hamrick
Oleg Polyakov, AQI
Poornima Venkat, PayPal
Richard Littauer, MIT Media Lab
Reza Akhavan, Yahoo!
Rich Trott, UCSF

**Comment by Trott** [comment]
We can probably close this now, yeah?
