### ISSUE TITLE
solicit feedback

### ISSUE THREAD

**Issue by llkats** [nodeschool/sanfrancisco#44]
I'd like to gather feedback from attendees. This would require two things: a mechanism to collect feedback, and messaging on the homepage (possibly twitter, etc.) to solicit information.

I think GitHub Issues would be a fine way to collect feedback, though maybe people think a Google Form might be more suitable? Or we could lean on GitHub Issues and designate an email address for feedback anyone feels the need to give anonymously. I prefer organizing in the open, but as always, people might be more comfortable with a form or email.

Thoughts pls :smiley: :pray: :bow: :wave: :dancers:

**Comment by jedireza** [comment]
+1 - How about a combo:

 - Let's post an issue on GitHub "Feedback for February 7th Workshop" - This can be our public forum for anyone interested.
 - Send a simple rating style survey (via anonymous Google Form) that is easy to fill out.

And we can even post the aggregate results from the survey back to the GitHub thread.

I'm happy to setup the Google Form and email the attendees. What questions and types of responses do we want?

I'd also like to get a list from @agminusthev or @groundwater of those who made it and those who didn't. Maybe we send a different email if they weren't able to make it.

:sparkles::metal::sparkles:

**Comment by RichardLitt** [comment]
I would not solicit feedback in a way that discourages anonymity, if even by a preference for a particular venue. I don't know of any negative feedback, but we've got to make a safe space for people to air it. I'm worried that posting aggregate results back may cause this. I think that the results of the survey should stay with the organisors, and those should be a select, well-defined team of people, not an amorphous 'I've contributed on GitHub' team. Make sense?

**Comment by RichardLitt** [comment]
Not that I mean to rain on the parade, guys! :)

**Comment by jedireza** [comment]
:pager:

**Comment by RichardLitt** [comment]
I'm still waiting for your response, haha. :)

**Comment by jedireza** [comment]
> I prefer organizing in the open, but as always, people might be more comfortable with a form or email.

I think @llkats said it best and I tend to agree. Let's try to keep it simple for now. I've created #47 to get things moving.

> I would not solicit feedback in a way that discourages anonymity, if even by a preference for a particular venue. I don't know of any negative feedback, but we've got to make a safe space for people to air it. I'm worried that posting aggregate results back may cause this.

I agree, we don't want to discourage anonymity. In the spirit of keeping things simple, let's skip the survey for now. I mentioned that people can email us directly for private help/feedback.

**Comment by RichardLitt** [comment]
I think you did good.

**Comment by llkats** [comment]
Ack sorry, I went abruptly offline for the past few days for a little vacation and some much-needed headspace. Thanks for taking care of this, @jedireza, I'm glad you went ahead and sent the email. I think it's perfect. :+1: :+1: :+1:

**Comment by jedireza** [comment]
:v: All is good. Closing this.
