### ISSUE TITLE
International day - Saturday May 23rd, 1-5p

### ISSUE THREAD

**Issue by jedireza** [nodeschool/sanfrancisco#46]
International Day is May 23rd, 2015

http://nodeschool.io/international-day/

**Comment by TheAlphaNerd** [comment]
I'd love to help with this!

**Comment by jedireza** [comment]
The 23rd of May lands on a Saturday. We should start by trying to find a venue.

**Comment by paulgrock** [comment]
We could probably do it at Blizzard. How many people do you think we'll have?

**Comment by jedireza** [comment]
Sweet. I've never been to the Blizzard office. How many people do you think it'll comfortably hold?

**Comment by paulgrock** [comment]
Maybe 60?

**Comment by jedireza** [comment]
Nice. If we stick with the 5:1 mentor attendee ratio and max out at 40 attendees, we'd need 8 mentors and probably a handful of other people helping out... that would put us just under 55 people.

**Comment by paulgrock** [comment]
Just checked on this and Blizzard is happy to host the event (and get some food/snacks) as long as people sign NDAs. Is that cool?

**Comment by jedireza** [comment]
That's great that Blizzard is willing to host us. If the NDA thing isn't a joke, I'm not sure I'd like to make that part of the experience for attendees. Is there a lot of sensitive information in the area we'd congregate?

**Comment by paulgrock** [comment]
Yeah the NDA thing isn't a joke. Blizzard is pretty paranoid about security. Let me ask around on Monday and see if we can have this event without people signing NDAs. There isn't much/any sensitive info in the main area so that might make it an easier sell.

**Comment by paulgrock** [comment]
Just heard back from security/legal and they're good with us running this event with no NDA.

**Comment by jedireza** [comment]
:guitar: rock and roll!! Blizzard it is :grin:

**Comment by jedireza** [comment]
@paulgrock should we stick with our usual time of 1p - 5p?

**Comment by paulgrock** [comment]
Might as well

**Comment by cantremember** [comment]
i would be happy to volunteer for Mentorship

**Comment by jedireza** [comment]
Thanks @cantremember. We'll be sure to ping you when we post a mentor registration thread.

**Comment by llkats** [comment]
Registered in the thread! https://github.com/nodeschool/international-day/issues/8#issuecomment-92577370

**Comment by Trott** [comment]
@llkats I'm in for mentoring on International Day.

**Comment by llkats** [comment]
Woo it's over!!!
