### ISSUE TITLE
Feedback for the February 7th 2015 workshop

### ISSUE THREAD

**Issue by jedireza** [nodeschool/sanfrancisco#47]
We'd love to hear what experiences you thought were good and what you think could be better. We prefer to organize and collaborate in the open and when you need to reach us privately you can always send emails to nodeschoolsf@gmail.com.

Okay.... go :runner:

**Comment by marcora** [comment]
Great event... fantastic location, relaxed atmosphere and helpful people! I have learned quite a bit about Node.js :+1:

**Comment by llkats** [comment]
:rainbow: :rainbow: :fireworks: :goat: :sheep: :+1: :star2: :raised_hands: :rainbow: :rainbow:

**Comment by karishay** [comment]
:+1: :rainbow: 

Very informative and enjoyable. Thanks for putting it on!

**Comment by duquet** [comment]
Really great experience in so many ways from super helpful mentors, fantastic fellow students and amazing space and hosts. It really felt like a fantastic experience that I would love to repeat and am super proud to be a part of. Learned tons and enjoyed every minute.

**Comment by jseiden** [comment]
I didn't know what to expect but was really pleased. The mentors were helpful and everyone got to go at their own place. Good vibes all around.  I look forward to future events.

**Comment by jedireza** [comment]
:fireworks:
