### ISSUE TITLE
Mentor registration for March 28th 2015

### ISSUE THREAD

**Issue by jedireza** [nodeschool/sanfrancisco#50]
Tradecraft is hosting us on March 28th from 1pm - 5pm. The address is: 855 Front Street 94111

We like to keep a 5:1 attendee:mentor ratio. We're accepting 40 attendees for this workshop. So we'll need 8 mentors.

Mentors should commit to completing (or have already completed) the [core NodeSchool workshoppers](http://nodeschool.io/#workshopper-list) before the event. Having also completed elective workshoppers is a great bonus.

Comment to get involved or ask questions.

- - - - - -

Confirmed mentors:

 - [x] @TheAlphaNerd 
 - [x] @Trott 
 - [x] @bengl
 - [x] @LizTheDeveloper
 - [x] @Rolken
 - [x] @MrBri
 - [x] @brianleroux
 - [x] @Yonet
 - [x] @100ideas

Organizers and helpers:

 - [x] @jedireza
 - [x] @llkats
 - [ ] @duquet

**Comment by TheAlphaNerd** [comment]
**raises hand**

**Comment by jedireza** [comment]
Thanks @TheAlphaNerd, I look forward to seeing you there.

**Comment by llkats** [comment]
:dancer:

**Comment by Trott** [comment]
In!

**Comment by jedireza** [comment]
:+1: thanks @Trott

**Comment by bengl** [comment]
in :heavy_check_mark:

**Comment by jedireza** [comment]
:+1: thanks @bengl

**Comment by lizTheDeveloper** [comment]
I'l be there, also @Rolken will be there.

**Comment by jedireza** [comment]
:tada: Very cool. Thanks @lizTheDeveloper and @Rolken.

**Comment by MrBri** [comment]
I'm interest in mentoring or at least getting my Node nerdiness on. :neckbeard:

**Comment by jedireza** [comment]
:sparkles: Glad to hear it! Thanks @MrBri :sparkles:

**Comment by brianleroux** [comment]
o/

**Comment by jedireza** [comment]
Thanks @brianleroux :beers:

**Comment by Yonet** [comment]
I can help out

**Comment by 100ideas** [comment]
I'd like to help out as a mentor as well. I have run through the core workshoppers and a couple of the electives. Hey @TheAlphaNerd maybe we can go together... :boat:

**Comment by jedireza** [comment]
Thanks @Yonet :shipit:

**Comment by jedireza** [comment]
@100ideas thanks so much for volunteering to be a mentor. Our goal is one to do one workshop per month, so we'll be sure to ping you again. Also International day is coming up, checkout #46 for details.

**Comment by jedireza** [comment]
@100ideas I've added you to the mentor list for this Saturday if you're able to make it.

**Comment by TheAlphaNerd** [comment]
@100ideas fancy seeing you here!  Perhaps we could grab breakfast before.

**Comment by lizTheDeveloper** [comment]
FYI we're here and set up. The building has a law office plaque on the outside, it says MBV Law, but it's the right building.

**Comment by lizTheDeveloper** [comment]
Also if anyone gets lost or needs anything, you can get my phone at 415-851-9394 (phone number goes away after the event)

**Comment by TheAlphaNerd** [comment]
I can't recall I'd there is food or not. should I pick something up first?

**Comment by jedireza** [comment]
We can order some food.
