### ISSUE TITLE
NodeSchool SF - Saturday March 28th, 1-5p

### ISSUE THREAD

**Issue by jedireza** [nodeschool/sanfrancisco#51]
Tradecraft is hosting us on March 28th from 1pm - 5pm. The address is:

855 Front Street
San Francisco, 94111

Attendees may register here: https://ti.to/nodeschoolsf/march-28th-2015
Mentors may register here: https://github.com/nodeschool/sanfrancisco/issues/50

**Comment by jedireza** [comment]
I almost forgot to mention...

:speaker: Dance.js :speaker: https://github.com/dancejs/Oakland/issues/15
is also happening on March 28th. It could be your afterparty :wink:

**Comment by fokusfocus** [comment]
Hi jedireza,

I'm signed up to attend the NodeSchoolSF tomorrow. This will be my first time attending. Do you have any prerequisites that I need to do before attending?

**Comment by TheAlphaNerd** [comment]
@100ideas fancy seeing you here!  Perhaps we could grab breakfast before.

**Comment by jedireza** [comment]
@fokusfocus nope. It's a relaxed environment. If you'd like to get a head start you could always checkout http://nodeschool.io/#workshopper-list

**Comment by Marlena** [comment]
It bums me out but I can't make it today.  Is there a way for me to donate my ticket to someone else?  If there is not a waitlist, I can email the members list at Double Union, the feminist hacker space and see if someone wants my ticket. 

Hope there's another nodeschool soon!

**Comment by jedireza** [comment]
@Marlena yeah that is a bummer you can't make it today. Transferring your ticket is fine, we can also refund it. I know it's short notice, but if you do transfer it please [email me](mailto:jedireza@gmail.com) the person's email. Our goal is one workshop per month so... see you at the next workshop. :wink:

**Comment by lizTheDeveloper** [comment]
If anyone has questions about getting here or the space you can get me at 415-851-9394 (phone number expires after the event)
