### ISSUE TITLE
Feedback for the March 28th 2015 workshop

### ISSUE THREAD

**Issue by jedireza** [nodeschool/sanfrancisco#55]
We'd love to hear what experiences you thought were good and what you think could be better. We prefer to organize and collaborate in the open and when you need to reach us privately you can always send emails to nodeschoolsf@gmail.com.

Okay.... go :dancer:

**Comment by SilverEzhik** [comment]
When will photos be posted?

**Comment by jedireza** [comment]
@SilverEzhik I should have the group photo up by Sunday :wink:

**Comment by padma-vemuri** [comment]
I think, we should have for event for more than 4 hours?

**Comment by jedireza** [comment]
@padma-vemuri thanks for sharing :pray:

**Comment by jedireza** [comment]
:tada: The group photo is up on the site now. Apologies that it's slightly out of focus.

I'm really enjoying these workshops. You all are amazing people and it's such a pleasure to meet and hangout with everyone.

**Comment by llkats** [comment]
100% in agreement. Hopefully we have a date for the next workshop soon, because I can't wait! C'monnnnnn @github, get back to us!!

**Comment by jwrobes** [comment]
I thought it was a great start.  I totally felt like there was a wealth of knowledge there to tap into, and am looking forward to doing some more of the tutorials on my own and coming in armed with questions for the next one.  One thing that might be interesting, is finding a way to encourage and team up with others who are starting out to keep each other motivated in the learning process.  I think that talking through some of the more challenging concepts, like streams and callbacks, is the best way to really understand them, and that this is just the place to do it.

**Comment by jedireza** [comment]
@jwrobes thanks for sharing :+1: 

Do you think we could do better at surveying what different areas of focus people have before we dive into the workshops?
