### ISSUE TITLE
When and where for the April workshop?

### ISSUE THREAD

**Issue by jedireza** [nodeschool/sanfrancisco#56]
Tradecraft was a great location and @LizTheDeveloper mentioned that they'd be happy to have us again. It's also fun to see new locations so if you know of a place please share in the discussion.

Just like before, we need to choose a date, time and location. :rainbow:

**Comment by llkats** [comment]
Apparently I accidentally unwatched this repo! :anguished: Will be getting emails again now, whoops!

I'm requesting use of GitHub's community space, let's see what they say!

**Comment by jedireza** [comment]
:octocat: `===` :+1:;

**Comment by TheAlphaNerd** [comment]
It is definitely worth pinging @skalnik or someone else we know at github.  Having a sponsor will make this process go extremely quickly.

**Comment by llkats** [comment]
@TheAlphaNerd: one step ahead of you :wink:

**Comment by TheAlphaNerd** [comment]
udabaste :D

**Comment by LizzHale** [comment]
Any update on a date for the April workshop?

**Comment by skalnik** [comment]
The issue on our end is finding someone to be around during the event :sob: I don't think GitHub will be able to host

**Comment by TheAlphaNerd** [comment]
boourns.  @skalnik is anyone at GH able to be around or does it have to be specific people?  Is this issue that it is on a weekend?

**Comment by skalnik** [comment]
> boourns. @skalnik is anyone at GH able to be around or does it have to be specific people? Is this issue that it is on a weekend?

I think its anyone, however not sure who else to ping. If you have suggestions, let me know!

My conflicts are weekend and travel related :(

**Comment by jedireza** [comment]
I think we should shoot for an event on the 25th since it's the last Saturday of the month. Hopfully we can find a venue by this weekend and start promoting. If :octocat: doesn't workout this month let's shoot for having it there in June.

BTW you're all awesome :fireworks: :heart:

**Comment by TheAlphaNerd** [comment]
So fwiw this is the same weekend that nodebots is planning its meet up.  While the over lap could be viewed as a problem, it could actually be a blessing as nodebots is also looking for a location at the moment.  Perhaps we could run back to back events in the same space.

**Comment by jedireza** [comment]
I'd be down for that. It may be heavy on the venue depending on their resources.

**Comment by TheAlphaNerd** [comment]
@bryan-m-hughes thoughts ^^^

**Comment by bryan-m-hughes** [comment]
I like the idea of back to back, and if we could do the same venue that would be awesome! @jedireza does bring up a good point though. We shouldn't wed ourselves to the idea of using the same space.

FWIW I had reached out to PubNub, but they aren't able to host that weekend.

As far as who gets what day, I'm only available on Sunday, so I'm perfectly happy with Node school taking Saturday and NodeBots taking Sunday.

**Comment by TheAlphaNerd** [comment]
Oh doodle... I just realized this is the same weekend as empire js.

I'll be in nyc

Womp Womp.

Sorry ya'll

**Comment by cantremember** [comment]
alright, so it April looks like a difficult month for scheduling ...

should we just open a new issue for May workshop scheduling?

**Comment by llkats** [comment]
I was also going to suggest seeing if Tradecraft wouldn't mind hosting us again. Otherwise, it is getting a bit late, so we might just look forward to the Node International Day event?

**Comment by jedireza** [comment]
@LizTheDeveloper what's the possibility of Tradecraft hosting us in April. Maybe the 25th? :wink:

**Comment by jedireza** [comment]
:facepunch: Since it's getting late in the month to make plans we may need to skip the April workshop.

:fireworks: We already have plans for our May workshop which is also [International Day](http://nodeschool.io/international-day/). For details see #46.

:v: Let's use this as an opportunity to schedule our workshops at least a month or two ahead.

**Comment by bryan-m-hughes** [comment]
FWIW we reworked the NodeBots SF meetup for this month too (simple open hack night during the week)...not enough time :(
