### ISSUE TITLE
Mentor registration for Saturday May 23rd: International Day

### ISSUE THREAD

**Issue by llkats** [nodeschool/sanfrancisco#62]
Blizzard(!!!) is hosting us on May 23rd from 1pm - 5pm. This is International Day, so it's sure to be a special event!

We will continue with the 5:1 attendee:mentor ratio and accept 40 attendees as before, which requires 8 mentors.

Mentors should commit to completing (or have already completed) the [core NodeSchool workshoppers](http://nodeschool.io/#workshopper-list) before the event. Having also completed elective workshoppers is a great bonus.

Comment to get involved or ask questions.

- - - - - -

Confirmed mentors:

 - [x] @TheAlphaNerd
 - [x] @cantremember
 - [x] @Trott
 - [x] @stevengill
 - [x] @wfro
 - [x] @bdeanindy
 - [x] @derekr 
 - [ ] ?

Organizers and helpers:

 - [ ] we'll miss you @jedireza!!
 - [x] @llkats
 - [x] @paulgrock

**Comment by llkats** [comment]
Pinging @cantremember, @Trott, and @TheAlphaNerd from the organization thread #46!

@paulgrock, shall I put you down as an organizer/helper?

**Comment by TheAlphaNerd** [comment]
MEMEMEMEMEMEMEMEMEMEMEMME

**Comment by asavpatel92** [comment]
Ohh....This was going be my first event with nodeschool. But I'm out of Bay
area that day... :'(

On Wed, May 6, 2015 at 12:04 PM, Lydia Katsamberis <notifications@github.com

**Comment by paulgrock** [comment]
@llkats yep, put me down for organizer/helper.

**Comment by llkats** [comment]
Thanks @TheAlphaNerd and @paulgrock!! :dancer: :dancer: :dancer:

**Comment by maxogden** [comment]
WoW what a great venue (hhahahahahaha)

On Wed, May 6, 2015 at 12:15 PM, Lydia Katsamberis <notifications@github.com

**Comment by llkats** [comment]
@maxogden I GET IT

**Comment by cantremember** [comment]
yes, @cantremember is jiggy with the Mentoriring

**Comment by llkats** [comment]
As the kids say :sunglasses:

**Comment by cantremember** [comment]
yeah.  i'm hip to their crunky jive

**Comment by bengl** [comment]
that's memorial day weekend right? probably not going to be around. sorry! next time.

**Comment by jedireza** [comment]
:airplane: Since I'll be in Europe I'll attempt a virtual check-in to say hi.
:camera: Don't forget a camera to take a group photo. A 35mm lens (or equivalent) is my recommendation.
:sparkles: Probably best to order stickers soon. I can help with this or share the creds with @llkats.

**Comment by Trott** [comment]
Totally in for mentoring. Sign me up!

**Comment by ryanstevens** [comment]
Love to mentor!  Available to help organize as well.

**Comment by llkats** [comment]
Thanks @Trott and @ryanstevens!! We'll miss you, @beng and @jedirezal!

I have a camera with a 35mm lens, and anyone else who wants to photograph, I'd also welcome. :)

@jedireza, if you could put the order for stickers in, I'd really appreciate it. I can DM you my address if you want to send them to me.

**Comment by jedireza** [comment]
@llkats will do. Last time we spoke we talked about purple stickers this round. Is that still a good plan?

**Comment by llkats** [comment]
@jedireza :shipit: :+1: :rocket: :guitar: :boom: :trophy:

**Comment by stevengill** [comment]
I'd like to mentor but I can't commit 100% at the moment. I am just waiting to hear back about the schedule of a hockey tournament I am playing in that weekend at yerba buena. I believe it should be a early morning or late evening game so I should be able to do it but want to confirm before committing 100%.

**Comment by wfro** [comment]
I'd love to mentor!  Just a few questions, is there a base level of experience you're looking for with mentors?  What's been the general level of folks attending?

**Comment by bdeanindy** [comment]
It would be my pleasure to be a mentor for the event. I'm completing the Core classes now and I'll get through the Electives prior to the event. Fun little way to learn JS...rather like Scala Koans.

I don't have any plans that weekend, and I'll bring my daughter along to the event so she can spend some time learning JS too! :)

**Comment by llkats** [comment]
Thnak you @stevengill, @wfro, and @bdeanindy!

@wfro: we typically have a range of people from complete beginners to programming/JavaScript who need help setting up their environments to people who are comfortable with Node and tackling the advanced workshoppers, like Streams Adventure. We try to organize people by which workshoppers they are working on so they can work together on problems.

@paulgrock et al., any thoughts on @bdeanindy's offers for sponsorship?

Speaking of sponsorship, @TheAlphaNerd gave us some jQuerySF discount codes as door prizes, does anyone have any ideas about how to publicize that fact besides tweeting about it?

**Comment by paulgrock** [comment]
@llkats and @bdeanindy I think blizzard had already planned on covering food but I'll double check on Monday. Speaking of which what kind of food would be good? Lunch or snacks?

**Comment by llkats** [comment]
@paulgrock I feel like snacks and beverages are great. We had pizza last time and it was a hit, but I think that's above and beyond. So... whatever Blizzard feels like donating I guess? How's that for a wishy-washy answer?

**Comment by paulgrock** [comment]
@llkats that was the perfect amount of wishy-washyness :) I think pizza at least should be doable but I'll find out Monday.

**Comment by llkats** [comment]
@paulgrock Great, thanks!

**Comment by llkats** [comment]
Anyone in this thread interested in helping out with coordinating other chapters on the event day? https://github.com/nodeschool/international-day/issues/45

**Comment by llkats** [comment]
I got us some International Day stickers! https://www.stickermule.com/marketplace/5544-nodeschool-international-sticker

Getting excited!!

**Comment by ryanstevens** [comment]
@llkats Sorry, a situation came up and I will not be able to mentor on the 23rd.  I Apologize for having to back out.

**Comment by llkats** [comment]
@ryanstevens no worries! Life happens. :) Thanks for letting us know, hope to see you next time!

**Comment by derekr** [comment]
I'd like to be a mentor! I've done about 7 of the workshops, but not all core. Will finish those this week.

**Comment by llkats** [comment]
Thanks, @derekr!!

**Comment by paulgrock** [comment]
@llkats would it be possible to get a list of attendees sometime Friday (or whenever the event is full) to pass on to the building security?

**Comment by llkats** [comment]
@paulgrock sure thing! I made a reminder to send that over to you on Friday. It's not looking full yet at all; I think a lot of people will be out of town for Memorial Day Weekend.

**Comment by derekr** [comment]
Should we get there a little early or anything? This is my first time mentoring so not 100% sure on what's expected. Looking forward to it!

**Comment by llkats** [comment]
@derekr you can come a bit early if you want, I'll be there by 12:45. See you soon!

**Comment by derekr** [comment]
Is there an actual address? The map for the event is just coordinates.

**Comment by paulgrock** [comment]
Address is 1145 Market

**Comment by stevengill** [comment]
Be there in about 5

**Comment by llkats** [comment]
Thanks to everyone for a wonderful event! Couldn't've done it without you -- Nodeschool SF runs on your support and help and thoughtfulness and dedication! :+1: :+1: :+1: :100: :fireworks: :joy_cat: :clap: :dancer:
