### ISSUE TITLE
Open attendee registration and update site

### ISSUE THREAD

**Issue by llkats** [nodeschool/sanfrancisco#63]
:construction_worker: :muscle:

**Comment by llkats** [comment]
@paulgrock could you please send me the address for Blizzard so I can add it to the attendee registration page?

**Comment by paulgrock** [comment]
Sure, it's 1145 Market St. 94103. Our office is on the 8th floor.

**Comment by llkats** [comment]
@paulgrock thanks much!

**Comment by llkats** [comment]
Registration is live and site is updated. Will do the social medializing tomorrow morn. :sleeping:
