### ISSUE TITLE
When and where for the June workshop?

### ISSUE THREAD

**Issue by jedireza** [nodeschool/sanfrancisco#64]
In spirit of getting ahead of the curve let's start kicking around ideas for June.

**Comment by jedireza** [comment]
:octocat: Maybe GitHub could be the venue?

**Comment by llkats** [comment]
You could try filling this form out again, maybe we'll actually hear back this time! https://community.github.com/

**Comment by stevengill** [comment]
I could also look into getting Adobe (7th and townsend) to host if you all have a day in mind. Capacity is like 100-200.

Adobe's 4th and townsend space might be available as well but seats less (40ish).

**Comment by jedireza** [comment]
Let's see if @skalnik can sponsor us at the GitHub office one of the Saturdays in June, the 27th maybe?

@stevengill thanks so much! Let's make the Adobe office our plan B for June. If GitHub works out, we could plan to meet at the Adobe office in July.

**Comment by skalnik** [comment]
I may be able to do that, but I have travel around then and am still trying to figure it all out. May be worth talking to Adobe first :smile_cat:

**Comment by jedireza** [comment]
Ok cool. @stevengill let's try to reserve the Adobe office for Saturday, June 27th.

I filled out the GitHub request form (mentioned above) for Saturday, July 25th.

**Comment by skalnik** [comment]
> I filled out the GitHub request form (mentioned above) for Saturday, July 25th.

Perfect! :metal: :heart:

**Comment by stevengill** [comment]
Alright, I put in the request at Adobe. Right now I said 12pm-6pm. We can change that once they confirm the space is available.

**Comment by jedireza** [comment]
Woo hoo! Thanks.

**Comment by stevengill** [comment]
Got confirmation our event has been approved by Adobe! 

Estimated attendance? Time of event? 

I will need to submit a list of attendees before the event so they can print badges in advance. 

Lots of time to figure stuff out. Let me know if you all have any questions for me or questions I can ask the events people here at Adobe.

**Comment by jedireza** [comment]
> Got confirmation our event has been approved by Adobe!

That's great news. I think this is the furthest ahead we've been with venue planning. :stuck_out_tongue_winking_eye:

> Estimated attendance? Time of event?

Ballpark guess of 50. Typically we invite 40 attendees + 8 mentors + 2-3 organizers.

> I will need to submit a list of attendees before the event so they can print badges in advance.

We can supply the list before the event.

- - - - -

Thanks again!! :pray:

**Comment by stevengill** [comment]
Not sure if it is relevant, but girldevelopit is doing a beginner hackathon the same weekend. http://girldevelopit.ticketleap.com/neohack/details

**Comment by jedireza** [comment]
Thanks for sharing. Let's stick with our plans.

**Comment by jedireza** [comment]
Update: There's a company offsite I'll be attending during the week of this workshop and I won't be able to help help organize this month. Apologies for any inconvenience this may cause. I will miss not being there.

If you can help organize this workshop let us know by commenting.

**Comment by llkats** [comment]
As I mentioned to some people at our last event, I will be traveling for a conference and also be unable to coordinate this time around. :sob::sob::sob: Please let us know if you can step up to lead the June event! It's pretty easy, just make opening/closing announcements, take a group picture, and do what you can to make people comfy. It's a great experience and super fun to boot!

**Comment by TheAlphaNerd** [comment]
Would people be into rolling it back a week?

**Comment by jedireza** [comment]
I could be there on the 20th. I don't think we should move the date though since we reserved the venue already. I also noticed that the following Saturday is July 4th (Independence Day).

**Comment by Trott** [comment]
I can do it.

**Comment by stevengill** [comment]
I can also help out with this. 

We should update the website and get registration open soon! If someone can point me in the right direction, I can do it!

**Comment by jedireza** [comment]
Perfect, thank you both so much. The show goes on :sparkles:

I'll setup the Tito registration tomorrow and update the site with the link. I'll also place the sticker order.

**Comment by jedireza** [comment]
Ok. The ticket registration page is live: https://ti.to/nodeschoolsf/june-27th-2015

What address should I send the stickers? Feel free to DM me jedireza:email:gmail.com.

**Comment by jedireza** [comment]
What's the correct address for the venue? Is it:
601 Townsend St San Francisco, CA 94103

**Comment by jedireza** [comment]
Thanks for the DM @trott, I know where to send the stickers now.

**Comment by Trott** [comment]
Just emailed you my address.

Other things that need to happen:

* Web site needs to be updated. Still shows event from May as next event.
* Form to get the event on the main NodeSchool home page needs to be filled out.

Anything else?

**Comment by jedireza** [comment]
I have a PR coming for the website now.

**Comment by Trott** [comment]
Oh, and if you're looking for photos from the May event to add to the page, I think @TheAlphaNerd took the photos this time.

**Comment by jedireza** [comment]
Website updated and mentor registration issue created. Once we get the final address we can spread the word.

**Comment by jedireza** [comment]
Sticker order placed. We're going green this round :wink:

![nodeschool-sf-4-sm](https://cloud.githubusercontent.com/assets/979929/8088522/d25bf102-0f56-11e5-81f7-6ff29e63bd34.png)

**Comment by asavpatel92** [comment]
What's the time for the event guys???

Asav

**Comment by stevengill** [comment]
Address is 601 Townsend St San Francisco, CA 94103

**Comment by jedireza** [comment]
@asavpatel92 1pm - 5pm. I've updated the website with the address and time.
http://nodeschool.io/sanfrancisco/

Also a Tweet:
https://twitter.com/nodeschoolsf/status/608696769417904128

**Comment by llkats** [comment]
I also have leftover stickers from last time that I can pass along to someone before I leave on the 23rd.
