### ISSUE TITLE
Organizing in the open

### ISSUE THREAD

**Issue by jedireza** [nodeschool/sanfrancisco#65]
@llkats and I are big fans of organizing in the open. During the last meeting we posted a wiki page of the [Announcements Script](https://github.com/nodeschool/sanfrancisco/wiki/Announcements-Script) which are just some notes for that day's organizers to make sure proper shout outs are given and that important info is covered (like the Code of Conduct) :pray:.

We've been charging a $5 cover for attendees to help separate the serious from the curious and also help cover costs of things like stickers.

__Some details on how things are currently setup...__ I setup a [Stripe](https://stripe.com/) account that we linked to a [Tito](https://ti.to/) account for ticket sales. That Stripe account is linked to my personal [Simple](https://www.simple.com/) bank account. When we've needed to make purchases, I paid for it with whatever card or cash available and kept the receipts.

You may wonder what happens with all those bags of money :moneybag::moneybag::moneybag: from the ticket sales.

To keep things transparent and make it easy for any future organizers to follow suit, we created a new branch on our repo called `ledger` where we can keep track of this stuff: https://github.com/nodeschool/sanfrancisco/tree/ledger

Feel free to ask questions or talk about related ideas. I plan to close this thread after a few days of inactivity.

**Comment by cantremember** [comment]
thank you for the transparency @jedireza @llkats

**Comment by llkats** [comment]
:clap: :clap: :clap: 

Love it!
