### ISSUE TITLE
mentor support

### ISSUE THREAD

**Issue by llkats** [nodeschool/sanfrancisco#68]
Had some questions about mentoring this session, which I was woefully ill-equipped to answer. This is a reminder issue to write up some mentorship guidelines in the wiki with advice for mentors attending the sessions, helpful hints, what to expect, and general reassurances. Ideas welcome!

**Comment by llkats** [comment]
Here's a stub page for the wiki: https://github.com/nodeschool/sanfrancisco/wiki/Mentorship-Guidelines-and-Advice

**Comment by Trott** [comment]
Perhaps some content to repurposes at https://github.com/nodeschool/organizers/wiki/Event-Mentor-Best-Practices and/or https://github.com/node-forward/mentors

**Comment by cantremember** [comment]
i have a set of notes that i was going to craft into a Wiki on just this very subject

if no one mindes, i'm assigning this Issue to myself -- i'll add a follow-up comment to this thread once there's something up there to review / edit

**Comment by cantremember** [comment]
also see https://github.com/nodeschool/organizers/issues/97

**Comment by llkats** [comment]
Ahh nice, thanks @Trott and @cantremember. I tried assigning you, Dan, but you don't appear in the list... maybe you need to be an owner? Not sure. But I look forward to seeing what you come up with!

**Comment by maxogden** [comment]
@trosetty was helping me write the content on the /organizers wiki linked
above at Write The Docs Conf last week in PDX, *and* she lives in SF!

On Mon, May 25, 2015 at 3:12 PM, Lydia Katsamberis <notifications@github.com

**Comment by cantremember** [comment]
i've gone and dumped a whole shit-ton of words into [Mentorship Guidelines and Advice](https://github.com/nodeschool/sanfrancisco/wiki/Mentorship-Guidelines-and-Advice).  it's opinionated and could use some editing, so other folks' oversight would be very much appreciated

i did not attempt to merge in any content from [Event Mentor Best Practices](https://github.com/nodeschool/organizers/wiki/Event-Mentor-Best-Practices).  my guess is that these Pages should be combined.  i'll leave it up to other folks to find a good balance of their content

IMHO the [Node Mentoring Program](https://github.com/node-forward/mentors) is intended for a different audience

**Comment by Trott** [comment]
I've only skimmed it so far, but I feel compelled to give you a virtual high five just on the amount of love and effort that went into writing and curating all that.

**Comment by jedireza** [comment]
:100: excellent work @cantremember!

**Comment by cantremember** [comment]
@Trott @jedireza gracias!

@maxogden @trosetty @llkats is there value in merging [Mentorship Guidelines and Advice](https://github.com/nodeschool/sanfrancisco/wiki/Mentorship-Guidelines-and-Advice) into [Event Mentor Best Practices](https://github.com/nodeschool/organizers/wiki/Event-Mentor-Best-Practices)? i would not presume to make such a bold Edit without a :+1: or :-1: from the current contributors

i suggest that any such merge should go in that direction because the latter Page is in the `nodeschool/organizers` namespace

**Comment by llkats** [comment]
Apologies for the late reply! I have been inundated. But aaaaahhhhhhhhhhh @cantremember! This is amazing!!! Very thorough and thoughtful. The only feedback I have is perhaps a section on what experience a mentor should have - I will write a quick paragraph up momentarily. Otherwise I think it's :+1: :+1: :+1:

I am all for merging it in -- seems like it'd be fairly straightforward to pull the existing content into your write-up. As long as the current contributors find it to be true to their experiences and general enough for all chapters to use, I think it's worth sharing fo sho. :clap: :clap: :clap:

**Comment by llkats** [comment]
Okay, updated with a little addition hooray!

**Comment by cantremember** [comment]
true.  the only experience i call out is "having done a Workshopper or two under your belt" and "earn extra :star: :banana: for Windows experience"

oh -- and you've already updated it.  *grazie* @llkats !

**Comment by jedireza** [comment]
Is there still pending action items that need to be done for this?

**Comment by d48** [comment]
:+1:  on having those Mentorship Guidelines be used for all chapters. I'm forwarding these to our [Los Angeles Chapter](https://github.com/nodeschool/los-angeles) to glean over to prep for our event this Saturday. Yay!

**Comment by llkats** [comment]
I think for this issue, we are waiting for official buy-in from core/senior/cool people to merge into the `nodeschool/organizers` wiki. Maybe we should make an issue over there?  Or just go for it, and people can revert if they feel strongly? At this point, I might be leaning towards the latter :sunglasses:

**Comment by jedireza** [comment]
:white_check_mark: latter

**Comment by Trott** [comment]
+1 for "just go for it".

**Comment by llkats** [comment]
@cantremember do you want to do the honors of merging in to `organizers`? :smile:

**Comment by llkats** [comment]
I'm just gonna go for this.

**Comment by llkats** [comment]
Merged. Hope people like it. https://github.com/nodeschool/organizers/wiki/Event-Mentor-Best-Practices/f39834570be351cb6f1ff35f4f6668c2d78e6992

**Comment by jedireza** [comment]
:boom: it's awesome

**Comment by cantremember** [comment]
i, for one, wholly endorse the Mentor Support Steering Comittee's decision :+1:
