### ISSUE TITLE
site design help

### ISSUE THREAD

**Issue by llkats** [nodeschool/sanfrancisco#7]
Would love to customize our site to differentiate from Campinas, which the site was forked from. Anyone feel like taking the reins?

Things to potentially tackle:
- background images, pictures
- color scheme
- custom icons?

**Comment by llkats** [comment]
I'm poking a bit at the design this weekend, fyi to anyone watching this issue.

**Comment by llkats** [comment]
I pushed some updates to https://github.com/nodeschool/sanfrancisco/tree/gh-pages-update

Changes:
- chose a muted rainbow color palette to represent SF (seems a strong signifier of SF outside of any sports context)
- pulled all images and fell back to solid blocks of color since I couldn't seem to find any CC-licensed images that worked well enough
- updated text to include some details about the event on the 7th (addressing #10)
- updated navigation to reflect fewer sections of the site

Still to do:
- finesse typography/layout in mobile and tablet break points
- add more details about the event somewhere maybe?
- arrange the footer's content layout to be a bit nicer
- pushstate with the navigation seems to break back-button functionality

Please send me feedback about all of this so far! Design is not my strong suit, so I felt that paring the images down helped me make something I was happier with. I know it's not perfect but I'm trying to get the appearance updated and also post info about the event before this weekend. Thanks!

**Comment by RichardLitt** [comment]
It looks pretty good to me. Do you want feedback in the form of commits or comments?
 * More padding would be good, particularly between text and dividers in the sections.
 * There's got to be some CC images, did you look on Flickr? Strange. 
 * Colors look good.
 * I would mute the font color for the footer text a bit, it stands out. Shrink the font size, too.

**Comment by jedireza** [comment]
Thanks @llkats, it's a great update! The rainbow color palette is a great idea. We'll have some of our own images after the first meeting, so I wouldn't worry about images for now. The lighter navigation is also nice.

I agree about the browser history stuff (referenced in #14), I'd like to just remove the browser history changes completely and use anchor links. I also agree that the break points for mobile/tablet do need to be adjusted, but I wouldn't hold up changes for that now.

The "calling mentors" GitHub link is incorrect. It should point here:
https://github.com/nodeschool/sanfrancisco/issues/15

After we fix the mentor link fix and the browser history stuff, I think we should go with it.

:sparkles::pray::sparkles:

**Comment by llkats** [comment]
All right! 

Re: images, I was of course searching Flickr, but I found myself spending hours trying to find the right one and messing with full-bleed backgrounds, and decided my time would be better spent fixing the rest of the stuff. I personally prefer feedback via comments, but I'm not exactly sure what the customary procedure is.

I'll try to incorporate all this feedback over lunch so we can get something pushed for sure this evening.

**Comment by RichardLitt** [comment]
Fair! Sounds good. :)

**Comment by llkats** [comment]
Updated!

- muted footer text color
- introduced more padding around sections
- pulled the pushstate js entirely
- fixed mentor and CoC links
- minor typography fixes for other view breakpoints

Will be back this evening around 7-8ish!

**Comment by llkats** [comment]
Also I made a PR, let's move discussion over there herp derp.

**Comment by RichardLitt** [comment]
Looks good!

I would remove 'We're excited to see you', but that may just be me. Also, the period in 'Click here to buy a ticket' should be within the tag, too.

**Comment by llkats** [comment]
Merged.
