### ISSUE TITLE
Oakland Nodeschool help

### ISSUE THREAD

**Issue by llkats** [nodeschool/sanfrancisco#70]
Due to some great conversations at our last event, there is some movement to get a regular Oakland Nodeschool going again. If you are so inclined to pitch in, let them know [at the issue in their repo](https://github.com/nodeschool/oakland/issues/8)!

**Comment by llkats** [comment]
Note: I'd love for there to be conversation/symbiosis between East/West Bay chapters, so that we can assist as many people in the Bay Area as possible and support each other collectively. :sunny: :sunglasses: :dancer:

**Comment by jedireza** [comment]
> I'd love for there to be conversation/symbiosis between East/West Bay chapters, so that we can assist as many people in the Bay Area as possible and support each other collectively.

:sunglasses: I can dig it.

**Comment by smallhaxe** [comment]
Ditto.

And thanks, again, for organizing such an awesome international day workshop, nodeschoolsf!
