### ISSUE TITLE
Mentor Registration for June 27th 2015

### ISSUE THREAD

**Issue by jedireza** [nodeschool/sanfrancisco#72]
Adobe is hosting us on June 27th from 1pm - 5pm. The address is: 601 Townsend St SF, CA 94103

We like to stay close to a 5:1 attendee:mentor ratio. We're accepting up to 50 attendees for this workshop. So we'll need 8-9 mentors.

Mentors should commit to completing (or have already completed) the [core NodeSchool workshoppers](http://nodeschool.io/#workshopper-list) before the event. Having also completed elective workshoppers is a great bonus.

Comment to get involved or ask questions.

Confirmed mentors:

 - [x] @bengl 
 - [x] @paulgrock
 - [x] @smallhaxe

Organizers and helpers:

 - [x] @trott
 - [x] @stevengill

**Comment by bengl** [comment]
:ok: :rocket: :helicopter:

Also I recently bought a Windows laptop for other reasons. Bonus: Can now help Windows people.

**Comment by jedireza** [comment]
Sweet! :shipit: Thanks @bengl

**Comment by paulgrock** [comment]
I'm in for mentoring or helping out as needed

**Comment by jedireza** [comment]
Thanks @paulgrock :+1:

**Comment by jedireza** [comment]
FYI: As of now, we've had 15 attendee registrations. It may be a small event.

**Comment by Trott** [comment]
It's Pride weekend. (You'd think I'd remember this, as it's my birthday, so this happens to me every year.) Traffic, transit, everything, is likely to be challenging. Especially [if you're going near Dolores Park](http://www.thedykemarch.org/#!the-plan/c5i3). If it's not too late, we might want to reach out to attendees, inform them of this, and see if they still want to come. I'm fine with still doing it. But it's probably a good idea to warn people that they may have to give themselves extra travel time etc.

**Comment by jedireza** [comment]
I'd rather not ask people if they want to come still. They did register :wink:

**Comment by Trott** [comment]
Yeah, good point. I guess we should just do an extra push and be OK with a low turnout this time if that's what comes to pass.

**Comment by jedireza** [comment]
Having many for few attendees shouldn't change change our disposition. And yes, let's get the word out as much as possible.

**Comment by Trott** [comment]
If two people show up, we will do everything we can to make sure they have AN AMAZING NODESCHOOL EXPERIENCE.

We will even go ALL CAPS if we have to.

Because that's how much we care.

**Comment by stevengill** [comment]
I'm sure it will be fine! @jedireza could I get the list of people who have registered? I need to submit it to Adobe to get badges made. People who register after can still register at the front desk on the day of the event.

**Comment by jedireza** [comment]
:+1: @stevengill I sent the list to your gmail (I found it on your GH profile).

**Comment by Trott** [comment]
It's too bad we didn't realize the Pride confluence earlier and order rainbow-colored stickers. Note To Self for next year.

**Comment by smallhaxe** [comment]
@jedireza, I'll be available to help. This is assuming I can still register at the door, as you mentioned, @stevengill.

**Comment by jedireza** [comment]
@smallhaxe thanks!

**Comment by Trott** [comment]
@stevngill What time should I show up? Do I need to bring anything other than the stickers? (And dare I ask how weekend parking is near 601 Townsend when there's both Pride events at Dolores Park and everywhere else and also a game at AT&T Park? Should have gotten my bicycle repaired this month...)

**Comment by stevengill** [comment]
We can definitely handle registration at the door.

You can look around for parking Rich. I could probably get you into the
Adobe garage as well if you don't find anything easily.

I'll be there 12:20ish.

**Comment by stevengill** [comment]
Closer to 12:30 actually.

**Comment by bengl** [comment]
I'm on my way. Any door codes or security shenanigans?

**Comment by Trott** [comment]
I didn't realize @smallhaxe was there as a mentor! Someone should have corrected me every time I said there were 4 mentors. (I can be forgiven a little because he was a few minutes late, right?)

I think we can close this thread now....
