### ISSUE TITLE
Experiment with free tickets

### ISSUE THREAD

**Issue by jedireza** [nodeschool/sanfrancisco#74]
I'm starting not to like having a paywall for attendees. We started charging to separate the serious from the curious and to help offset the minor costs we incur (ex: stickers/food). We've seen that even if people pay for their ticket that many (~40%) still no-show.

The costs are low to host a workshop. I'd like to try getting financial sponsors and having a free Tito registration for attendees.

Thoughts? Concerns?

**Comment by Trott** [comment]
I'm all in favor of this. (Of course, I have to deal with exactly none of the logistical issues it may create, so it's easy for me to say. So, let me know if there's something I can do to assist.)

**Comment by jedireza** [comment]
Our next event is at Mozilla's SF office. One requirement was that the event had to be free to attend. So I guess we'll see how it goes.

Closing this issue for now. We'll see how it goes.
