### ISSUE TITLE
Group Photo From 27-Jun-2015 Event

### ISSUE THREAD

**Issue by Trott** [nodeschool/sanfrancisco#75]
![img_2090](https://cloud.githubusercontent.com/assets/718899/8394975/50fcceba-1d07-11e5-8fa0-6aedad609c72.jpg)
![img_2091](https://cloud.githubusercontent.com/assets/718899/8394977/543c5c62-1d07-11e5-848c-05c482da0f99.jpg)
![img_2092](https://cloud.githubusercontent.com/assets/718899/8394978/56c5dada-1d07-11e5-90af-27c0c52878cc.jpg)
![img_2093](https://cloud.githubusercontent.com/assets/718899/8394979/5be6a8f0-1d07-11e5-9118-f2e269bb2a2a.jpg)
![img_2094](https://cloud.githubusercontent.com/assets/718899/8394981/5f743a46-1d07-11e5-8e25-eb2c6054cf04.jpg)

**Comment by Trott** [comment]
Some are kind of blurry I guess, but that's what you get for not showing up and bringing your awesome camera, @jedireza. Speaking of showing up and bringing an awesome camera, did you ever get the group photos from International Day that (I think) @thealphanerd took?

**Comment by Trott** [comment]
Also, @jedireza, I have a dozen leftover stickers. I can bring them to the next event, or if you want them sooner, uh, they're with me in the Excelsior.

**Comment by jedireza** [comment]
Thanks @Trott. We can connect when it's convenient (probably next event).

**Comment by llkats** [comment]
Aw cuties :heart_eyes:

**Comment by TheAlphaNerd** [comment]
I'll upload the photos from international day when I get home

sorry i'm such a slacker :P

**Comment by jedireza** [comment]
Closing since these are on the site now.
