### ISSUE TITLE
Update ledger

### ISSUE THREAD

**Issue by jedireza** [nodeschool/sanfrancisco#77]
- [ ] add sticker order
 - [ ] add pizza order (June workshop)

**Comment by llkats** [comment]
Do you need any docs from me from May?

**Comment by jedireza** [comment]
@llkats if you have any items that are not on the ledger let's add them.

@stevengill would you send me your pizza receipt from June 27th?

**Comment by llkats** [comment]
Added the ticket orders from May!

**Comment by jedireza** [comment]
Now that we're not charging for ticket, I wonder about the usefulness of the ledger.

**Comment by jedireza** [comment]
Closing. Feel free to re-open if you feel strongly about this.
