### ISSUE TITLE
Planning our July 25th workshop

### ISSUE THREAD

**Issue by jedireza** [nodeschool/sanfrancisco#78]
FYI: I'm working to get access to the Mozilla SF commons. I'll update this thread as I learn more.

UPDATE: Mozilla office confirmed.

 - - - - -

 - [x] create attendee (Tito) registration
 - [x] create mentor (GitHub) registration

**Comment by llkats** [comment]
Ping @potch!!

**Comment by llkats** [comment]
Also I will be around for this one -- besides CascadiaJS shenanigans from the 7th - 11th, I'll be around for planning and stuff. Please feel free to assign/delegate to me!!

**Comment by jedireza** [comment]
Thanks @llkats. I met @potch IRL last week in Whistler. His karaoke game is strong. :wink: 

Also, I just got confirmation that the space is ours. This event will be free and Mozilla is going to sponsor the pizza. :sparkles: :+1: :sparkles:

**Comment by TheAlphaNerd** [comment]
Is July 25th locked? This is the same day as node bots international day, which has been in the planning for a couple months

**Comment by jedireza** [comment]
Yeah we're booked for the 25th.

**Comment by TheAlphaNerd** [comment]
womp womp.... Guess I'll have to sit this one out :cry:

**Comment by jedireza** [comment]
Phewey. That's a bummer :cry:

**Comment by itnok** [comment]
Are you already booked up for the July 25th workshop? If not I'd love to join...

**Comment by jedireza** [comment]
@itnok not yet :wink:

When we open the attendee/mentor registration I'll update this thread so you should get a notification.

**Comment by itnok** [comment]
That's awesome! Thank you @jedireza

**Comment by jedireza** [comment]
Ok we're all set. Registration is open. Closing this issue.
