### ISSUE TITLE
Dev Bootcamp Proposal to host nodeschool event

### ISSUE THREAD

**Issue by fitchaj** [nodeschool/sanfrancisco#79]
Folks,

I was referred to nodeschool from a recent event attendee and, after learning about the program, I'd like to explore hosting an event at our coding bootcamp program. 

Location: 633 Folsom Street, San Francisco, CA 94107 

We have a lot of space here and believe it to be a good fit for your needs. Please contact me at andrew@devbootcamp.com. I'll happily show a scout around the space, if you'd like. 

Thanks!

Andrew Fitch
781-812-5465
andrew@devbootcamp.com

**Comment by fitchaj** [comment]
Also, I am flexible on times and dates.

**Comment by jedireza** [comment]
@fitchaj that's so nice of you all! We will keep this in mind for future events. Feel free to participate in any of our workshops. We almost always communicate via GitHub, you can keep an eye out by watching this repo. :pray:

**Comment by fitchaj** [comment]
Thanks @jedireza! I'll hope to host in the future.
