### ISSUE TITLE
set up Google Analytics account

### ISSUE THREAD

**Issue by llkats** [nodeschool/sanfrancisco#8]
Set up a Google Analytics account for the site so we can track engagement.

**Comment by llkats** [comment]
Don't forget to get the site updated with the GA tracking code.

**Comment by jedireza** [comment]
The Google Analytics account is setup. I've sent invites to @duquet and @llkats. I'll create a PR now to install it.

**Comment by llkats** [comment]
Looks great! :eggplant: :+1: :grinning: :goat: :dash:
