### ISSUE TITLE
Mentor Registration for July 25th 2015

### ISSUE THREAD

**Issue by jedireza** [nodeschool/sanfrancisco#80]
Mozilla is hosting us on July 25th from 1pm - 5pm. The address is: 2 Harrison St, San Francisco, CA 94105

As before, we'd like to stay close to a 5:1 attendee:mentor ratio. We're accepting up to 50 attendees for this workshop. So we'll need about 10 mentors.

Mentors should commit to completing (or have already completed) the [core NodeSchool workshoppers](http://nodeschool.io/#workshopper-list) before the event. Having also completed elective workshoppers is a great bonus. We also encourage mentors to review the [Mentorship Guidelines and Advice](https://github.com/nodeschool/sanfrancisco/wiki/Mentorship-Guidelines-and-Advice) wiki page.

Comment to get involved or ask questions.

Confirmed mentors:

 - [x] @LindsayElia
 - [x] @Trott 
 - [x] @erikasf
 - [x] @paulgrock
 - [x] @prattsj 
 - [x] @derekr
 - [x] @upekabee
 - [x] @stevengill
 - [x] @groundwater
 - [x] @negomi
 - [x] @bengl

Organizers and helpers:

 - [x] @jedireza
 - [x] @llkats

**Comment by LindsayElia** [comment]
Hello! I would love to be a mentor. I spent the past 2 months learning JavaScript and Node at Galvanize in SF. Please check out my GitHub or let me know if you have questions. I'm familiar with about half of the material in the core NodeSchool workshoppers and can complete the remaining ones by the date of this event.

**Comment by Trott** [comment]
In for mentoring!

**Comment by jedireza** [comment]
@LindsayElia Yay! Thank you!

@Trott Woot Thank you!

**Comment by erikasf** [comment]
Hi, please include me in the mentor category. I am familiar with nodeJS and  will finish the material by the date .

**Comment by paulgrock** [comment]
I'm in

**Comment by jedireza** [comment]
@erikasf @paulgrock Fantastic! Thank you both!

**Comment by prattsj** [comment]
Hey there, I'd love to sign up as a mentor. I've been developing and maintaining production node.js apps for ~3 years now. I'll be sure to complete the workshoppers before the event.

**Comment by llkats** [comment]
I just want to say YASSSSSS

💃💃💃💃💃

**Comment by jedireza** [comment]
@prattsj Boom! Thank you!

**Comment by jedireza** [comment]
@llkats Yassss back atcha!

**Comment by derekr** [comment]
I can mentor for this event!

**Comment by jedireza** [comment]
Oh I almost forgot to ask. Are any of the current mentors Windows users?

Sending a shout out to @bengl if he's able to join us.

**Comment by jedireza** [comment]
@derekr Good stuff. Thank you!

**Comment by upekabee** [comment]
Hi, I have experience building a node app for my startup. I'd love to mentor for this event. I'll complete the workshoppers before the event.

**Comment by jedireza** [comment]
@upekabee Very cool. Thank you!

**Comment by Trott** [comment]
Pinging @smallhaxe and @stevengill

**Comment by stevengill** [comment]
I'll be there! I will be a little late though.

**Comment by jedireza** [comment]
@stevengill Super. Thank You!

**Comment by groundwater** [comment]
@jedireza I can mentor.

**Comment by jedireza** [comment]
@groundwater Awesome. Thanks!

UPDATE: I extended the attendance to 50 so we'll need about 10 mentors.

We'll likely need some mentor support for Windows users. Which of the current mentors have experience with node on Windows?

**Comment by negomi** [comment]
I'd love to mentor if you're still looking. I've recently moved to SF from the UK, and was working as an engineer back in London. I'll complete the workshoppers before the event.

**Comment by jedireza** [comment]
@negomi welcome to SF and thanks!

**Comment by wfro** [comment]
In for mentoring if you still have room!

**Comment by jedireza** [comment]
@wfro thank you! We just reached our goal of 10 mentors. If anyone cancels, we'll update this thread.

**Comment by smallhaxe** [comment]
@jedireza, @Trott I'll be there, too, although it seems your mentors list is quite full (nice problem to have)!

**Comment by asavpatel92** [comment]
Hi guys...are on space constraint at Mozilla? because registration is closed I was hoping to be able to bring in my couple of friends.

**Comment by jedireza** [comment]
@asavpatel92 we are fully booked. We're going send an email to the attendees who registered, encouraging anyone who is unsure about attending, to return their ticket so others (like your friends) have a chance to attend.

**Comment by asavpatel92** [comment]
@jedireza thanks... (y)

**Comment by bengl** [comment]
Tentatively in for mentoring. (Sorry for late reply.)

**Comment by jedireza** [comment]
Thanks @bengl. We'll keep you posted since we're already at 10 mentors.

**Comment by jedireza** [comment]
@LindsayElia, @Trott, @erikasf, @paulgrock, @prattsj, @derekr, @upekabee, @stevengill, @groundwater, @negomi

Do you have experience using node on Windows?

**Comment by Trott** [comment]
I've installed it on a Windows VM to test some Windows-specific stuff, but I don't have a lot of experience with it. In a pinch, I can be the designated Windows person, but I hope we have someone for whom Windows is their usual environment...

**Comment by LindsayElia** [comment]
@jedireza No, sorry!

**Comment by jedireza** [comment]
@LindsayElia no apologies necessary. :smile:

**Comment by bengl** [comment]
i'm sorry!

**Comment by cantremember** [comment]
i am also sorry :computer: :fire:

**Comment by jedireza** [comment]
:wink: No worries if you don't have experience with Windows, I don't. 

I would like to make sure attendees who may need help with Windows environments how a quality experience. I'd like to invite @bengl and @cantremember to join us so we have support for those who may need it.

**Comment by jedireza** [comment]
Oh and I almost forgot! @cantremember created a great piece on [Mentorship Guidelines and Advice](https://github.com/nodeschool/sanfrancisco/wiki/Mentorship-Guidelines-and-Advice).

I would encourage everyone to review it before the event.

**Comment by cantremember** [comment]
thank you for the kind words, @jedireza 

i've never actually used Node in a Windows environment.  i'm just good at speaking from another hypothetical person's' perspective :blush:

**Comment by stevengill** [comment]
I have a windows VM setup with node and could help with issues if required.

**Comment by jedireza** [comment]
Fantastic! Thanks @stevengill

**Comment by bengl** [comment]
I might put a few Windows tips in that doc (unless there's a better place for it. maybe a new doc?)

**Comment by jedireza** [comment]
@bengl the wiki is open, let's create a new page and link to it from that mentor guide as needed.

**Comment by cantremember** [comment]
+1 for new page.  Windows Skillz are an entirely independent topic
