### ISSUE TITLE
Update website media

### ISSUE THREAD

**Issue by jedireza** [nodeschool/sanfrancisco#82]
We have a bunch of photos to add to the website. I think we could do better than the wide horizontal images we currently have. Maybe something more like a carousel could serve us better long term and not limit us to just one photo per event.

**Comment by goodbedford** [comment]
Hey Reza,
I think that is a good idea to have some sort of carousel. Has someone already attempted to add it? I could throw my name in the hat.  I would need a about a week and a half to do it. My current schedule is pretty hectic.  Do you have any ideas for the design?

**Comment by jedireza** [comment]
@goodbedford thanks for getting involved. Nobody has claimed this issue yet. When you create a PR just be sure to reference this issue in the description and they'll get linked together.

I don't have any ideas about the design. We are currently using Boostrap and they've created a [carousel component](http://getbootstrap.com/javascript/#carousel) that we get for free.

**Comment by llkats** [comment]
This seems done with @goodbedford's PR :+1:
