### ISSUE TITLE
6th Month Commemorative Sticker

### ISSUE THREAD

**Issue by jedireza** [nodeschool/sanfrancisco#88]
Can you believe this month's workshop is already our 6th event?! So far we've used the [stock NodeSchool hexagon sticker](http://www.finnpauls.de/nodeschool-stickerify/) using different colors for each month. I'm thinking for this month we could use all the colors of our previous stickers together. Thanks @llkats for the idea about inverting the artwork.

![nodeschool-sf-1-5](https://cloud.githubusercontent.com/assets/979929/9153257/ef9cdd9e-3dff-11e5-82e4-2c4aa0a19a1c.png)

![nodeschool-sf-6](https://cloud.githubusercontent.com/assets/979929/9153263/8607d996-3e00-11e5-83a5-f5f0c0b99b52.png)

**Comment by llkats** [comment]
I want to marry that sticker 😍😍😍

**Comment by Trott** [comment]
:+1:

**Comment by paulgrock** [comment]
Oooh, those are nice!

**Comment by jedireza** [comment]
The order has been placed. These stickers will be ours. Oh yes, they will be ours!
