### ISSUE TITLE
set up Meetup group and/or Tito account for rsvps

### ISSUE THREAD

**Issue by llkats** [nodeschool/sanfrancisco#9]
Per discussion [here](https://github.com/nodeschool/sanfrancisco/issues/1#issuecomment-69632435), we need to track RSVPs and charge a nominal entrance fee to ensure attendance. Let's discuss which method we want to use (Meetup and/or Tito) and get those accounts created. After creation, update the site with links to the signup page(s).

**Comment by RichardLitt** [comment]
BrooklynJs uses [Peatix](http://peatix.com/), which seemed to work well. Not sure about Tito, and MeetUp is functional (but I don't like their UI, not sure why). Daybreaker uses [Splash](http://splashthat.com/) which looks cool...

**Comment by groundwater** [comment]
Meetup seems to get weirdo randos who just appear to drink beer and eat pizza.

Also our awesome marketing peoples can help get the word out.

**Comment by conrado** [comment]
suggestion, drop the free beer, keep the free speech

**Comment by jedireza** [comment]
I signed up for a Tito and Stripe account and linked them. Sent invites to @llkats and @duquet.

To finish setting up the event with Tito, we'll need to know the maximum number of attendees. @groundwater do you or @agminusthev know that number?

**Comment by agminusthev** [comment]
@jedireza We were talking about having 35 attendees. Mentors will not need to get a ticket so that's probably our max number.

**Comment by jedireza** [comment]
Ticket registration is live: https://ti.to/nodeschoolsf/feb7

If anyone notices something that should be corrected or improved please let me know. This is my first time using Tito.

**Comment by noelledaley** [comment]
Hey! Like @groundwater said, I (Noelle, NR's community steward) can help get the word out on New Relic's social channels (as well as my own) if you'd like. Just let me know what you'd like to share and when.

We have plenty of space for everyone so capacity won't be an issue, at least as far as the venue goes. I'd imagine you'd want to keep a certain mentor:student ratio though. Sounds like @agminusthev already has it sorted. :)

Let me know if I can help with anything else!

**Comment by groundwater** [comment]
Thank you @noelledaley ! :bow:

**Comment by agminusthev** [comment]
@noelledaley is on point!

**Comment by llkats** [comment]
Yay, thanks everyone! I'm also letting code-curious people at my job know about the event, and am also planning on emailing the Double Union (https://www.doubleunion.org/) mailing list to let them know about the event.

**Comment by groundwater** [comment]
@llkats here is some cake for being awesome :cake:

**Comment by agminusthev** [comment]
We have the space reserved and the ticket registration live. What else do we need to do before the event?

- Sell tickets
- Confirm at least 7 mentors (we're close if we're not already there)
- Day of, make the magic happen

**Comment by linclark** [comment]
I can mentor.

**Comment by groundwater** [comment]
I can mentor :+1:
