### ISSUE TITLE
Mentor Registration for September 26th 2015

### ISSUE THREAD

**Issue by jedireza** [nodeschool/sanfrancisco#92]
Mozilla is hosting us on September 26th from 1pm - 5pm. The address is: 2 Harrison St, San Francisco, CA 94105

As before, we'd like to stay close to a 5:1 attendee:mentor ratio. We're accepting up to 50 attendees for this workshop. So we'll need about 10 mentors.

Mentors should commit to completing (or have already completed) the [core NodeSchool workshoppers](http://nodeschool.io/#workshopper-list) before the event. Having also completed elective workshoppers is a great bonus. We also encourage mentors to review the [Mentor Best Practices](https://github.com/nodeschool/organizers/wiki/Event-Mentor-Best-Practices) wiki page.

Comment to get involved or ask questions.

Confirmed mentors:

 - [x] @Trott 
 - [x] @isurfbecause
 - [x] @bengl
 - [x] @upekabee
 - [x] @prattsj
 - [x] @Fauntleroy 
 - [x] @negomi 
 - [x] @smallhaxe
 - [x] @wfro
 - [x] @azat-co

Organizers and helpers:

 - [x] @jedireza
 - [x] @llkats

**Comment by Trott** [comment]
In!

**Comment by Trott** [comment]
I wouldn't mind leading a session the way @llkats did this last time. But if she or someone else already has something planned, I can wait! I have something specific in mind and can get into it offline (or here).

**Comment by cantremember** [comment]
regretfully, i cannot Mentor this one.  hopefully i'll be there for the one in October :ghost:

**Comment by jedireza** [comment]
Thanks @Trott :+1: 

See you next time @cantremember :scream:

**Comment by paulgrock** [comment]
Sadly, I'm out of town that weekend. Sorry @jedireza

**Comment by jedireza** [comment]
@paulgrock :sob: I'll try to get over this.

**Comment by llkats** [comment]
In!

Definitely not up for leading a focused session, though -- that would be all you, @Trott!!

**Comment by isurfbecause** [comment]
I'm in as a mentor. I cannot wait.

**Comment by jedireza** [comment]
@isurfbecause thanks! :ice_cream:

**Comment by bengl** [comment]
yo. in.

**Comment by jedireza** [comment]
@bengl great to hear, thanks! :roller_coaster:

**Comment by upekabee** [comment]
In! :)

**Comment by jedireza** [comment]
@upekabee yay! Thank you. :cake:

**Comment by jedireza** [comment]
:mega: pinging some previous mentors:

@negomi @prattsj @erikasf @LindsayElia

**Comment by prattsj** [comment]
I'm in!

**Comment by jedireza** [comment]
@prattsj woohoo! Thank you. :candy:

**Comment by Fauntleroy** [comment]
![you_have_my_sword](https://cloud.githubusercontent.com/assets/507047/9800954/f4567b22-57c4-11e5-82d5-39c7e3b86890.gif)

**Comment by negomi** [comment]
Also in! :cat:

**Comment by smallhaxe** [comment]
I'm in, if you still need folks!

**Comment by jedireza** [comment]
@Fauntleroy haha. Thank you. :dart:

@negomi fantastic! Thank you. :raised_hands: 

@smallhaxe perfect! Thank you. :zap:

**Comment by wfro** [comment]
:dancers: I'm in as well (looks like there's a couple more spots?) :dancers:

**Comment by jedireza** [comment]
@wfro happy to hear it. Thank you. :dancer:

**Comment by LindsayElia** [comment]
Sorry not this time. Please ping me next month though. I'm working on a final project for school this month. After that I should be have much more free time to help out, which I'm looking forward to!

**Comment by Trott** [comment]
Maybe @goodbedford wants to mentor this time around?

**Comment by jedireza** [comment]
@LindsayElia sounds good. Wish you well with your final project. Until next time.

**Comment by llkats** [comment]
Omggggg it's this Saturdayyyyyy :fireworks:

**Comment by Fauntleroy** [comment]
![newspaper_ecstasy](https://cloud.githubusercontent.com/assets/507047/10064732/8e11cbde-6230-11e5-9b92-d77378be2153.gif)

# GET HYPE

**Comment by goodbedford** [comment]
@group I will be in the building, helping where I can. But full fledge mentor, not ready yet. Still need to finish a couple more workshops. I will when the time is right. By the way everyone, I just graduated from my General Assembly Bootcamp. It was a whirlwind, now I was lucky enough to also get a job there as a Developer in Residence for the next 3 months. My role will be to Assist the Instructors on the Education Team and a lot of mentoring for the next cohort starting Monday. I am sure I will be able to encourage some more node schoolers to join.  I also will have a little more free time. Yay

**Comment by isurfbecause** [comment]
nice to hear, things are rolling for you @goodbedford

**Comment by goodbedford** [comment]
Oh and @llkats I meet one of your coworkers by the name of Sam( I think) at a family gathering. He couldn't say enough good things about you and how you helped him personal develop in many ways. We were talking about imposter syndrome and how with your help( I don't know if you know) he over came it. Later

**Comment by jedireza** [comment]
![stickerz](https://cloud.githubusercontent.com/assets/979929/10065667/5f7c0d80-623e-11e5-84fe-f689a3bb1343.jpg)

**Comment by Fauntleroy** [comment]
@jedireza 

![colbert_give](https://cloud.githubusercontent.com/assets/507047/10065698/d34e830a-623e-11e5-8f41-09c33b146022.gif)

**Comment by jedireza** [comment]
@goodbedford congrats on graduating GA! No pressure for being a mentor. The invite is always open.

@Fauntleroy in due time... in due time. :cake:

**Comment by azat-co** [comment]
@jedireza still need mentors? I can help.

**Comment by jedireza** [comment]
@azat-co that'll be great. Thanks! :+1:

**Comment by azat-co** [comment]
@jedireza cool

**Comment by jedireza** [comment]
Thanks everyone! It was a great day. :tada: :confetti_ball: :fireworks:
