### ISSUE TITLE
November and December 2015

### ISSUE THREAD

**Issue by jedireza** [nodeschool/sanfrancisco#93]
We've been keeping a nice cadence and hosting events on the last Saturday of the month. In October, November and December, this could prove difficult. :wink:

What days should we host events during these months?

**Comment by goodbedford** [comment]
Maybe the second Sat for those months.

**Comment by Fauntleroy** [comment]
Whatever you decide, we should try and ensure that Nodeschool Oakland can sync up.

**Comment by jedireza** [comment]
Yup. NodeSchool Oakland was one of the first things that came to mind.

**Comment by llkats** [comment]
Maybe we could do some joint sessions, especially in November/December when lots of people are busy with hectic schedules. One in Oakland one month, and one in SF the other month?

**Comment by Fauntleroy** [comment]
NodeSchool holiday party!

**Comment by paulgrock** [comment]
I like @llkats idea of alternating between Oak and SF for Nov and December. For October we could still have it on the last Saturday, Halloween, and tell people they can come dressed up if they want.

Off topic: I love the idea of NodeSchool holiday party. We talked about something like mentor Thanksgiving which could be really fun.

**Comment by jedireza** [comment]
> Off topic: I love the idea of NodeSchool holiday party. We talked about something like mentor Thanksgiving which could be really fun.

Yes, since we talked on Saturday, I've been thinking of hosting a mentor appreciation day. We could invite the previous mentors from SF and OAK and invite them to the top floor of MozSF and have an evening balcony mixer looking out over the bay. What better month than November. Amirite :tada: 

![moz-sf-roof-1](https://cloud.githubusercontent.com/assets/979929/9595603/4709da12-501d-11e5-92a1-951bac4ab2ea.jpg)
![moz-sf-roof-2](https://cloud.githubusercontent.com/assets/979929/9595602/47094e8a-501d-11e5-8c82-9a89b7a8a784.jpg)
![moz-sf-roof-3](https://cloud.githubusercontent.com/assets/979929/9595604/470a87aa-501d-11e5-83cf-a2d7404dc9e1.jpg)

**Comment by llkats** [comment]
This would be amazing. I love the view from Moz SF's balcony!

It'd be especially great if @brianloveswords were there too :grinning:

**Comment by jedireza** [comment]
> It'd be especially great if @brianloveswords were there too :grinning:

That was a pleasant surprise when I was looking for images :mag:

**Comment by Fauntleroy** [comment]
@jedireza After seeing those photos I'm now even more flummoxed that we didn't go up there Saturday! :anguished:

**Comment by jedireza** [comment]
:shipit:

**Comment by brianloveswords** [comment]
hahahaha amazing :dancer:

**Comment by brianloveswords** [comment]
Also I wish I *could* go!

**Comment by llkats** [comment]
@brianloveswords you will be with us in spirit :ghost: :hearts:

**Comment by smallhaxe** [comment]
+1 for alternating Nov/Dec between SF/Oak.

+1 for second or third Saturdays of both months (14 or 21 Nov and 12 or 19 Dec) to hopefully accommodate most schedules.

+1 for parties (and themes)!

**Comment by jedireza** [comment]
:pager: ping pong. Usually I'd put in the reservation for the Mozilla SF space now-ish. We should try to pick dates and venues soon.

**Comment by Fauntleroy** [comment]
I'm working on getting in touch with @isaacs for the October event at npm. Were we planning on doing a combined event next month?

**Comment by jedireza** [comment]
We could combine next month sure. With a focus on dates before venues, and a target day of Saturday:

 - __October__:
  - 17th or the 24th
  - I'm pretty confident we can get the Mozilla SF space in October.
 - __November__:
  - FYI Node Knockout is November 7th-8th.
  - 14th or the 21st
 - __December__: 
  - 12th or the 19th

We can take longer talking about options for November and December. But October should get nailed down first. If we end up using the Mozilla space, let's book it soon.

**Comment by paulgrock** [comment]
Have we decided what the plan is for October? If not my thought would be we keep it simple since we need to secure the space soon and move it up from the 31st to 24th. Then we can figure out if we're going to alternate between Oakland and SF for Nov/Dec.

**Comment by Fauntleroy** [comment]
I haven't been able to contact anyone at NPM about an October event, so I'm going to move on to planning for November. A NodeSchool SF event on the 24th sounds good to me!

**Comment by austocratic** [comment]
Will we be doing another breakout session this month?  

Which of the Workshoppers would be advantageous to do a Breakout lecture instead of self-paced?

If we don't do another breakout lecture, I think it would be cool for a group of NodeSchoolers to team up and work through one of the Electives (Maybe off to the side from the main group).  I think this would promote repeat NodeSchoolers as they come back to take on more advanced subjects.

Would the mentors be able to support the Elective Workshoppers?

**Comment by JacksonTech** [comment]
First time NodeSchooler here (visited September). I like the idea of working through one of the Electives as a group. You might be able to encourage NodeSchoolers to work as small groups within a larger one (occasionally this happens naturally). Sometimes, it happens that when one group gets ahead of the others, they'll start to wander around and help out other people, which lessens the dependency/workload on a small number of mentors and makes the event overall more fun. Is there any way this behavior can be fostered?

**Comment by austocratic** [comment]
A question I want to ask:

Which is more aligned with the goals & mission of NodeSchool: To provide an introduction to Node, or advance Node learning?  Or are both equally as important to NodeSchool?

I want to ask that question before I get too deep in brainstorming about ideas for advancing the learning of repeat NodeSchool attendees?

If NodeSchool SF becomes too crowded with intermediate Node Developers would this hurt the open & receptive environment it is so good at fostering?

**Comment by jedireza** [comment]
> I haven't been able to contact anyone at NPM about an October event, so I'm going to move on to planning for November. A NodeSchool SF event on the 24th sounds good to me!

:calendar: I'd like to try reserving MozSF for October 24th. If you'd like to propose an alternative, I'll wait about 24 hours before moving forward. The venue blocks other logistics (tickets, promotion, etc...).

> Will we be doing another breakout session this month?

Great question. I'm not sure yet. If so we'll need to pick a workshopper and find someone to lead it. We're open to ideas here.

> Would the mentors be able to support the Elective Workshoppers?

Yes, some mentors have completed a lot of workshoppers and some have done only the core. It really depends on which mentors are able to join. Usually if one mentor doesn't know the answer to another question they'll ask another mentor.

> I like the idea of working through one of the Electives as a group. You might be able to encourage NodeSchoolers to work as small groups within a larger one (occasionally this happens naturally). [...] Is there any way this behavior can be fostered?

Yes we typically mention forming groups and working together. Maybe we missed saying that precisely in the intro last month (September). I've added a note about that in our announcements wiki page under the format section: https://github.com/nodeschool/sanfrancisco/wiki/Announcements-Script#format

> Which is more aligned with the goals & mission of NodeSchool: To provide an introduction to Node, or advance Node learning? Or are both equally as important to NodeSchool?

Yes both are important. We'll try to adapt to the audience. As a side note completing all the workshoppers doesn't make you an intermediate/advanced node programmer, it does give you a better perspective of the landscape.

Reflecting more on this, these classifications (beginner/intermediate/advanced) seem silly to me. We will welcome all people and foster learning in a friendly and save environment.

> I want to ask that question before I get too deep in brainstorming about ideas for advancing the learning of repeat NodeSchool attendees? [...] If NodeSchool SF becomes too crowded with intermediate Node Developers would this hurt the open & receptive environment it is so good at fostering?

I'm a fan of the open format and don't think a lot about how to change it. The group workshoppers were the first experiment we did with a slightly different style. Most importantly, I think it's best to let things happen naturally and adapt to the attendees needs. Some attendees even come and work on their side projects and ask for help when they get stuck.

**Comment by Trott** [comment]
No matter who you are, there are parts of Node and/or its ecosystem where you are a beginner. There's just too much there to know everything and it moves too quickly.

The whole mentor/attendee dichotomy is largely arbitrary. Basically, to be a mentor, you should do the six or eight core workshoppers. But beyond that, it's really all about whether you feel comfortable taking on the "mentor" designation or not. It's totally OK (in my book, anyway) to be both a mentor and an attendee at the same event.

I think the most important thing is to maintain a welcoming atmosphere that facilitates people learning whether its own their own, in peer groups, or with the help of someone more knowledgable about the particular area of study. The question of whether it should focus on beginners or more advanced folks really comes down to the needs of whoever showed up that day.

**Comment by jedireza** [comment]
Well put @Trott, thanks! :clap: :cake: :shipit:

**Comment by llkats** [comment]
I wonder if there's a way we can facilitate intermediate/advanced peeps organizing and pairing up a little more. I like the self-directed part of Nodeschool, but understand that not everyone has the assertiveness or know-how to organize themselves. Project-based groups would be a fun thing once people are past the workshoppers themselves.

In the one Oakland Nodeschool that I attended (in another lifetime, maybe a year ago?), we walked through the setup of an actual project. Maybe that could be another option for the focused group workshop, or we could have a show-and-tell type session where we walk through someone's codebase to demonstrate organizational concepts, etc etc.

Perhaps on our sign-up page, we could explain and solicit project ideas (maybe in the form of a poll?) so that (intermediate/advanced) people come primed with any pairing or small-group projects they'd like to work or get help on, hackathon-style. After announcements, we should have people with ideas come up to the front and identify themselves so others can congregate and organize.

At some point, I would like to have an advanced group take a look at `streams-adventure` with an eye toward improving and updating it, forking it if necessary. I could facilitate discussion, but as a streams noob myself, I'd need a lot of technical support. (N.B., I'm moving this month, so probably will not have time to prepare a focused session for October.)

Those are my ideas! Hoping October 24th works!

**Comment by jedireza** [comment]
Thanks for sharing @llkats. :tada: :fireworks: I really like the thought of recruiting people to help maintain and/or update workshoppers.

**Comment by mikeal** [comment]
Do we have any idea what the average state of participation is in maintaining workshoppers? Do they tend to be "OPEN Open Source" or are they often just a single maintainer? Maybe we should have a push to get liberal contribution policies adopted in these projects and then push people in to them once we're confident they can retain contributors?

**Comment by jedireza** [comment]
Great questions. Specifically looking at the core workshoppers:

| Workshopper | Downloads last month (npm) | Maintainer(s) | Open Issues | Open PRs |
| ------------------ | -------------------------------------- | ------------------ | ----------------- | -------------- |
| [javascripting](https://www.npmjs.com/package/javascripting) | 4,717 | [sethvincent](https://github.com/sethvincent/) | 13 | 3 |
| [learnyounode](https://www.npmjs.com/package/learnyounode) | 9,539 | [rvagg](https://www.npmjs.com/~rvagg), [julianduque](https://www.npmjs.com/~julianduque), [leichtgewicht](https://www.npmjs.com/~leichtgewicht) | 77 | 15 |
| [git-it](https://www.npmjs.com/package/git-it) | 2,769 | [jlord](https://www.npmjs.com/~jlord) | 16 | 0 |
| [how-to-npm](https://www.npmjs.com/package/how-to-npm) | 1,420 | [isaacs](https://www.npmjs.com/~isaacs), [linclark](https://www.npmjs.com/~linclark) | 22 | 11 |
| [scope-chains-closures](https://www.npmjs.com/package/scope-chains-closures) | 1,134 | [jesstelford](https://www.npmjs.com/~jesstelford) | 5 | 0 |
| [stream-adventure](https://www.npmjs.com/package/stream-adventure) | 1,928 | [substack](https://www.npmjs.com/~substack), [cwmma](https://www.npmjs.com/~cwmma), [maxogden](https://www.npmjs.com/~maxogden), [julianduque](https://www.npmjs.com/~julianduque) | 33 | 19 |

We might want to take these ideas into another thread, but now that I see it in a matrix, I'm even more interested in the discussion.

**Comment by jedireza** [comment]
:ghost: October is in motion.

_Changes title of the thread so we can focus on November and December details._

**Comment by jedireza** [comment]
A discussion started in the Oakland repo about a November event. https://github.com/nodeschool/oakland/issues/15

I mentioned it there but wanted to echo it here to... I will be out of town for most of November and December. So we'll need to find another Mozillian that's willing to be a host in December in order to use the Mozilla SF space.

**Comment by llkats** [comment]
I vote for taking a Nodeschool Secular Winter Holiday in December and jump to planning January instead.

**Comment by jedireza** [comment]
Taking December off sounds good to me.

**Comment by lizTheDeveloper** [comment]
Hey guys! I changed jobs and now I'm working at Galvanize. We have a much bigger space, with classroom tables and a lot of openness.
We're at 44 Tehama, and I'd love to host- we have way more instructors here too, and we'd love to get more involved with NodeSchool re: mentoring, etc. 
If you want to host an event, just let me know the dates. We could probably pull something off in November if you need help, our Evangelists can do a lot of the legwork for ya.

**Comment by lizTheDeveloper** [comment]
@jedireza and @llkats and @mikeal bump

**Comment by llkats** [comment]
Hi @lizTheDeveloper!! Congrats on the new gig, that's awesome! Let's chat in the new year - we've been generously hosted by Mozilla for the past few sessions, and while it's been great having a steady home base, I like the idea of shaking up the routine as well. We'll be partnering with Nodeschool Oakland for November and taking December off, so let's definitely touch base once everyone's back from the holidays. :smile:

**Comment by llkats** [comment]
The tl;dr of this thread is:

Go to Nodeschool Oakland in November!
Go outside in December!
Let's meet back at Nodeschool SF in January. See you all then! :heart: :sparkles: :snowman:

**Comment by jedireza** [comment]
@lizTheDeveloper very cool! Congrats on joining Gavanize. Changing the venue up will also be nice, mabye overdue even. :+1:
