### ISSUE TITLE
Focused session for September 26th

### ISSUE THREAD

**Issue by jedireza** [nodeschool/sanfrancisco#95]
We're still waiting-for/gathering feedback from the Git-It session that @llkats led. From what I saw it seemed liked a win and went really well.

Should we do another Git-It session? Has anyone had other ideas for focused sessions?

Let the :coffee: talk begin.

**Comment by jedireza** [comment]
:pager: @Trott

**Comment by Trott** [comment]
Conventional idea: Do the npm workshop so people get an idea of how to publish their own modules. I'm not particularly interested in leading that session, but I think it's a solid choice.

Unconventional idea: If we think we're getting enough intermediate JS folks, I'd like to help people get a gentle introduction to contributing to Node itself. The code base can be intimidating to approach, but there are some easy ways to get involved. Not all contributions need to be code, of course. And the ones that are code aren't necessarily *in* Node as much as around Node. (I personally think helping with tests is a great way to get involved. You get to learn a sliver of the code base at a time, and tests are given a bit more freedom in the coding conventions department than other parts of the code base.)

For the second one, if we *don't* think we're getting enough intermediate folks, I'd *still* love to do it for interested mentors (although depending who is in the mentor pool, I might not be telling people stuff they don't already know, but that's OK).

**Comment by paulgrock** [comment]
If we don't go with option 2 @Trott you should give a "Contributing to Node" talk at SF Node.

**Comment by jedireza** [comment]
> Conventional idea: Do the npm workshop so people get an idea of how to publish their own modules.

:+1: It would be _really great_ if a rep from npm came to lead that session.

> Unconventional idea: If we think we're getting enough intermediate JS folks, I'd like to help people get a gentle introduction to contributing to Node itself.

:+1: Let's gauge interest. Even if only a few people were interested we could dedicate that side area (where the private offices are) where you could lead a small group to start. Maybe the take-aways from this could turn into a real-deal NodeSchool workshopper.

**Comment by Trott** [comment]
On the npm idea, @linclark maybe? Although...if someone works at npm, it might be kind of brutal to ask them to volunteer to do this on a Saturday.

**Comment by Trott** [comment]
@paulgrock Only if you can think of a snappier title.

**Comment by paulgrock** [comment]
@Trott awww man. Naming things is hard.

**Comment by jedireza** [comment]
> Although...if someone works at npm, it might be kind of brutal to ask them to volunteer to do this on a Saturday.

Haha why? This sounds like a perfect community outreach event for them.

**Comment by llkats** [comment]
Love the idea of another focused session, especially the npm one. I'd love to host the `git-it` session again in the future, though I definitely will not have my stuff together to run a session in September. Definitely down to mentor/support anyone who would like to, though.

The focused session was pretty intense from a leading standpoint... I think that someone should only lead if they are particularly enthused and ready to take the event on.

**Comment by bengl** [comment]
If no one from npm, Inc. can make it, I can definitely fill in to lead an npm session.

**Comment by jedireza** [comment]
I'm liking the idea of a focused npm workshopper session. :shipit: I'd like to get a ti.to ticket setup for this soon.

:pager: @linclark, @isaacs, @seldo

**Comment by jedireza** [comment]
I'd like to open a focused session for the npm workshopper led by @bengl.

@bengl you still up for it?

**Comment by bengl** [comment]
Sure. It would still probably be best if an npm-er could do it, but I'm happy to fill in.

**Comment by Trott** [comment]
@zkat? @ehsalazar?

**Comment by jedireza** [comment]
It's official. @bengl is leading a how-to-npm workshopper.
