### ISSUE TITLE
CoC response and resources

### ISSUE THREAD

**Issue by llkats** [nodeschool/sanfrancisco#96]
Hey folks,

On a more serious note, I've been thinking a little bit about what we'd actually do if we experience a code of conduct violation at a Nodeschool event. Beyond asking someone to leave, I am not entirely sure what actions I would take, and I think that a codified response would be best. I found this page as a resource: http://geekfeminism.wikia.com/wiki/Conference_anti-harassment/Responding_to_reports, which seems like a good starting point. I'd definitely be interested in any other resources people find.

Maybe we could even hold a smaller event for people interested in getting trained in conflict resolution, perhaps with a trained mediator or other professional. We could make a workshopper out of the material we learn, to keep it Nodeschooly. :)

This issue is sort of a placeholder for me, to approach in a few weeks once I'm back from traveling. Would love discussion and thoughts in the meantime. Thanks!

**Comment by Trott** [comment]
If I recall correctly (and apologies in advance if I am not), at the outset of the events, it tends to get announced that CoC violations can be reported to mentors. It may make sense to narrow that (say, to organizers or some other identifiable and narrow set of individuals). 

Mentors are pretty much anybody who says "I'd like to mentor!". We're trusting people we may not know at all to handle very challenging and potentially volatile situations. If such a situation were to arise, that would probably be unfair to pretty much everyone involved.

**Comment by jedireza** [comment]
> Beyond asking someone to leave, I am not entirely sure what actions I would take, and I think that a codified response would be best. I found this page as a resource: http://geekfeminism.wikia.com/wiki/Conference_anti-harassment/Responding_to_reports, which seems like a good starting point.

@llkats great link. Thank you for sharing this. It was WAY more detail that I expected before clicking. They rock :guitar:

> If I recall correctly (and apologies in advance if I am not), at the outset of the events, it tends to get announced that CoC violations can be reported to mentors. It may make sense to narrow that (say, to organizers or some other identifiable and narrow set of individuals). 

@Trott yeah we should be more clear who can take charge in these situations. For mentors not prepared to handle these situations, the default can be to bubble the information back up to someone who is able to take action.

> Maybe we could even hold a smaller event for people interested in getting trained in conflict resolution

@llkats I like this idea.

**Comment by llkats** [comment]
I'm going to close this for now while we're taking a break for the holidays. Will re-open for further discussion in the new year!
