### ISSUE TITLE
An official hexagon sticker for SF

### ISSUE THREAD

**Issue by jedireza** [nodeschool/sanfrancisco#97]
So this happened tonight  :open_hands: :microphone: ... :walking: ... :v:

![sticker-demo](https://cloud.githubusercontent.com/assets/979929/9809756/e479a1f6-581f-11e5-9c7d-cce5d9531dba.png)

We still need to see how it'll come out printed.

**Comment by TheAlphaNerd** [comment]
amazing!

**Comment by d48** [comment]
That looks great! @jcblw

**Comment by paulgrock** [comment]
Whoa! Love it 💜

**Comment by Fauntleroy** [comment]
@jedireza who made it?

**Comment by jedireza** [comment]
@Fauntleroy You can blame me. :wink:

**Comment by jcblw** [comment]
nice work @jedireza !

**Comment by Trott** [comment]
Someone needs to make an animated gif of this with Godzilla Cat With Laser Eyes coming out of the fog to attack the bridge, but then those sea gulls get closer and it turns out they're pterodactyls and not sea gulls at all, and they're rushing to attack Gozilla Cat With Laser Eyes before it can attack the bridge.

Nice work! I look forward to sporting this on my laptop.

**Comment by jdaudier** [comment]
We're currently in the process of making one for NodeSchool NYC too.  Would love to see @jedireza's take on this too.

**Comment by d48** [comment]
> Someone needs to...
@Trott , this...is a great idea :smile:

**Comment by xtuc** [comment]
Very nice!

**Comment by cantremember** [comment]
i believe the appropriate colloqualism is :+1:

**Comment by jedireza** [comment]
Thanks everyone. I'm glad so many of you like it. My plan is to get a set printed and see how they turn out. Hopefully they'll arrive in time for the upcoming workshop (26th).

> We're currently in the process of making one for NodeSchool NYC too. Would love to see @jedireza's take on this too.

@jdaudier it's been a long time since I put on my graphic design hat. I'm actually still surprised at the result, I think it was a fluke. :blush: 

Also, there is so many parts of SF this graphic doesn't capture. Many months ago when we discussed having a graphic, I remember the Transamerica building, Sutro Tower and Golden Gate Bridge were elements that resonated with us at the time. NYC is rich in landmarks and culture too. You should think about what resonates with your group.

**Comment by LindsayElia** [comment]
looks awesome!
